### ISSUE TITLE
[tests] Not all tests are run on Link all

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#11243]
Enabling LinkAll tests on tvOS / dotnet showed some test failures.
Those failures were not seen in iOS / dotnet... and, upon inspection, did not seems to be executed **nor excluded**

# iOS Unified 64-bits - simulator

* Debug: `Tests run: 68 Passed: 68 Inconclusive: 0 Failed: 0 Ignored: 1`
* Debug [dotnet]: `Tests run: 62 Passed: 62 Inconclusive: 0 Failed: 0 Ignored: 7`

# tvOS - simulator

* Debug: `Tests run: 93 Passed: 93 Inconclusive: 0 Failed: 0 Ignored: 2` <- Success! that's more tests than iOS above
* Debug [dotnet]:  `Tests run: 84 Passed: 77 Inconclusive: 0 Failed: 7 Ignored: 8` <- More than iOS, with failures

# Failures

```
[FAIL] Assembly_Load : System.IO.FileNotFoundException : Could not load assembly. File not found: mscorlib.dll 
[FAIL] Assembly_ReflectionOnlyLoadFrom : System.PlatformNotSupportedException : PlatformNotSupported_ReflectionOnly 
[FAIL] DetectPlatform : Mono.Runtime 
[FAIL] DoubleEpsilon_ToString : Epsilon.ToString() 
[FAIL] LinkedAwayGenericTypeAsOptionalMemberInProtocol : NSSet<T> must be linked away, otherwise this test is useless 
[FAIL] NoFatCorlib : /Users/poupou/Library/Developer/CoreSimulator/Devices/D0CE3484-536C-4593-BEBF-AE36A64D84D7/data/Containers/Bundle/Application/64083F94-B09B-4EB5-910F-95B49811EF94/link all.app/System.Private.CoreLib.dll 
[FAIL] SingleEpsilon_ToString : Epsilon.ToString() 
```

Some failures might be _normal_ when run on dotnet, IOW some adjustments are required.

**Comment by spouliot** [comment]
For iOS, both legacy and dotnet, there's nothing executed for `LinkAllRegressionTest`.

```
LinkAll.LinkAllRegressionTest
LinkAll.LinkAllRegressionTest : 2 ms
```

For tvOS legacy

```
LinkAll.LinkAllRegressionTest
	[PASS] AnonymousType
	[PASS] Aot_27116
	[PASS] AppleTls
	[PASS] Assembly_Load
	[PASS] Assembly_LoadFile
	[PASS] Assembly_LoadFrom
	[PASS] Assembly_ReflectionOnlyLoadFrom
	[IGNORED] AssemblyReferences_16213 : Assumption broken with mono 2017-12
	[PASS] Bug14456
	[PASS] Bug20363
	[PASS] Bug59015
	[PASS] DetectPlatform
	[PASS] DoubleEpsilon_Compare
	[PASS] DoubleEpsilon_ToString
	[PASS] Events
	[PASS] GetterOnly
	[PASS] LinkedAwayGenericTypeAsOptionalMemberInProtocol
	[PASS] MEF_3862
	[PASS] NestedNSObject
	[PASS] NoFatCorlib
	[PASS] OpenTk10_Preserved
	[PASS] RemovedAttributes
	[PASS] SetterOnly
	[PASS] SingleEpsilon_Compare
	[PASS] SingleEpsilon_ToString
	[PASS] SystemDataSqlClient
	[PASS] TrustUsingOldPolicy
	[PASS] UltimateBindings
	[PASS] WebKit_NSProxy
LinkAll.LinkAllRegressionTest : 1573 ms
```

For tvOS dotnet

```
LinkAll.LinkAllRegressionTest
	[PASS] AnonymousType
	[PASS] Aot_27116
	[PASS] AppleTls
	[FAIL] Assembly_Load : System.IO.FileNotFoundException : Could not load assembly. File not found: mscorlib.dll
		   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext) in System.Private.CoreLib.dll:token 0x60021e8+0x2d
		   at System.Reflection.Assembly.Load(String assemblyString) in System.Private.CoreLib.dll:token 0x60021e6+0x1f
		   at LinkAll.LinkAllRegressionTest.Assembly_Load() in /Users/poupou/git/main/xamarin-macios/tests/linker/ios/link all/LinkAllTest.cs:line 250
		   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6002355+0x6a
	[PASS] Assembly_LoadFile
	[PASS] Assembly_LoadFrom
	[FAIL] Assembly_ReflectionOnlyLoadFrom : System.PlatformNotSupportedException : PlatformNotSupported_ReflectionOnly
		   at LinkAll.LinkAllRegressionTest.Assembly_ReflectionOnlyLoadFrom() in /Users/poupou/git/main/xamarin-macios/tests/linker/ios/link all/LinkAllTest.cs:line 299
		   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6002355+0x6a
	[IGNORED] AssemblyReferences_16213 : Assumption broken with mono 2017-12
	[PASS] Bug14456
	[PASS] Bug20363
	[PASS] Bug59015
	[FAIL] DetectPlatform :   Mono.Runtime
  Expected: not null
  But was:  null

		   at LinkAll.LinkAllRegressionTest.DetectPlatform() in /Users/poupou/git/main/xamarin-macios/tests/linker/ios/link all/LinkAllTest.cs:line 217
	[PASS] DoubleEpsilon_Compare
	[FAIL] DoubleEpsilon_ToString :   Epsilon.ToString()
  Expected string length 21 but was 6. Strings differ at index 0.
  Expected: "4.94065645841247E-324"
  But was:  "5E-324"
  -----------^

		   at LinkAll.LinkAllRegressionTest.DoubleEpsilon_ToString() in /Users/poupou/git/main/xamarin-macios/tests/linker/ios/link all/LinkAllTest.cs:line 415
	[PASS] Events
	[PASS] GetterOnly
	[FAIL] LinkedAwayGenericTypeAsOptionalMemberInProtocol :   NSSet<T> must be linked away, otherwise this test is useless
  Expected: null
  But was:  <Foundation.NSSet`1[TKey]>

		   at LinkAll.LinkAllRegressionTest.LinkedAwayGenericTypeAsOptionalMemberInProtocol() in /Users/poupou/git/main/xamarin-macios/tests/linker/ios/link all/LinkAllTest.cs:line 597
	[PASS] MEF_3862
	[PASS] NestedNSObject
	[FAIL] NoFatCorlib :   /Users/poupou/Library/Developer/CoreSimulator/Devices/D0CE3484-536C-4593-BEBF-AE36A64D84D7/data/Containers/Bundle/Application/64083F94-B09B-4EB5-910F-95B49811EF94/link all.app/System.Private.CoreLib.dll
  Expected: String ending with "link all.app/mscorlib.dll"
  But was:  "/Users/poupou/Library/Developer/CoreSimulator/Devices/D0CE3484-536C-4593-BEBF-AE36A64D84D7/data/Containers/Bundle/Application/64083F94-B09B-4EB5-910F-95B49811EF94/link all.app/System.Private.CoreLib.dll"

		   at LinkAll.LinkAllRegressionTest.NoFatCorlib() in /Users/poupou/git/main/xamarin-macios/tests/linker/ios/link all/LinkAllTest.cs:line 626
	[PASS] RemovedAttributes
	[PASS] SetterOnly
	[PASS] SingleEpsilon_Compare
	[FAIL] SingleEpsilon_ToString :   Epsilon.ToString()
  Expected string length 12 but was 5. Strings differ at index 1.
  Expected: "1.401298E-45"
  But was:  "1E-45"
  ------------^

		   at LinkAll.LinkAllRegressionTest.SingleEpsilon_ToString() in /Users/poupou/git/main/xamarin-macios/tests/linker/ios/link all/LinkAllTest.cs:line 394
	[PASS] UltimateBindings
	[PASS] WebKit_NSProxy
LinkAll.LinkAllRegressionTest : 175.9214 ms
```

**Comment by spouliot** [comment]
AFAICS things are compiled correctly, all attributes (`[Test]`, `[TestFixture]`) are present.

NUnitLite returns `68` tests for the assembly - which does not include any form `LinkAll.LinkAllRegressionTest`.

The `NUNITLITE_NUGET` is defined - so it's not the same code we used before. However it's also defined for tvOS... which returns `94` tests found.

**Comment by spouliot** [comment]
Updating to NUnitLite 3.13.1 does not find any (`0`) tests...

but we're back to `68` (not enough by like 3.12) if we use Link SDK. That's likely an unrelated issue, but one that needs fixing too.

Debugging with sources...

```
Platform setting deteremined invalid, cannot set 'Introduced' to '592128' as it is already set for the same platform to 'None'
```

```
  at ObjCRuntime.AvailabilityAttribute.Check (System.String property, ObjCRuntime.Platform existing, ObjCRuntime.Platform updated) [0x00008] in /Users/poupou/git/main/xamarin-macios/src/ObjCRuntime/PlatformAvailability.cs:354 
  at ObjCRuntime.AvailabilityAttribute.set_Introduced (ObjCRuntime.Platform value) [0x00000] in /Users/poupou/git/main/xamarin-macios/src/ObjCRuntime/PlatformAvailability.cs:371 
  at ObjCRuntime.AvailabilityAttribute..ctor (ObjCRuntime.Platform introduced, ObjCRuntime.Platform deprecated, ObjCRuntime.Platform obsoleted, ObjCRuntime.Platform unavailable) [0x00006] in /Users/poupou/git/main/xamarin-macios/src/ObjCRuntime/PlatformAvailability.cs:469 
  at ObjCRuntime.iOSAttribute..ctor (System.Byte major, System.Byte minor, System.Byte subminor) [0x00000] in /Users/poupou/git/main/xamarin-macios/src/ObjCRuntime/PlatformAvailability.cs:521 
  at ObjCRuntime.iOSAttribute..ctor (System.Byte major, System.Byte minor) [0x00000] in /Users/poupou/git/main/xamarin-macios/src/ObjCRuntime/PlatformAvailability.cs:516 
  at (wrapper managed-to-native) System.MonoCustomAttrs.GetCustomAttributesInternal(System.Reflection.ICustomAttributeProvider,System.Type,bool)
  at System.MonoCustomAttrs.GetCustomAttributesBase (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inheritedOnly) [0x00013] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/corlib/System/MonoCustomAttrs.cs:128 
  at System.MonoCustomAttrs.GetCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Boolean inherit) [0x00011] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/corlib/System/MonoCustomAttrs.cs:295 
  at System.Reflection.RuntimeMethodInfo.GetCustomAttributes (System.Boolean inherit) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:499 
  at NUnit.Framework.Internal.AsyncToSyncAdapter.IsAsyncOperation (System.Reflection.MethodInfo method) [0x00001] in /Users/poupou/git/nunit/src/NUnitFramework/framework/Internal/AsyncToSyncAdapter.cs:37 
  at NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.CheckTestMethodSignature (NUnit.Framework.Internal.TestMethod testMethod, NUnit.Framework.Internal.TestCaseParameters parms) [0x000f7] in /Users/poupou/git/nunit/src/NUnitFramework/framework/Internal/Builders/NUnitTestCaseBuilder.cs:183 
  at NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.BuildTestMethod (NUnit.Framework.Interfaces.IMethodInfo method, NUnit.Framework.Internal.Test parentSuite, NUnit.Framework.Internal.TestCaseParameters parms) [0x00022] in /Users/poupou/git/nunit/src/NUnitFramework/framework/Internal/Builders/NUnitTestCaseBuilder.cs:63 
  at NUnit.Framework.TestAttribute.BuildFrom (NUnit.Framework.Interfaces.IMethodInfo method, NUnit.Framework.Internal.Test suite) [0x00022] in /Users/poupou/git/nunit/src/NUnitFramework/framework/Attributes/TestAttribute.cs:132 
  at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildSingleTestMethod (NUnit.Framework.Interfaces.IMethodInfo method, NUnit.Framework.Internal.Test suite) [0x00009] in /Users/poupou/git/nunit/src/NUnitFramework/framework/Internal/Builders/DefaultTestCaseBuilder.cs:155 
  at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildFrom (NUnit.Framework.Interfaces.IMethodInfo method, NUnit.Framework.Internal.Test parentSuite) [0x000ec] in /Users/poupou/git/nunit/src/NUnitFramework/framework/Internal/Builders/DefaultTestCaseBuilder.cs:122 
  at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildTestCase (NUnit.Framework.Interfaces.IMethodInfo method, NUnit.Framework.Internal.TestSuite suite) [0x00001] in /Users/poupou/git/nunit/src/NUnitFramework/framework/Internal/Builders/NUnitTestFixtureBuilder.cs:229 
  at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.AddTestCasesToFixture (NUnit.Framework.Internal.TestFixture fixture, NUnit.Framework.Interfaces.IPreFilter filter) [0x0005c] in /Users/poupou/git/nunit/src/NUnitFramework/framework/Internal/Builders/NUnitTestFixtureBuilder.cs:202 
  at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom (NUnit.Framework.Interfaces.ITypeInfo typeInfo, NUnit.Framework.Interfaces.IPreFilter filter, NUnit.Framework.Interfaces.ITestFixtureData testFixtureData) [0x002d7] in /Users/poupou/git/nunit/src/NUnitFramework/framework/Internal/Builders/NUnitTestFixtureBuilder.cs:174 
  at NUnit.Framework.TestFixtureAttribute+<BuildFrom>d__47.MoveNext () [0x00023] in /Users/poupou/git/nunit/src/NUnitFramework/framework/Attributes/TestFixtureAttribute.cs:269 
  at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom (NUnit.Framework.Interfaces.ITypeInfo typeInfo, NUnit.Framework.Interfaces.IPreFilter filter) [0x0005e] in /Users/poupou/git/nunit/src/NUnitFramework/framework/Internal/Builders/DefaultSuiteBuilder.cs:98 
```

so it seems newer version of NUnit are instantiating the attributes... and some are broken (the short-hand versions we normally use for bindings) and it turns out those were removed in `XAMCORE_3_0` which explains why the tests were included in tvOS builds.

The fixes are to 

- [ ] Remove the attributes in the test, which are not even tested in the code;
- [ ] Find a way to have that exception show something in our tests results;
- [ ] Make the current stable version of NUnit (3.13.1) work;
- [ ] Correct the (old) typo in the error message 😸

**Comment by spouliot** [comment]
Main issue (not all test ran) fix is merged with https://github.com/xamarin/xamarin-macios/commit/94caf968ccbc97d3167a92db1ad5322ea06c2cd9

nunit 3.13.1 situation tracked in https://github.com/xamarin/xamarin-macios/issues/11292
