### ISSUE TITLE
VS2019 Automatic Provisioning fails with System.ObjectDisposedException

### ISSUE THREAD

**Issue by isness** [xamarin/xamarin-macios#11517]
### Steps to Reproduce

1.  Go to Automatic provisioning in iOS porject settings.
2.  Select your team
3.  The provisioning starts
4.  Fails after "Creating certificate" with "Automatic provisioning failed, please check the logs"

The exception in the log:
```
Xamarin.Messaging.Exceptions.MessagingRemoteException: An error occurred on client IDBLocal169000292 while executing a reply for topic xvs/idb/auto-provision ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Http.StringContent'.
   at System.Net.Http.HttpContent.CheckDisposed()
   at System.Net.Http.HttpContent.CopyToAsync(Stream stream, TransportContext context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.MacDev.AppleSigning.DeveloperPortalWebClient.<>c__DisplayClass25_0.<<Request>b__2>d.MoveNext() in /Users/builder/azdo/_work/1/s/External/maciostools/Xamarin.MacDev.AppleSigning/AppleDeveloperPortal/DeveloperPortalWebClient.cs:line 127
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.MacDev.AppleSigning.DeveloperPortalWebClient.<Request>d__25.MoveNext() in /Users/builder/azdo/_work/1/s/External/maciostools/Xamarin.MacDev.AppleSigning/AppleDeveloperPortal/DeveloperPortalWebClient.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.MacDev.AppleSigning.AuthorizedDeveloperPortalClient.<RequestAuthorized>d__7.MoveNext() in /Users/builder/azdo/_work/1/s/External/maciostools/Xamarin.MacDev.AppleSigning/AppleDeveloperPortal/AuthorizedDeveloperPortalClient.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.MacDev.AppleSigning.AuthorizedDeveloperPortalClient.<Request>d__4.MoveNext() in /Users/builder/azdo/_work/1/s/External/maciostools/Xamarin.MacDev.AppleSigning/AppleDeveloperPortal/AuthorizedDeveloperPortalClient.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.MacDev.AppleSigning.AppleDeveloperPortal.<CreateCertificate>d__24.MoveNext() in /Users/builder/azdo/_work/1/s/External/maciostools/Xamarin.MacDev.AppleSigning/AppleDeveloperPortal/AppleDeveloperPortal.cs:line 215
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.MacDev.AppleSigning.CreateCertificate.<Run>d__9.MoveNext() in /Users/builder/azdo/_work/1/s/External/maciostools/Xamarin.MacDev.AppleSigning/ProvisioningTasks/CreateCertificate.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.MacDev.AppleSigning.ResolveCertificate.<Run>d__13.MoveNext() in /Users/builder/azdo/_work/1/s/External/maciostools/Xamarin.MacDev.AppleSigning/ProvisioningTasks/ResolveCertificate.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.IDB.AppleProvisioningManager.<AutoProvisionAsync>d__20.MoveNext() in C:\A\1\1\s\src\Messaging\Xamarin.Messaging.IDB.Local\AppleProvisioningManager.cs:line 369
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.IDB.Local.AutoProvisionHandler.<ExecuteAsync>d__2.MoveNext() in C:\A\1\1\s\src\Messaging\Xamarin.Messaging.IDB.Local\Handlers\AutoProvisionHandler.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.Client.RequestHandler`2.<HandleAsync>d__5.MoveNext() in C:\A\1\230\s\src\Xamarin.Messaging.Client\Handlers\RequestHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.Client.MessageHandlerManager.<>c__DisplayClass16_1`2.<<RegisterHandlerAsync>b__2>d.MoveNext() in C:\A\1\230\s\src\Xamarin.Messaging.Client\MessageHandlerManager.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.Client.MessagingClient.<ReplyAsync>d__32`2.MoveNext() in C:\A\1\230\s\src\Xamarin.Messaging.Client\MessagingClient.cs:line 0
   --- End of inner exception stack trace ---
   at Xamarin.Messaging.Client.ApplicationMessageExtensions.<>c__DisplayClass10_0`1.<OfResponse>b__1(MqttApplicationMessage m) in C:\A\1\230\s\src\Xamarin.Messaging.Client\Extensions\ApplicationMessageExtensions.cs:line 194
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Xamarin.Messaging.Client.MessagingClient.<PostAsync>d__21`2.MoveNext() in C:\A\1\230\s\src\Xamarin.Messaging.Client\MessagingClient.cs:line 190
```

### Environment

```
Microsoft Visual Studio Community 2019
Version 16.9.5
VisualStudio.16.Release/16.9.5+31229.75
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Azure App Service Tools v3.0.0   16.9.693.2781
Azure App Service Tools v3.0.0

C# Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitHub.VisualStudio   2.11.106.19330
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   16.9.7 (df23ba6)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Visual Basic Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

WiX Toolset Visual Studio Extension   1.0.0.4
WiX Toolset Visual Studio Extension version 1.0.0.4
Copyright (c) .NET Foundation and contributors. All rights reserved.

Xamarin   16.9.000.292 (d16-9@26a958f)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.9.0.318 (remotes/origin/7b35adcdd1b204bbdcb279e0f029d151a20a4bf3@7b35adcdd)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.9.72 (426ebf6)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.2.2.1 (d16-9/877f572)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-9@54f8c24
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.34.1@daff8f4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@d210f11


Xamarin.iOS and Xamarin.Mac SDK   14.16.0.5 (ab40b131d)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

**Comment by Weishaupt** [comment]
+1.
I started with a fresh Xamarin Forms Project and tried to enable Automatic Provisioning

Things I've already tried to remediate the issue

1. I've updated my Build Host (Mac Mini 8,1) to the latest macOS Big Sur version (11.3.1)
2. I've updated Xcode to the latest version 12.5

A certificate is created in the Apple Developer Console, but non is available at `%localappdata%\Xamarin\iOS\Provisioning\Certificates`

```
Microsoft Visual Studio Enterprise 2019
Version 16.9.5
VisualStudio.16.Release/16.9.5+31229.75
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA483
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.9.693.2781
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2112521+5741df381174d72f08e3632bb99f52e8635b6a1a
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.9.693.2781
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.9.693.2781
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.9.693.2781
Azure Functions and Web Jobs Tools

C# Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40423.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.9.7 (df23ba6)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62103.10080
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.30201.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.9.000.292 (d16-9@26a958f)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.9.0.318 (remotes/origin/7b35adcdd1b204bbdcb279e0f029d151a20a4bf3@7b35adcdd)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.9.72 (426ebf6)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.2.2.1 (d16-9/877f572)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-9@54f8c24
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.34.1@daff8f4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@d210f11


Xamarin.iOS and Xamarin.Mac SDK   14.16.0.5 (ab40b131d)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

```
Xamarin.VisualStudio.Progress.ProgressReportService|Information|0|Creating certificate...
System.Net.Mqtt.Sdk.MqttClientImpl|Information|0|Client vs16372Marvi - An application message for topic xvs/idb/auto-provision-output was received
System.Net.Mqtt.Sdk.ClientPacketListener|Information|0|Client vs16372Marvi - Dispatching Publish message to flow PublishReceiverFlow and topic xvs/idb/auto-provision-output
Xamarin.VisualStudio.Progress.ProgressReportService|Information|0|There was an error while trying to automatically provision the project, please check the logs.
System.Net.Mqtt.Sdk.MqttClientImpl|Information|0|Client vs16372Marvi - An application message for topic xvs/idb/auto-provision-output was received
System.Net.Mqtt.Sdk.ClientPacketListener|Information|0|Client vs16372Marvi - Dispatching Publish message to flow PublishReceiverFlow and topic vs16372Marvi/error/xvs/idb/auto-provision
System.Net.Mqtt.Sdk.MqttClientImpl|Information|0|Client vs16372Marvi - An application message for topic vs16372Marvi/error/xvs/idb/auto-provision was received
Xamarin.Messaging.Client.MessagingClient|Error|0|An error occurred on the receiver while executing a post for topic xvs/idb/auto-provision and client vs16372Marvi
Xamarin.Messaging.Exceptions.MessagingRemoteException: An error occurred on client IDBLocal169000292 while executing a reply for topic xvs/idb/auto-provision ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Http.StringContent'.
   at System.Net.Http.HttpContent.CheckDisposed()
   at System.Net.Http.HttpContent.CopyToAsync(Stream stream, TransportContext context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.MacDev.AppleSigning.DeveloperPortalWebClient.<>c__DisplayClass25_0.<<Request>b__2>d.MoveNext() in /Users/builder/azdo/_work/1/s/External/maciostools/Xamarin.MacDev.AppleSigning/AppleDeveloperPortal/DeveloperPortalWebClient.cs:line 127
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.MacDev.AppleSigning.DeveloperPortalWebClient.<Request>d__25.MoveNext() in /Users/builder/azdo/_work/1/s/External/maciostools/Xamarin.MacDev.AppleSigning/AppleDeveloperPortal/DeveloperPortalWebClient.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.MacDev.AppleSigning.AuthorizedDeveloperPortalClient.<RequestAuthorized>d__7.MoveNext() in /Users/builder/azdo/_work/1/s/External/maciostools/Xamarin.MacDev.AppleSigning/AppleDeveloperPortal/AuthorizedDeveloperPortalClient.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.MacDev.AppleSigning.AuthorizedDeveloperPortalClient.<Request>d__4.MoveNext() in /Users/builder/azdo/_work/1/s/External/maciostools/Xamarin.MacDev.AppleSigning/AppleDeveloperPortal/AuthorizedDeveloperPortalClient.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.MacDev.AppleSigning.AppleDeveloperPortal.<CreateCertificate>d__24.MoveNext() in /Users/builder/azdo/_work/1/s/External/maciostools/Xamarin.MacDev.AppleSigning/AppleDeveloperPortal/AppleDeveloperPortal.cs:line 215
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.MacDev.AppleSigning.CreateCertificate.<Run>d__9.MoveNext() in /Users/builder/azdo/_work/1/s/External/maciostools/Xamarin.MacDev.AppleSigning/ProvisioningTasks/CreateCertificate.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.MacDev.AppleSigning.ResolveCertificate.<Run>d__13.MoveNext() in /Users/builder/azdo/_work/1/s/External/maciostools/Xamarin.MacDev.AppleSigning/ProvisioningTasks/ResolveCertificate.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.IDB.AppleProvisioningManager.<AutoProvisionAsync>d__20.MoveNext() in C:\A\1\1\s\src\Messaging\Xamarin.Messaging.IDB.Local\AppleProvisioningManager.cs:line 369
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.IDB.Local.AutoProvisionHandler.<ExecuteAsync>d__2.MoveNext() in C:\A\1\1\s\src\Messaging\Xamarin.Messaging.IDB.Local\Handlers\AutoProvisionHandler.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.Client.RequestHandler`2.<HandleAsync>d__5.MoveNext() in C:\A\1\230\s\src\Xamarin.Messaging.Client\Handlers\RequestHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.Client.MessageHandlerManager.<>c__DisplayClass16_1`2.<<RegisterHandlerAsync>b__2>d.MoveNext() in C:\A\1\230\s\src\Xamarin.Messaging.Client\MessageHandlerManager.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.Client.MessagingClient.<ReplyAsync>d__32`2.MoveNext() in C:\A\1\230\s\src\Xamarin.Messaging.Client\MessagingClient.cs:line 0
   --- End of inner exception stack trace ---
   at Xamarin.Messaging.Client.ApplicationMessageExtensions.<>c__DisplayClass10_0`1.<OfResponse>b__1(MqttApplicationMessage m) in C:\A\1\230\s\src\Xamarin.Messaging.Client\Extensions\ApplicationMessageExtensions.cs:line 194
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Xamarin.Messaging.Client.MessagingClient.<PostAsync>d__21`2.MoveNext() in C:\A\1\230\s\src\Xamarin.Messaging.Client\MessagingClient.cs:line 190
```

**Comment by Weishaupt** [comment]
Manually creating a development (or distribution) certificate fails, too.
![grafik](https://user-images.githubusercontent.com/2642714/118393652-76123900-b640-11eb-80f4-e8a0623cddac.png)

**Comment by ersmabinda** [comment]
With  VS2019 16.9.4 on Windows 10 I had an authentication failure. After updating to 16.9.5 the authentication succeeds but the automatic provisioning fails with the exception as described above.
This situation is really annoying. According to the release notes it is supposed to have been resolved.
Any work around?

**Comment by mauroa** [comment]
Hi, this issue has already been fixed for 16.9.6 and latest 16.10. Find the corresponding VS Feedback Item: https://developercommunity.visualstudio.com/t/Xamarin---iOS---Signing-Certs--Bundle-S/1424258

For future reference please use the VS Developer Community site to submit your feedback. 
Thanks
