### ISSUE TITLE
.NET/macOS: make it possible to skip assemblies referenced by the executable at startup

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#12341]
On macOS, this can happen:

```
$ ./vstool 
2021-08-04 11:10:31.875 vstool[80557:68737978] Xamarin.Mac: Invalid IDE Port: -1
2021-08-04 11:10:34.706 vstool[80557:68737970] Could not find `System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089` referenced by assembly `Microsoft.VisualStudio.Telemetry, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a`.
2021-08-04 11:10:34.709 vstool[80557:68737970] Could not find `System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089` referenced by assembly `MonoDevelop.Core, Version=2.6.0.0, Culture=neutral, PublicKeyToken=3ead7498f347467b`.
2021-08-04 11:10:34.709 vstool[80557:68737970] Could not find `System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089` referenced by assembly `vstool, Version=1.0.0.0, Culture=neutral, PublicKeyToken=3ead7498f347467b`.
2021-08-04 11:10:34.724 vstool[80557:68737970] Xamarin.Mac: Aborting due to trying to marshal managed exception:
Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
 (System.IO.FileNotFoundException)
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly) in System.Private.CoreLib.dll:token 0x6004cdb+0x8
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext) in System.Private.CoreLib.dll:token 0x6004cda+0x16
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef) in System.Private.CoreLib.dll:token 0x6004ad1+0xe
   at ObjCRuntime.Runtime.CollectReferencedAssemblies(List`1 assemblies, Assembly assembly) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 595
   at ObjCRuntime.Runtime.CollectReferencedAssemblies(List`1 assemblies, Assembly assembly) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 597
   at ObjCRuntime.Runtime.CollectReferencedAssemblies(List`1 assemblies, Assembly assembly) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 597
   at ObjCRuntime.Runtime.RegisterEntryAssembly(Assembly entry_assembly) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 566
   at ObjCRuntime.Runtime.RegisterEntryAssembly(IntPtr a) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 425
   at ObjCRuntime.Runtime.register_entry_assembly(IntPtr assembly, IntPtr& exception_gchandle) in /Users/builder/azdo/_work/1/s/xamarin-macios/runtime/Delegates.generated.cs:line 510
```

this is where it throws:

https://github.com/xamarin/xamarin-macios/blob/6dda8a97dc9b779734ef8b6c1af36fb2aeb94a33/src/ObjCRuntime/Runtime.cs#L614-L617

This is a mac-specific code path, and while seemingly it's possible to avoid the exception by setting `NSApplication.IgnoreMissingAssembliesDuringRegistration=true`, that won't work, because this exception occurs before any user code can execute.

We should make all our platforms behave the same way here (not throw).

Ref: [Teams link](https://teams.microsoft.com/l/message/19:1cd82f86048b449e937cdfb51403e194@thread.skype/1628064403467?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=0056f60b-301f-43ac-bbcf-f356d3c42c92&parentMessageId=1628064403467&teamName=VS%20Client%20Experiences&channelName=General&createdTime=1628064403467)

**Comment by filipnavara** [comment]
Related: https://github.com/dotnet/runtime/issues/35401#issuecomment-883374959
