### ISSUE TITLE
.Net 6 - System.DllNotFoundException: Could not find the runtime library libxammac.dylib

### ISSUE THREAD

**Issue by jwosty** [xamarin/xamarin-macios#12605]
### Steps to Reproduce

1. Clone (the dotnet6 branch of) this repo: https://github.com/fsprojects/Interstellar/tree/dotnet6\
2. ``dotnet tool restore && dotnet paket restore``
3. Open Interstellar.MacOS.sln in VSfM
4. Try to run Example.macOS.WebKit.fsproj

### Expected Behavior

App opens a window. Note that it works when you launch it with the CLI: ``dotnet run --project Examples/Example.macOS.WebKit/Example.macOS.WebKit.fsproj``

### Actual Behavior

App crashes with:

```
Unhandled Exception:
System.DllNotFoundException: Could not find the runtime library libxammac.dylib
   at ObjCRuntime.Runtime.LookupInternalFunction[initialize_func](String name) in Xamarin.Mac.dll:token 0x600174a+0x9e
   at ObjCRuntime.Runtime.EnsureInitialized() in Xamarin.Mac.dll:token 0x600174b+0x2a
   at AppKit.NSApplication.Init() in Xamarin.Mac.dll:token 0x600f0c7+0x12
   at Example.macOS.WebKit.main.main(String[] args) in /Users/jwostenberg/Code/FSharp/Interstellar/Examples/Examples.macOS.WebKit/Main.fs:line 9
[ERROR] FATAL UNHANDLED EXCEPTION: System.DllNotFoundException: Could not find the runtime library libxammac.dylib
   at ObjCRuntime.Runtime.LookupInternalFunction[initialize_func](String name) in Xamarin.Mac.dll:token 0x600174a+0x9e
   at ObjCRuntime.Runtime.EnsureInitialized() in Xamarin.Mac.dll:token 0x600174b+0x2a
   at AppKit.NSApplication.Init() in Xamarin.Mac.dll:token 0x600f0c7+0x12
   at Example.macOS.WebKit.main.main(String[] args) in /Users/jwostenberg/Code/FSharp/Interstellar/Examples/Examples.macOS.WebKit/Main.fs:line 9
```

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.8 (build 0)
Installation UUID: 290bbaa8-262e-4c8c-b800-82712d5961b9
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/6.0.100-preview.7.21379.14/Sdks
SDK Versions:
	6.0.100-preview.7.21379.14
	5.0.400
	3.1.412
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.0-preview.7.21377.19
	5.0.9
	3.1.18

=== .NET Core 3.1 SDK ===

SDK: 3.1.412

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.4 (17801)
Build 12D4e

=== Xamarin.Mac ===

Version: 7.14.0.24 (Visual Studio Community)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:00-0400

=== Xamarin.Android ===

Version: 11.3.0.4 (Visual Studio Community)
Commit: xamarin-android/d16-10/ae14caf
Android SDK: /Users/jwostenberg/Library/Android/sdk
	Supported Android versions:
		6.0 (API level 23)
		7.0 (API level 24)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.3
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/jwostenberg/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-08-12 20:43:52 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-08-12 20:44:10 UTC

=== Xamarin.iOS ===

Version: 14.20.0.24 (Visual Studio Community)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:01-0400

=== Xamarin Designer ===

Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== Build Information ===

Release ID: 810080000
Git revision: 0bc91c25997e4c374dc6eb96809c7bf52f6a7c33
Build date: 2021-08-18 14:50:30-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Tue Jun 22 19:49:55 PDT 2021
    root:xnu-6153.141.35~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

LiveXAML 1.3.51
Paket 0.6
Open With 0.2
XAML Styler 2.0.1
MvvmCross Template pack 2.1.0
```

### Build Logs

https://gist.github.com/jwosty/22c2b166bbe45fb7f56f61140d852781

### Example Project (If Possible)

https://github.com/fsprojects/Interstellar/tree/dotnet6/Examples/Examples.macOS.WebKit

**Comment by spouliot** [comment]
The fact that it works from the command-line means the SDK parts are fine. The problem is that the IDEs are not updated with each new net6 previews and a lot of, often incompatible, changes happens inside each releases. FWIW I'm surprised it built something without any errors.

Right now only the VS 2022 previews (on Windows) have support for the net6 previews projects.

IOW the current 8.x versions of VSfM does not support net6 projects. An upcoming (preview) version of VSfM will include support for net6 projects.
