### ISSUE TITLE
Compiling a .NET 6 binding project requires mono.framework

### ISSUE THREAD

**Issue by cwensley** [xamarin/xamarin-macios#12922]
### Steps to Reproduce

1. Install .NET 6 RC1
2. Install the `macos` workload `sudo dotnet workload install macos`
3. Ensure Mono.framework is _not_ installed
4. Create a .NET 6 binding project, something like:
  ```csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net6.0-macos</TargetFrameworks>
    <IsBindingProject>True</IsBindingProject>
  </PropertyGroup>
  <ItemGroup>
    <ObjcBindingApiDefinition Include="ApiDefinition.cs" />
    <ObjcBindingCoreSource Include="StructsAndEnums.cs" />
  </ItemGroup>
</Project>
  ```
5. Compile `dotnet build`

### Expected Behavior

Project compiles successfully.

### Actual Behavior

Crashes with the following error:

```
curtis@Curtis-Mac TestNet6BindingProject % dotnet build
Microsoft (R) Build Engine version 17.0.0-preview-21460-01+8f208e609 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
BTOUCH : error BI0000: Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new [/Users/curtis/Projects/test/TestNet6BindingProject/TestNet6BindingProject.csproj]
  System.ComponentModel.Win32Exception (2): No such file or directory
     at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
     at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
     at System.Diagnostics.Process.Start()
     at Xamarin.Utils.Execution.<>c__DisplayClass24_1.<RunAsync>b__0() in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/common/Execution.cs:line 103
     at System.Environment.get_StackTrace()
     at ErrorHelper.ShowInternal(Exception e) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/error.cs:line 175
     at ErrorHelper.Show(Exception e, Boolean rethrow_errors) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/error.cs:line 125
     at BindingTouch.Main(String[] args) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/btouch.cs:line 91

Build FAILED.
```

Installing mono makes the project compile, but this should not be necessary.  It appears that btouch is trying to execute csc from mono.framework instead of using the dotnet compiler.

### Environment

.NET 6 RC1 on macOS 11.6.  VS for Mac is not installed.

### Build Logs

[diagnostic-build-output.txt](https://github.com/xamarin/xamarin-macios/files/7279740/diagnostic-build-output.txt)

### Example Project (If Possible)

[TestNet6BindingProject.zip](https://github.com/xamarin/xamarin-macios/files/7279746/TestNet6BindingProject.zip)

**Comment by rolfbjarne** [comment]
Thanks for the report, we'll look into fixing this.
