### ISSUE TITLE
ACTool fails to copy file - Access Denied

### ISSUE THREAD

**Issue by KirillOsenkov** [xamarin/xamarin-macios#13473]
On my local machine ACTool started failing with access denied:

```
        /usr/local/share/dotnet/packs/Microsoft.macOS.Sdk/12.0.101-preview.10.249/tools/msbuild/macOS/Xamarin.Shared.targets(748,3): error MSB4018: The "ACTool" task failed unexpectedly.
System.UnauthorizedAccessException: Access to the path is denied.
 ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at Xamarin.MacDev.Tasks.ACToolTaskBase.Execute() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ACToolTaskBase.cs:line 275
   at Xamarin.MacDev.Tasks.ACTool.Execute() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/ACTool.cs:line 13
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/Users/kirill/vsmac2/main/src/core/VisualStudio/VisualStudio.csproj]
```

The File.Copy operation that is failing is here: 
https://github.com/xamarin/xamarin-macios/blob/78f52e2fc238ba731bf993d6d2b6d4b142ab8a48/msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ACToolTaskBase.cs#L275

I'm guessing there should be a try/catch around that File.Copy that would log the source and destination file paths before throwing. Right now it's hard to understand which file is being copied where and why it's failing.

**Comment by KirillOsenkov** [comment]
I have found out that the file couldn't be copied because Defender for Mac has attached extended attributes to the file:

```
could not copy extended attributes to ....: Operation not permitted
```

I will follow up with the Defender team, but we should still log a better message if the File.Copy operation fails (to determine what was the source and what was the destination for the Copy operation that failed).

**Comment by nosami** [comment]
Wow... thanks for filing this @KirillOsenkov - I just hit this as well

**Comment by yevgeniy-seleznev** [comment]
+1, having the same problem. Applying the above exclusion trick in Defender did not resolve the issue

**Comment by KirillOsenkov** [comment]
@yevgeniy-seleznev the Defender team has fixed the bug and will be rolling out the fix shortly.

For now, as a workaround, if a file can't be copied, run this script on a directory that contains the files:
```
find . -xattrname com.microsoft.defender.dlp.marker#C | xargs sudo xattr -d com.microsoft.defender.dlp.marker#C
```

The problem is that Defender erroneously adds an external attribute to some random files, which a regular user doesn't have permissions to read. So attempts to copy the file not under sudo result in Access denied since the copy process also wants to copy the extended attributes but it doesn't have read access.

You can also temporarily uninstall the DLP component of Defender until a fix is available:
```
sudo /Library/Application\ Support/Microsoft/DLP/scripts/uninstall
```

**Comment by yevgeniy-seleznev** [comment]
> @yevgeniy-seleznev the Defender team has fixed the bug and will be rolling out the fix shortly.
> 
> For now, as a workaround, if a file can't be copied, run this script on a directory that contains the files:
> 
> ```
> find . -xattrname com.microsoft.defender.dlp.marker#C | xargs sudo xattr -d com.microsoft.defender.dlp.marker#C
> ```
> 
> The problem is that Defender erroneously adds an external attribute to some random files, which a regular user doesn't have permissions to read. So attempts to copy the file not under sudo result in Access denied since the copy process also wants to copy the extended attributes but it doesn't have read access.
> 
> You can also temporarily uninstall the DLP component of Defender until a fix is available:
> 
> ```
> sudo /Library/Application\ Support/Microsoft/DLP/scripts/uninstall
> ```

Thank you -- removing the attributes using the first part of your suggestion, on the source folder, did the trick!
