### ISSUE TITLE
Xamarin.iOS is missing TypeForwardedToAttribute for System.nfloat

### ISSUE THREAD

**Issue by lauxjpn** [xamarin/xamarin-macios#13642]
When using existing libraries build before .NET 6 in a .NET 6 targeted project, the project compiles and runs fine for Xamarin.Android.

This is not the case for Xamarin.iOS, because of `System.nfloat` that is expected by those older libraries to exist in `Xamarin.iOS` but has been moved.

Is there a specific reason why the type was not redirected using the `TypeForwardedToAttribute` or is this just an oversight?

<details>
<summary>Fata exception log output before crash</summary>

```
2021-12-30 06:06:49.762304+0100 MyApp.iOS[3258:59136] Could not register the assembly 'Xamarin.Forms.Platform.iOS': System.TypeLoadException: Could not resolve type with token 0100005d from typeref (expected class 'System.nfloat' in assembly 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065')
   at System.Reflection.MonoMethodInfo.GetMethodInfo(IntPtr handle)
   at System.Reflection.RuntimeMethodInfo.GetPseudoCustomAttributes()
   at System.Reflection.CustomAttribute.GetPseudoCustomAttributes(ICustomAttributeProvider obj, Type attributeType)
   at System.Reflection.CustomAttribute.GetCustomAttributesBase(ICustomAttributeProvider obj, Type attributeType, Boolean inheritedOnly)
   at System.Reflection.CustomAttribute.GetCustomAttributes(ICustomAttributeProvider obj, Type attributeType, Boolean inherit)
   at System.Reflection.RuntimeMethodInfo.GetCustomAttributes(Type attributeType, Boolean inherit)
   at Registrar.SharedDynamic.GetOneAttribute[ExportAttribute](ICustomAttributeProvider provider)
   at Registrar.DynamicRegistrar.GetExportAttribute(MethodBase method)
   at Registrar.Registrar.RegisterTypeUnsafe(Type type, List`1& exceptions)
   at Registrar.Registrar.RegisterAssembly(Assembly assembly)
```

</details>

(I worked around the issue in this case here by recompiling the corresponding Xamarin.Forms projects against `.net6.0-ios`, but this should not have been necessary.)

**Comment by Perksey** [comment]
Existing Xamarin.iOS projects are not compatible with .NET 6 iOS. Please see #13087.

**Comment by chamons** [comment]
@Perksey 's link is correct. iOS projects are not compatible with NET6 without a recompile. 

I believe there was some conflict that made TypeForwardedToAttribute difficult or impossible to use here, but do not know the details. @rolfbjarne might be able to drop by and provide context.

Due to this nfloat/nint/nunit and other issues we decided to make the NET6 transition a full API break and fix a large number of issues that were impossible to resolve in an API compatible way.

**Comment by rolfbjarne** [comment]
> I believe there was some conflict that made TypeForwardedToAttribute difficult or impossible to use here, but do not know the details. @rolfbjarne might be able to drop by and provide context.

TypeForwardedToAttribute can only be used to move a type to another assembly (you add the TypeForwardedToAttribute to the original assembly, and it points to the type in the new namespace).

It can't be used to move a type to a different namespace (like we did for `System.nfloat` -> `ObjCRuntime.nfloat`).
