### ISSUE TITLE
Mac: Drag/drop fails with "Cannot create an instance of AppKit.NSDraggingInfo because it is an abstract class"

### ISSUE THREAD

**Issue by sandyarmstrong** [xamarin/xamarin-macios#14170]
Using a frankenbuild where I installed 12.1.301-preview.13.4 and then copied relevant files from https://github.com/xamarin/xamarin-macios/pull/14148 over the installed workload.

We have a class that implements/inherits `INSDraggingSource` and `INSDraggingDestination`, with a method `public override NSDragOperation DraggingEntered(NSDraggingInfo sender)`.

It seems like whenever a drag occurs, the following error shows up in our logs:

```
ERROR [2022-02-16 09:36:19Z]: Marshaled Managed Exception
ObjCRuntime.RuntimeException: Unable to marshal the parameter #1 whose managed type is 'AppKit.NSDraggingInfo' to managed.
Additional information:
	Selector: draggingEntered:
	Method: AppKit.NSDragOperation VisualStudioMac.UI.TabStrip.TabStripDragContainer.DraggingEntered (AppKit.NSDraggingInfo)

 ---> System.MemberAccessException: Cannot create an instance of AppKit.NSDraggingInfo because it is an abstract class.
   at System.Reflection.RuntimeConstructorInfo.CheckCanCreateInstance(Type declaringType, Boolean isVarArg)
   at System.Reflection.RuntimeConstructorInfo.ThrowNoInvokeException()
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at ObjCRuntime.Runtime.ConstructNSObject[T](IntPtr ptr, Type type, MissingCtorResolution missingCtorResolution) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 1201
   at ObjCRuntime.Runtime.GetNSObject(IntPtr ptr, Type target_type, MissingCtorResolution missingCtorResolution, Boolean evenInFinalizerQueue, Boolean& created) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 1457
   at ObjCRuntime.Runtime.GetNSObjectWithType(IntPtr ptr, IntPtr type_ptr, Boolean& created) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 781
   at ObjCRuntime.Runtime.get_nsobject_with_type(IntPtr obj, IntPtr type, Boolean& created, IntPtr& exception_gchandle) in /Users/builder/azdo/_work/1/s/xamarin-macios/runtime/Delegates.generated.cs:line 676
   --- End of inner exception stack trace ---
2022-02-16 09:36:19.495 VisualStudio[70504:2784465] *** Canceling drag because exception 'ObjCRuntime.RuntimeException' (reason 'Unable to marshal the parameter #1 whose managed type is 'AppKit.NSDraggingInfo' to managed.
Additional information:
	Selector: draggingEntered:
	Method: AppKit.NSDragOperation VisualStudioMac.UI.TabStrip.TabStripDragContainer.DraggingEntered (AppKit.NSDraggingInfo)
') was raised during a dragging session
```

**Comment by sandyarmstrong** [comment]
I understand this was fixed in P14 via https://github.com/xamarin/xamarin-macios/pull/13987.

I'm working around this in P13 by using manual exports instead of overriding from base classes.
