### ISSUE TITLE
xib files broken for .NET 6 IOS

### ISSUE THREAD

**Issue by jona-1993** [xamarin/xamarin-macios#14226]
### Steps to Reproduce

1. Create a .NET 6 IOS project.
2. Add view controller (+ xib file). I named that "test"
3. Create a button with Xcode, I named this button "Testbt"
4. Call own xib file with : NSBundle.MainBundle.LoadNib ("test", this, null);
5. run app and crash

### Expected Behavior
no crash

### Actual Behavior
crash when NSBundle.MainBundle.LoadNib ("test", this, null); is called

### Environment

```
Visual Studio Community 2022 for Mac Preview
Version 17.0 Preview (17.0 build 7303)
Installation UUID: a33e7e16-5f94-4216-a222-fd4ec85e0b7c

Runtime
.NET 6.0.2-servicing.1.22101.5 (64-bit)
Architecture: X64

Roslyn (Language Service)
4.1.0-3.22062.11+cc0d213b15fdda217ad888d269d19754fa556eb4

NuGet
Version: 6.0.0.262

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/6.0.200/Sdks
SDK Versions:
	6.0.200
	6.0.102
	6.0.101
	6.0.100
	6.0.100-rc.1.21463.6
	6.0.100-preview.7.21379.14
	5.0.405
	5.0.404
	5.0.403
	5.0.402
	5.0.401
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	5.0.100-rc.2.20479.15
	5.0.100-preview.5.20279.10
	3.1.416
	3.1.415
	3.1.414
	3.1.413
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.300
	3.1.200
	3.1.102
	3.1.100
	3.1.100-preview3-014645
	3.1.100-preview2-014569
	3.0.100
	2.1.810
MSBuild SDKs: /usr/local/share/dotnet/sdk/6.0.200/Sdks

.NET Core Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.2
	6.0.1
	6.0.0
	6.0.0-rc.1.21451.13
	5.0.14
	5.0.13
	5.0.12
	5.0.11
	5.0.10
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	5.0.0-rc.2.20475.5
	5.0.0-preview.5.20278.1
	3.1.22
	3.1.21
	3.1.20
	3.1.19
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.4
	3.1.2
	3.1.0
	3.1.0-preview3.19553.2
	3.1.0-preview2.19525.6
	3.0.0
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.14
	2.1.13

Xamarin.Profiler
Version: 1.7.0.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin Designer
Version: 17.1.5.7
Hash: d6a336055
Branch: remotes/origin/d17-0-vsmac
Build date: 2022-02-14 19:26:49 UTC

Apple Developer Tools
Xcode 13.2.1 (19586)
Build 13C100

Xamarin.Mac
Version: 8.6.0.3 (Visual Studio Community)
Hash: caa899d24
Branch: d17-1
Build date: 2022-01-16 21:16:56-0500

Xamarin.iOS
Version: 15.6.0.3 (Visual Studio Community)
Hash: caa899d24
Branch: d17-1
Build date: 2022-01-16 21:16:56-0500

Xamarin.Android
Version: 12.2.99.75 (Visual Studio Community)
Commit: xamarin-android/main/398afd4
Android SDK: /Users/jona1993/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)
		11.0 (API level 30)
		9.0  (API level 28)

SDK Command-line Tools Version: 5.0
SDK Platform Tools Version: 31.0.3
SDK Build Tools Version: 31.0.0

Build Information: 
Mono: a5d1934
Java.Interop: xamarin/java.interop/main@32635fd6
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.37.2@51b4821
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@0e80ea1

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.2.0.19
Hash: 95c3497
Branch: remotes/origin/new/vsm-net6
Build date: 2022-02-14 19:26:54 UTC

Android Device Manager
Version: 0.0.0.1092
Hash: a6f517e
Branch: remotes/origin/new/vsm-net6
Build date: 2022-02-14 19:26:54 UTC

Build Information
Release ID: 1700007303
Git revision: cd68696da194e10e3f7d6fddb2733dc33e52ca90
Build date: 2022-02-14 19:22:58+00
Build branch: release-17.0
Build lane: release-17.0

Operating System
Mac OS X 12.1.0
Darwin 21.2.0 Darwin Kernel Version 21.2.0
    Sun Nov 28 20:28:54 PST 2021
    root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64


```

### Build Logs

[build-log.log](https://github.com/xamarin/xamarin-macios/files/8122565/build-log.log)

### Crash log 

```
Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSUnknownKeyException Reason: [<AppDelegate 0x600000d502c0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key Testbt.
Native stack trace:
	0   CoreFoundation                      0x00007fff203feba4 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff201a1be7 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff203fe845 -[NSException init] + 0
	3   Foundation                          0x00007fff20796332 -[NSObject(NSKeyValueCoding) setValue:forKey:] + 315
	4   UIKitCore                           0x00007fff24c1c820 -[UIRuntimeOutletConnection connect] + 109
	5   CoreFoundation                      0x00007fff203e92cd -[NSArray makeObjectsPerformSelector:] + 228
	6   UIKitCore                           0x00007fff24c125bc -[UINib instantiateWithOwner:options:] + 2185
	7   UIKitCore                           0x00007fff24c12eb6 -[NSBundle(UINSBundleAdditions) loadNibNamed:owner:options:] + 144
	8   libxamarin-dotnet-debug.dylib       0x000000010eca1679 xamarin_dyn_objc_msgSend + 217
	9   ???                                 0x0000000113c282da 0x0 + 4626481882

   at ObjCRuntime.Runtime.ThrowNSException(IntPtr ns_exception)
   at ObjCRuntime.Runtime.throw_ns_exception(IntPtr exc)
   at Foundation.NSBundle.LoadNib(String nibName, NSObject owner, NSDictionary options)
   at HelloiOS.AppDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions) in /Users/jona1993/Desktop/net6-mobiles-samples-fresh/HelloiOS/AppDelegate.cs:line 21
--- End of stack trace from previous location ---
   at Foundation.NSBundle.LoadNib(String nibName, NSObject owner, NSDictionary options)
   at HelloiOS.AppDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions) in /Users/jona1993/Desktop/net6-mobiles-samples-fresh/HelloiOS/AppDelegate.cs:line 21
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at HelloiOS.Application.Main(String[] args) in /Users/jona1993/Desktop/net6-mobiles-samples-fresh/HelloiOS/Main.cs:line 12	0   CoreFoundation                      0x00007fff203feba4 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff201a1be7 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff203fe845 -[NSException init] + 0
	3   Foundation                          0x00007fff20796332 -[NSObject(NSKeyValueCoding) setValue:forKey:] + 315
	4   UIKitCore                           0x00007fff24c1c820 -[UIRuntimeOutletConnection connect] + 109
	5   CoreFoundation                      0x00007fff203e92cd -[NSArray makeObjectsPerformSelector:] + 228
	6   UIKitCore                           0x00007fff24c125bc -[UINib instantiateWithOwner:options:] + 2185
	7   UIKitCore                           0x00007fff24c12eb6 -[NSBundle(UINSBundleAdditions) loadNibNamed:owner:options:] + 144
	8   libxamarin-dotnet-debug.dylib       0x000000010eca1679 xamarin_dyn_objc_msgSend + 217
	9   ???                                 0x0000000113c282da 0x0 + 4626481882
```

### Example Project 
[HelloiOS.zip](https://github.com/xamarin/xamarin-macios/files/8122542/HelloiOS.zip)

**Comment by chamons** [comment]
I currently do not believe this is "broken for .NET 6 iOS" as I created a legacy Xamarin project, repeated your steps and see the same exception.

Here is my project showing this.

[xibtest.zip](https://github.com/xamarin/xamarin-macios/files/8375241/xibtest.zip)

I did not dig into your xib to see what specifically you did wrong. This article may be helpful - https://becodable.com/this-class-is-not-key-value-coding-compliant-for-the-key/

I'm going to close this issue, as the stated reason "this xib is broken for .NET 6" appears to be "I can't get this xib to work in general, which isn't yet a bug.

Please feel free to open a new issue after digging into it more if you believe there is an actual bug in the SDK.
