### ISSUE TITLE
Pair to Mac fails iOS workload install since 6.0.300-preview.22154.4

### ISSUE THREAD

**Issue by shugaoye** [xamarin/xamarin-macios#14476]
### Steps to Reproduce
Please refer to this issue
https://github.com/xamarin/xamarin-macios/issues/13611
I have exactly the same issue in .NET 6.0.300-preview.22154.4 (.NET MAUI preview 14)

### Actual Behavior
When I tried to pair with Mac, I got the following error message:
```
Error: Could not install workload manifest for 'ios'
```
### Environment
```
Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.2.0 Preview 2.1
```

### Log

`%LOCALAPPDATA%\Xamarin\Logs\17.0\2022-03-23_16-54-47.23400.Ide.log`

```
    DateTime=2022-03-23T08:55:41.3433375Z: 03/23/2022 08:55:41Z
Xamarin.Messaging.Integration.State.ServerStateContext Information: 0 : Default NuGet sources: https://api.nuget.org/v3/index.json: 03/23/2022 08:55:41Z
    DateTime=2022-03-23T08:55:41.3503409Z: 03/23/2022 08:55:41Z
Xamarin.Messaging.Integration.State.ServerStateContext Information: 0 : !Default NuGet sources: https://api.nuget.org/v3/index.json: 03/23/2022 08:55:41Z
    DateTime=2022-03-23T08:55:41.3503409Z: 03/23/2022 08:55:41Z
Xamarin.Messaging.Client.MessagingClient Error: 0 : An error occurred on the receiver while executing a post for topic xvs/idb/initialize-dotnet-workload and client vs23400Roger
Xamarin.Messaging.Exceptions.MessagingRemoteException: An error occurred on client IDB while executing a reply for topic xvs/idb/initialize-dotnet-workload ---> System.ApplicationException: Could not install workload manifest for 'ios'. Details: The manifest package for 'ios' could not be found in any of the expected NuGet sources
 ---> System.ApplicationException: The manifest package for 'ios' could not be found in any of the expected NuGet sources
  at Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManager.GetWorkloadManifestPackageIdAsync (System.String sdkBand, System.String identifier, Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManifestType manifestType, NuGet.Versioning.NuGetVersion nugetVersion, System.Collections.Generic.IEnumerable`1[T] nugetSources) [0x0011f] in <74ede3b7f4a94a7ea5ffd906a433ab9a>:0 
  at Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManager.GetWorkloadManifestPackageIdAsync (System.String sdkBand, System.String identifier, Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManifestType manifestType, NuGet.Versioning.NuGetVersion nugetVersion, System.Collections.Generic.IEnumerable`1[T] nugetSources) [0x001ee] in <74ede3b7f4a94a7ea5ffd906a433ab9a>:0 
  at Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManager.GetWorkloadManifestPackageIdAsync (System.String sdkBand, System.String identifier, Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManifestType manifestType, NuGet.Versioning.NuGetVersion nugetVersion, System.Collections.Generic.IEnumerable`1[T] nugetSources) [0x001ee] in <74ede3b7f4a94a7ea5ffd906a433ab9a>:0 
  at Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManager.GetWorkloadManifestPackageIdAsync (System.String sdkBand, System.String identifier, Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManifestType manifestType, NuGet.Versioning.NuGetVersion nugetVersion, System.Collections.Generic.IEnumerable`1[T] nugetSources) [0x001ee] in <74ede3b7f4a94a7ea5ffd906a433ab9a>:0 
  at Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManager.GetWorkloadManifestPackageIdAsync (System.String identifier, Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManifestType manifestType, NuGet.Versioning.NuGetVersion nugetVersion, System.Collections.Generic.IEnumerable`1[T] nugetSources) [0x000fc] in <74ede3b7f4a94a7ea5ffd906a433ab9a>:0 
  at Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManager.InstallWorkloadManifestAsync (System.String identifier, System.String workloadVersion, Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManifestType manifestType, System.Collections.Generic.IEnumerable`1[T] nugetSources) [0x000cd] in <74ede3b7f4a94a7ea5ffd906a433ab9a>:0 
   --- End of inner exception stack trace ---
  at Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManager.InstallWorkloadManifestAsync (System.String identifier, System.String workloadVersion, Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManifestType manifestType, System.Collections.Generic.IEnumerable`1[T] nugetSources) [0x00222] in <74ede3b7f4a94a7ea5ffd906a433ab9a>:0 
  at Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManager.InstallWorkloadAsync (System.String workloadIdentifier, System.String workloadVersion, System.String platformIdentifier, System.Collections.Generic.IEnumerable`1[T] workloadDependencies, System.Collections.Generic.IEnumerable`1[T] nugetSources) [0x001a0] in <74ede3b7f4a94a7ea5ffd906a433ab9a>:0 
  at Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManager.InstallWorkloadAsync (System.String workloadIdentifier, System.String workloadVersion, System.String platformIdentifier, System.Collections.Generic.IEnumerable`1[T] workloadDependencies, System.Collections.Generic.IEnumerable`1[T] nugetSources) [0x002d2] in <74ede3b7f4a94a7ea5ffd906a433ab9a>:0 
  at Xamarin.Messaging.IDB.InitializeDotNetWorkloadMessageHandler.ExecuteAsync (Xamarin.Messaging.IDB.Contracts.InitializeDotNetWorkloadMessage message) [0x00408] in <74ede3b7f4a94a7ea5ffd906a433ab9a>:0 
  at Xamarin.Messaging.Client.RequestHandler`2[TMessage,TResult].HandleAsync (TMessage message) [0x0010e] in <a7b86a82e33f4a078bfaf64dd6221e5b>:0 
  at Xamarin.Messaging.Client.MessageHandlerManager+<>c__DisplayClass16_1`2[TMessage,TResult].<RegisterHandlerAsync>b__2 () [0x00084] in <a7b86a82e33f4a078bfaf64dd6221e5b>:0 
  at Xamarin.Messaging.Client.MessagingClient.ReplyAsync[TRequest,TResponse] (Xamarin.Messaging.Client.IRequest`1[T] request, Xamarin.Messaging.MessagePriority priority, System.Func`1[TResult] replyFunctionAsync) [0x000c5] in <a7b86a82e33f4a078bfaf64dd6221e5b>:0 
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Xamarin.Messaging.Client.ApplicationMessageExtensions.<>c__DisplayClass10_0`1.<OfResponse>b__1(MqttApplicationMessage m) in D:\a\_work\1\s\src\Xamarin.Messaging.Client\Extensions\ApplicationMessageExtensions.cs:line 194
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Xamarin.Messaging.Client.MessagingClient.<PostAsync>d__21`2.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Client\MessagingClient.cs:line 190: 03/23/2022 08:55:43Z
    DateTime=2022-03-23T08:55:43.2728724Z: 03/23/2022 08:55:43Z
Xamarin.Messaging.Integration.State.ServerStateContext Information: 0 : Performing server validations against '127.0.0.1'...: 03/23/2022 08:55:43Z
    DateTime=2022-03-23T08:55:43.2798685Z: 03/23/2022 08:55:43Z
Xamarin.Messaging.Integration.State.ServerStateContext Information: 0 : !Performing server validations against '127.0.0.1'...: 03/23/2022 08:55:43Z
    DateTime=2022-03-23T08:55:43.2798685Z: 03/23/2022 08:55:43Z
Xamarin.Messaging.Integration.State.ServerStateContext Information: 0 : Server State transition from ValidatingState to DisconnectingState on 127.0.0.1 (127.0.0.1): 03/23/2022 08:55:43Z
    DateTime=2022-03-23T08:55:43.3458937Z: 03/23/2022 08:55:43Z
Xamarin.Messaging.Integration.State.ServerStateContext Information: 0 : Starting disconnection from 127.0.0.1...: 03/23/2022 08:55:43Z
    DateTime=2022-03-23T08:55:43.3640421Z: 03/23/2022 08:55:43Z
Xamarin.Messaging.Integration.State.ServerStateContext Information: 0 : !Starting disconnection from 127.0.0.1...: 03/23/2022 08:55:43Z
    DateTime=2022-03-23T08:55:43.3650165Z: 03/23/2022 08:55:43Z
System.Net.Mqtt.Sdk.Bindings.TcpChannel Warning: 0 : The underlying communication stream has completed sending bytes. The observable sequence will be completed and the channel will be disposed: 03/23/2022 08:55:43Z
    DateTime=2022-03-23T08:55:43.4470150Z: 03/23/2022 08:55:43Z
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client vs23400Roger - Packet Channel observable sequence has been completed: 03/23/2022 08:55:43Z
    DateTime=2022-03-23T08:55:43.4490356Z: 03/23/2022 08:55:43Z
Xamarin.Messaging.Integration.State.ServerStateContext Information: 0 : Server State transition from DisconnectingState to DisconnectedState on 127.0.0.1 (127.0.0.1): 03/23/2022 08:55:43Z
    DateTime=2022-03-23T08:55:43.4870367Z: 03/23/2022 08:55:43Z
Xamarin.Messaging.Ssh.MessagingService Information: 0 : The underlying client has been closed: 03/23/2022 08:55:43Z
    DateTime=2022-03-23T08:55:43.4920363Z: 03/23/2022 08:55:43Z
Xamarin.Messaging.Integration.State.ServerStateContext Information: 0 : Starting disconnection from 127.0.0.1...: 03/23/2022 08:55:43Z
    DateTime=2022-03-23T08:55:43.5220153Z: 03/23/2022 08:55:43Z
Xamarin.Messaging.Integration.State.ServerStateContext Information: 0 : !Starting disconnection from 127.0.0.1...: 03/23/2022 08:55:43Z
    DateTime=2022-03-23T08:55:43.5220153Z: 03/23/2022 08:55:43Z
Xamarin.Messaging.Integration.State.ServerStateContext Information: 0 : The connection to '127.0.0.1' has been finished: 03/23/2022 08:55:43Z
    DateTime=2022-03-23T08:55:43.5370156Z: 03/23/2022 08:55:43Z
Xamarin.Messaging.Integration.State.ServerStateContext Information: 0 : !The connection to '127.0.0.1' has been finished: 03/23/2022 08:55:43Z
    DateTime=2022-03-23T08:55:43.5370156Z: 03/23/2022 08:55:43Z
Xamarin.Messaging.Integration.State.ServerStateContext Error: 0 : Could not install workload manifest for 'ios'. Details: The manifest package for 'ios' could not be found in any of the expected NuGet sources

System.ApplicationException: Could not install workload manifest for 'ios'. Details: The manifest package for 'ios' could not be found in any of the expected NuGet sources
 ---> System.ApplicationException: The manifest package for 'ios' could not be found in any of the expected NuGet sources
  at Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManager.GetWorkloadManifestPackageIdAsync (System.String sdkBand, System.String identifier, Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManifestType manifestType, NuGet.Versioning.NuGetVersion nugetVersion, System.Collections.Generic.IEnumerable`1[T] nugetSources) [0x0011f] in <74ede3b7f4a94a7ea5ffd906a433ab9a>:0 
  at Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManager.GetWorkloadManifestPackageIdAsync (System.String sdkBand, System.String identifier, Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManifestType manifestType, NuGet.Versioning.NuGetVersion nugetVersion, System.Collections.Generic.IEnumerable`1[T] nugetSources) [0x001ee] in <74ede3b7f4a94a7ea5ffd906a433ab9a>:0 
  at Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManager.GetWorkloadManifestPackageIdAsync (System.String sdkBand, System.String identifier, Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManifestType manifestType, NuGet.Versioning.NuGetVersion nugetVersion, System.Collections.Generic.IEnumerable`1[T] nugetSources) [0x001ee] in <74ede3b7f4a94a7ea5ffd906a433ab9a>:0 
  at Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManager.GetWorkloadManifestPackageIdAsync (System.String sdkBand, System.String identifier, Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManifestType manifestType, NuGet.Versioning.NuGetVersion nugetVersion, System.Collections.Generic.IEnumerable`1[T] nugetSources) [0x001ee] in <74ede3b7f4a94a7ea5ffd906a433ab9a>:0 
  at Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManager.GetWorkloadManifestPackageIdAsync (System.String identifier, Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManifestType manifestType, NuGet.Versioning.NuGetVersion nugetVersion, System.Collections.Generic.IEnumerable`1[T] nugetSources) [0x000fc] in <74ede3b7f4a94a7ea5ffd906a433ab9a>:0 
  at Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManager.InstallWorkloadManifestAsync (System.String identifier, System.String workloadVersion, Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManifestType manifestType, System.Collections.Generic.IEnumerable`1[T] nugetSources) [0x000cd] in <74ede3b7f4a94a7ea5ffd906a433ab9a>:0 
   --- End of inner exception stack trace ---
  at Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManager.InstallWorkloadManifestAsync (System.String identifier, System.String workloadVersion, Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManifestType manifestType, System.Collections.Generic.IEnumerable`1[T] nugetSources) [0x00222] in <74ede3b7f4a94a7ea5ffd906a433ab9a>:0 
  at Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManager.InstallWorkloadAsync (System.String workloadIdentifier, System.String workloadVersion, System.String platformIdentifier, System.Collections.Generic.IEnumerable`1[T] workloadDependencies, System.Collections.Generic.IEnumerable`1[T] nugetSources) [0x001a0] in <74ede3b7f4a94a7ea5ffd906a433ab9a>:0 
  at Xamarin.Messaging.IDB.DotNetSdk.DotNetWorkloadManager.InstallWorkloadAsync (System.String workloadIdentifier, System.String workloadVersion, System.String platformIdentifier, System.Collections.Generic.IEnumerable`1[T] workloadDependencies, System.Collections.Generic.IEnumerable`1[T] nugetSources) [0x002d2] in <74ede3b7f4a94a7ea5ffd906a433ab9a>:0 
  at Xamarin.Messaging.IDB.InitializeDotNetWorkloadMessageHandler.ExecuteAsync (Xamarin.Messaging.IDB.Contracts.InitializeDotNetWorkloadMessage message) [0x00408] in <74ede3b7f4a94a7ea5ffd906a433ab9a>:0 
  at Xamarin.Messaging.Client.RequestHandler`2[TMessage,TResult].HandleAsync (TMessage message) [0x0010e] in <a7b86a82e33f4a078bfaf64dd6221e5b>:0 
  at Xamarin.Messaging.Client.MessageHandlerManager+<>c__DisplayClass16_1`2[TMessage,TResult].<RegisterHandlerAsync>b__2 () [0x00084] in <a7b86a82e33f4a078bfaf64dd6221e5b>:0 
  at Xamarin.Messaging.Client.MessagingClient.ReplyAsync[TRequest,TResponse] (Xamarin.Messaging.Client.IRequest`1[T] request, Xamarin.Messaging.MessagePriority priority, System.Func`1[TResult] replyFunctionAsync) [0x000c5] in <a7b86a82e33f4a078bfaf64dd6221e5b>:0 : 03/23/2022 08:55:43Z
    DateTime=2022-03-23T08:55:43.5730158Z: 03/23/2022 08:55:43Z
Xamarin.Messaging.Integration.State.ServerStateContext Error: 0 : !Could not install workload manifest for 'ios'. Details: The manifest package for 'ios' could not be found in any of the expected NuGet sources
: 03/23/2022 08:55:43Z
    DateTime=2022-03-23T08:55:43.5730158Z: 03/23/2022 08:55:43Z
Xamarin.Messaging.Client.PingHandler Information: 0 : vs23400Roger received ping. Sending acknowledge...: 03/23/2022 08:55:46Z
    DateTime=2022-03-23T08:55:46.3488355Z: 03/23/2022 08:55:46Z

```

**Comment by dalexsoto** [comment]
Please try again, this should be resolved now. https://www.nuget.org/packages/Microsoft.NET.Sdk.iOS.Manifest-6.0.200/15.2.302-preview.14.122

**Comment by shugaoye** [comment]
Thanks! It looks good now.
