### ISSUE TITLE
iOS Signing Fails due to Error in Generating Automatic Provisioning Profile or Certificate Retrieval

### ISSUE THREAD

**Issue by GeorgDangl** [xamarin/xamarin-macios#15061]
### Steps to Reproduce

1. Create a new iOS project in Visual Studio 2022
2. Open project properties and select a team for automatic provisioning

### Expected Behavior

Developer certificates and provisioning profiles are loaded or created.

### Actual Behavior

An error is shown:
![image](https://user-images.githubusercontent.com/10274404/169274474-50052ecf-7de4-4aab-8e6c-6eb89f41cf2a.png)

### Environment

<details>
<summary>Version information</summary>

```
Microsoft Visual Studio Enterprise 2022
Version 17.2.1
VisualStudio.17.Release/17.2.1+32516.85
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   17.2.388.21846
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.2.388.21846
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.2.388.21846
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.2.0-4.22252.24+47cdc16a21bbb8a4aadfb666b011e2059e1be5d2
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CodeMaid   12.0
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

File Icons   2.7
Adds icons for files that are not recognized by Solution Explorer

GitHub Copilot   1.14.0.1 (v1.14.0.1@c80f05666)
GitHub Copilot is an AI pair programmer that helps you write code faster and with less work.

GitHub Copilot Agent   1.14.5744 (v1.14.0)

Markdown Editor v2   2.0.104
A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.2.20 (482eb2a)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Open Command Line   2.5.238
2.5.238

OpenOnGitHub   1.3
Visual Studio Extension for opening files on GitHub.com

Razor (ASP.NET Core)   17.0.0.2218101+885a343b00bcab620a90c1550c37dafd730ce984
Provides languages services for ASP.NET Core Razor.

ResX Resource Manager   ResXManager
Manage localization of all ResX-based resources in one place. Shows all resources of a solution and lets you edit the strings and their localizations in a well-arranged data grid.

SQL Server Data Tools   17.0.62204.01010
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.10418.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.2.0-4.22252.24+47cdc16a21bbb8a4aadfb666b011e2059e1be5d2
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.22253.3+058e7a7e597a02c129f38742f250a4b212da9ee3
Microsoft Visual F# Tools

Visual Studio Inline Suggestions   2.2.1994.35131
Ghost text API for Visual Studio inline suggestions

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   17.2.0.174 (d17-2@fb414d4)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.2.0.244 (remotes/origin/d17-2@197e1a0b7)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.2.15 (2e3b60e)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.3.0.3 (d17-2/bbba5a2)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: adf1bc4
    Java.Interop: xamarin/java.interop/d17-2@9760f0a9
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.38.2@7b1e016
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-2@fc3c2ac


Xamarin.iOS and Xamarin.Mac SDK   15.10.0.1 (568bdb24e)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

xsd   1.0
Generate code fro XSD/JSON

xsd2code++   5.0
Advanced Code Generator From XML & JSON Schemas
```
</details>

### Build Logs

```
    DateTime=2022-05-19T10:33:17.5057227Z: 05.19.2022 10:33:17Z
Xamarin.VisualStudio.Progress.ProgressReportService Information: 0 : Resolving certificate...: 05.19.2022 10:33:21Z
    DateTime=2022-05-19T10:33:21.5031987Z: 05.19.2022 10:33:21Z
Xamarin.VisualStudio.Progress.ProgressReportService Information: 0 : !Resolving certificate...: 05.19.2022 10:33:21Z
    DateTime=2022-05-19T10:33:21.5031987Z: 05.19.2022 10:33:21Z
Xamarin.VisualStudio.Progress.ProgressReportService Information: 0 : Fetching valid and locally installed signing identities...: 05.19.2022 10:33:21Z
    DateTime=2022-05-19T10:33:21.5031987Z: 05.19.2022 10:33:21Z
Xamarin.VisualStudio.Progress.ProgressReportService Information: 0 : !Fetching valid and locally installed signing identities...: 05.19.2022 10:33:21Z
    DateTime=2022-05-19T10:33:21.5031987Z: 05.19.2022 10:33:21Z
Xamarin.VisualStudio.Progress.ProgressReportService Information: 0 : There was an error while trying to automatically provision the project, please check the logs.: 05.19.2022 10:33:21Z
    DateTime=2022-05-19T10:33:21.5031987Z: 05.19.2022 10:33:21Z
Xamarin.VisualStudio.Progress.ProgressReportService Information: 0 : !There was an error while trying to automatically provision the project, please check the logs.: 05.19.2022 10:33:21Z
    DateTime=2022-05-19T10:33:21.5031987Z: 05.19.2022 10:33:21Z
Xamarin.Messaging.Client.MessagingClient Error: 0 : An error occurred on the receiver while executing a post for topic xvs/idb/auto-provision and client vs11512Georg
Xamarin.Messaging.Exceptions.MessagingRemoteException: An error occurred on client IDBLocal while executing a reply for topic xvs/idb/auto-provision ---> System.NotSupportedException: The Apple Developer Portal web API for creating certificates is no longer supported. Please create your certificate manually.
   at Xamarin.MacDev.AppleSigning.CreateCertificate.<Run>d__9.MoveNext() in /Users/builder/azdo/_work/1/s/External/maciostools/Xamarin.MacDev.AppleSigning/ProvisioningTasks/CreateCertificate.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.MacDev.AppleSigning.ResolveCertificate.<Run>d__13.MoveNext() in /Users/builder/azdo/_work/1/s/External/maciostools/Xamarin.MacDev.AppleSigning/ProvisioningTasks/ResolveCertificate.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.IDB.AppleProvisioningManager.<AutoProvisionAsync>d__22.MoveNext() in D:\a\_work\1\s\src\Messaging\Xamarin.Messaging.IDB.Local\AppleProvisioningManager.cs:line 419
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.IDB.Local.AutoProvisionHandler.<ExecuteAsync>d__2.MoveNext() in D:\a\_work\1\s\src\Messaging\Xamarin.Messaging.IDB.Local\Handlers\AutoProvisionHandler.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.Client.RequestHandler`2.<HandleAsync>d__5.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Client\Handlers\RequestHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.Client.MessageHandlerManager.<>c__DisplayClass16_1`2.<<RegisterHandlerAsync>b__2>d.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Client\MessageHandlerManager.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.Client.MessagingClient.<ReplyAsync>d__32`2.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Client\MessagingClient.cs:line 0
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Xamarin.Messaging.Client.ApplicationMessageExtensions.<>c__DisplayClass10_0`1.<OfResponse>b__1(MqttApplicationMessage m) in D:\a\_work\1\s\src\Xamarin.Messaging.Client\Extensions\ApplicationMessageExtensions.cs:line 194
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Xamarin.Messaging.Client.MessagingClient.<PostAsync>d__21`2.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Client\MessagingClient.cs:line 190: 05.19.2022 10:33:21Z
```

### Additional Information

When I open the settings to manage my apple account, it loads neither certificates nor provisioning profiles.

The build is running on a Mac Mini with M1.

**Comment by chamons** [comment]
Thanks so much for the feedback.

Unfortunately, this is considered an IDE bug, as it is in Visual Studio, and that team is not accessible from github.

Please see the instructions [here](https://developercommunity.visualstudio.com/report?space=8&entry=problem) to file an issue so that team can help.

Thanks!
