### ISSUE TITLE
Can't start ShazamKit 

### ISSUE THREAD

**Issue by vadd98** [xamarin/xamarin-macios#15138]
Hi, I'm trying to implement ShazamKit in a MAUI app, by the way I'm always getting an exception when I try to instantiate a SHSession.
I'm using the simulator because at the moment I don't have any physical iPhone to test, by the way a tried a native ShazamKit demo project found on Github on the simulator and it works fine.

### Steps to Reproduce

1. Create a basic MAUI app
2. Try to instantiate a native SHSession of the iOS platform

### Expected Behavior
Instantiate a SHSession

### Actual Behavior
Can't instantiate a SHSession. 
This is the exception I'm getting:

> Could not create an native instance of the type 'ShazamKit.SHSession': the native class hasn't been loaded.
It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false.
   at Foundation.NSObject.InitializeObject(Boolean alloced)
   at Foundation.NSObject..ctor(NSObjectFlag x)
   at ShazamKit.SHSession..ctor()
   at Compilero.Mobile.Platforms.iOS.Services.IOsShazamKitService..ctor()

### Environment

<details>
<summary>Version information</summary>
```
Xamarin iOS & Mac 15.10.0.1
iOS version 15.0
```
</details>

**Comment by chamons** [comment]
Initial testing confirms this. I tried setting code signing on my maui project to match an xcode project that works on sim, but so far I'm seeing a difference. Will need to look into it more.

**Comment by vadd98** [comment]
Sure, I used this one https://github.com/heysaik/ShazamKit-Demo

I'm aware of that issue, indeed I can't get any Match in the simulator, by the way the whole system works and returns a NoMatch result, while using Xamarin I can't even create the session.

**Comment by rolfbjarne** [comment]
Yes, we won't link with ShazamKit because we think it's only available on device:

https://github.com/xamarin/xamarin-macios/blob/d869a6868a0a1fb33a1bbec34a5b1542c227b9b8/tools/common/Frameworks.cs#L445

You can probably work around it by adding this to your csproj:

```xml
<PropertyGroup>
    <MtouchExtraArgs>-gcc_flags="-framework ShazamKit"</MtouchExtraArgs>
</PropertyGroup>
```

**Comment by vadd98** [comment]
I tried your suggestion and indeed now works in the simulator! 
Obviously it does not get any match, by the way I can test the implementation
