### ISSUE TITLE
System.Runtime.Loader.AssemblyDependencyResolver doesn't work in macOS

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#15685]
Repro:

Add this to a managed Main function of a `net6.0-macos` project:

```cs
try {
	new System.Runtime.Loader.AssemblyDependencyResolver ("/tmp");
} catch (Exception e) {
	Console.WriteLine ($"❌ {e}");
	return 1;
}
```

Complete file: https://github.com/rolfbjarne/xamarin-macios/commit/bd36139787fda5ee9244d77361a480d6513f6d83

Output:

```
❌ System.InvalidOperationException: Dependency resolution failed for component /tmp with error code -2147450750. Detailed error: Hostpolicy must be initialized and corehost_main must have been called before calling corehost_resolve_component_dependencies.

   at System.Runtime.Loader.AssemblyDependencyResolver..ctor(String componentAssemblyPath)
   at MySimpleApp.Program.Main(String[] args) in /Users/rolf/work/maccore/main/xamarin-macios/tests/dotnet/MySimpleApp/AppDelegate.cs:line 15
````

**Comment by julewingchun** [comment]
Are there any news about this bug? I am experiencing the same issue.

**Comment by rolfbjarne** [comment]
@julewingchun no news yet, and it will likely take a while until we get around to look at it (maybe for .NET 8)
