### ISSUE TITLE
ILStrip failure for FsToolkit.ErrorHandling(Must be of type CilStrip.Mono.Cecil.TypeReference)

### ISSUE THREAD

**Issue by NickDarvey** [xamarin/xamarin-macios#18485]
### Steps to Reproduce

1. Download `FsToolkitiOSApp.zip` (attached)
2. Run
    ```
    dotnet build -c Release -t:Run -f net7.0-ios -p:RuntimeIdentifier=ios-arm64 -p:_DeviceName=1234 -bl
    ``` 

### Expected Behavior

Release build completes.

### Actual Behavior

```
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7067/targets/Xamarin.Shared.Sdk.targets(765,3): ILStrip failed for obj/Release/net7.0-ios/ios-arm64/linked/FsToolkit.ErrorHandling.dll: Must be of type CilStrip.Mono.Cecil.TypeReference [/FsToolkitiOSApp.fsproj]


System.ArgumentException: Must be of type CilStrip.Mono.Cecil.TypeReference
   at CilStrip.Mono.Cecil.GenericArgumentCollection.OnValidate(Object o)
   at System.Collections.CollectionBase.System.Collections.IList.Add(Object value)
   at CilStrip.Mono.Cecil.GenericArgumentCollection.Add(TypeReference value)
   at CilStrip.Mono.Cecil.ReflectionReader.GetTypeRefFromSig(SigType t, GenericContext context)
   at CilStrip.Mono.Cecil.ReflectionReader.GetGenericArg(GenericArg arg, GenericContext context)
   at CilStrip.Mono.Cecil.ReflectionReader.GetTypeRefFromSig(SigType t, GenericContext context)
   at CilStrip.Mono.Cecil.ReflectionReader.CompleteParameter(ParameterDefinition parameter, Param signature, GenericContext context)
   at CilStrip.Mono.Cecil.ReflectionReader.BuildParameterDefinition(String name, Int32 sequence, ParameterAttributes attrs, Param psig, GenericContext context)
   at CilStrip.Mono.Cecil.ReflectionReader.CompleteMethods()
   at CilStrip.Mono.Cecil.ReflectionReader.VisitTypeDefinitionCollection(TypeDefinitionCollection types)
   at CilStrip.Mono.Cecil.AggressiveReflectionReader.VisitTypeDefinitionCollection(TypeDefinitionCollection types)
   at CilStrip.Mono.Cecil.ReflectionReader.VisitModuleDefinition(ModuleDefinition mod)
   at CilStrip.Mono.Cecil.StructureReader.TerminateAssemblyDefinition(AssemblyDefinition asm)
   at CilStrip.Mono.Cecil.AssemblyDefinition.Accept(IReflectionStructureVisitor visitor)
   at CilStrip.Mono.Cecil.AssemblyFactory.GetAssembly(ImageReader irv, Boolean manifestOnly)
   at CilStrip.Mono.Cecil.AssemblyFactory.GetAssembly(ImageReader reader)
   at CilStrip.Mono.Cecil.AssemblyFactory.GetAssembly(String file)
   at ILStrip.StripAssembly(ITaskItem assemblyItem)
   
```

### Environment

<details>
<summary>Version information</summary>

```
dotnet  7.0.304
dotnet workload maui-ios 7.0.86/7.0.100
```

</details>

### Build Logs and Example Project

[FsToolkitiOSApp.zip](https://github.com/xamarin/xamarin-macios/files/11816963/FsToolkitiOSApp.zip)

### Workaround

Disabling IL stripping, as described in https://github.com/xamarin/xamarin-macios/issues/14841#issue-1218995218, works.

Is there a way to _only_ disable it for this asssembly?

**Comment by rolfbjarne** [comment]
Smaller repro: [testproj.zip](https://github.com/xamarin/xamarin-macios/files/11817339/testproj.zip)

Download & execute:

```
$ dotnet build /t:RunILStrip
testproj.csproj(10,5): error : ILStrip failed for FsToolkit.ErrorHandling.dll: Must be of type CilStrip.Mono.Cecil.TypeReference
```

**Comment by rolfbjarne** [comment]
> Is there a way to _only_ disable it for this asssembly?

It's rather ugly, but you can add something like this to your project file:

```xml
  <Target Name="_RemoveILStripTrigger" BeforeTargets="_StripAssemblyIL">
    <ItemGroup>
      <_RemovedResolvedFileToPublish Include="@(ResolvedFileToPublish)" Condition="'%(Filename)%(Extension)' == 'FsToolkit.ErrorHandling.dll'" />
      <ResolvedFileToPublish Remove="@(_RemovedResolvedFileToPublish)" />
    </ItemGroup>
  </Target>

  <Target Name="_RestoreILStripTrigger" AfterTargets="_StripAssemblyIL">
    <ItemGroup>
      <ResolvedFileToPublish Include="@(_RemovedResolvedFileToPublish)" />
    </ItemGroup>
  </Target>
```

**Comment by rolfbjarne** [comment]
Moving to dotnet/runtime, since the ILStrip implementation lives there.

**Comment by rolfbjarne** [comment]
This issue was moved to dotnet/runtime#87867

**Comment by NickDarvey** [comment]
Thanks @rolfbjarne
