### ISSUE TITLE
WatchOs project could't install in debug

### ISSUE THREAD

**Issue by jmmortega** [xamarin/xamarin-macios#18781]
I test in several Macs (Intel and ARM) and received the same output.

### Steps to Reproduce

1. Create a new WatchOs project with Visual Studio For Mac
2. Run the project using any Watch Simulator

### Expected Behavior

Simulator open and runs the watch project

### Actual Behavior

Receive an error Execution Failed without any information to triage what happens

### Environment

Visual Studio Community 2022 for Mac
Version 17.6.3 (build 421)
Installation UUID: 7d92e14f-0b68-4c5c-ab0e-d3d2af8e7a37

Runtime
.NET 7.0.3 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2

Roslyn (Language Service)
4.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.307/Sdks
SDK Versions:
	8.0.100-preview.6.23330.14
	7.0.307
	7.0.306
	7.0.302
	7.0.201
	7.0.102
	7.0.101
	7.0.100
	6.0.413
	6.0.412
	6.0.408
	6.0.406
	6.0.405
	6.0.404
	6.0.403
	6.0.100
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Version: 3.1.426

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	8.0.0-preview.6.23329.7
	7.0.10
	7.0.9
	7.0.5
	7.0.3
	7.0.2
	7.0.1
	7.0.0
	6.0.21
	6.0.20
	6.0.16
	6.0.14
	6.0.13
	6.0.12
	6.0.11
	6.0.0

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	7.0.3
	3.1.32

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode: 14.3.1 21814
Build: 14E300b

Xamarin.Mac
Version: 9.3.0.6 Visual Studio Community
Hash: 97731c92c
Branch: xcode14.3
Build date: 2023-04-11 22:38:35-0400

Xamarin.iOS
Version: 16.4.0.6 Visual Studio Community
Hash: 97731c92c
Branch: xcode14.3
Build date: 2023-04-11 22:38:36-0400

Xamarin Designer
Version: 17.6.3.9
Hash: 2648399ae8
Branch: remotes/origin/d17-6
Build date: 2023-08-02 19:06:42 UTC

Xamarin.Android
Version: 13.2.1.2 (Visual Studio Community)
Commit: xamarin-android/d17-5/a8a26c7
Android SDK: /Users/jmmontero/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.1 (API level 32)
		8.0  (API level 26)
		12.0 (API level 31)
		8.1  (API level 27)
		11.0 (API level 30)
		10.0 (API level 29)
		9.0  (API level 28)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 34.0.1
SDK Build Tools Version: 33.0.1

Build Information: 
Mono: d9a6e87
Java.Interop: xamarin/java.interop/d17-5@149d70fe
SQLite: xamarin/sqlite/3.40.1@68c69d8
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.6.0.50
Hash: a715dca
Branch: HEAD
Build date: 2023-08-02 19:06:47 UTC

Android Device Manager
Version: 0.0.0.1309
Hash: 06e3e77
Branch: HEAD
Build date: 2023-08-02 19:06:47 UTC

Build Information
Release ID: 1706030421
Git revision: c90350679f1b9295edc584519320b13d06489853
Build date: 2023-08-02 19:05:00+00
Build branch: release-17.6
Build lane: release-17.6

Operating System
Mac OS X 13.1.0
Darwin 22.2.0 Darwin Kernel Version 22.2.0
    Fri Nov 11 02:03:51 PST 2022
    root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64

### Build Logs

Not proceed, with start project it's enough

### Example Project (If Possible)

Not proceed, with start project it's enough

**Comment by jmmortega** [comment]
@rolfbjarne hey, thank you for your quick response. It's weird. I don't have this folder

**Comment by rolfbjarne** [comment]
What do you get when you execute this in a terminal?

```
ls -la ~/Library/Logs
```

**Comment by jmmortega** [comment]
[VSLogs.zip](https://github.com/xamarin/xamarin-macios/files/12418937/VSLogs.zip)
OK. Sorry I check in the wrong Library folder. 🥲

**Comment by rolfbjarne** [comment]
Looks like that's from ~/Library/VisualStudio, not ~/Library/Logs/VisualStudio?

**Comment by rolfbjarne** [comment]
This looks like a problem in VSMac:

```
ERROR [2023-08-24 10:33:02Z]: Execution failed.
System.NullReferenceException: Object reference not set to an instance of an object.
   at MonoDevelop.Projects.DotNetProject.OnExecute(ProgressMonitor monitor, ExecutionContext context, ConfigurationSelector configuration, SolutionItemRunConfiguration runConfiguration) in /Users/runner/work/1/s/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs:line 2400
   at MonoDevelop.Projects.SolutionItem.DoExecute(ProgressMonitor monitor, ExecutionContext context, ConfigurationSelector configuration, SolutionItemRunConfiguration runConfiguration) in /Users/runner/work/1/s/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItem.cs:line 1172
   at MonoDevelop.Debugger.HotReload.HotReloadProjectExtension.OnExecute(ProgressMonitor monitor, ExecutionContext context, ConfigurationSelector configuration, SolutionItemRunConfiguration runConfiguration) in /Users/runner/work/1/s/main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.HotReload/HotReloadProjectExtension.cs:line 110
   at MonoDevelop.UnitTesting.UnitTestProjectServiceExtension.OnExecute(ProgressMonitor monitor, ExecutionContext context, ConfigurationSelector configuration, SolutionItemRunConfiguration runConfiguration) in /Users/runner/work/1/s/main/src/addins/MonoDevelop.UnitTesting/Services/UnitTestProjectServiceExtension.cs:line 108
   at MonoDevelop.IPhone.IPhoneProjectFlavor.OnExecute(ProgressMonitor monitor, ExecutionContext context, ConfigurationSelector configuration, SolutionItemRunConfiguration runConfiguration) in /Users/runner/work/1/s/MonoDevelop.IPhone/MonoDevelop.IPhone/Project/IPhoneProject.cs:line 798
   at MonoDevelop.Projects.SolutionItem.Execute(ProgressMonitor monitor, ExecutionContext context, ConfigurationSelector configuration, SolutionItemRunConfiguration runConfiguration) in /Users/runner/work/1/s/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItem.cs:line 1060
   at MonoDevelop.Projects.Solution.OnExecute(ProgressMonitor monitor, ExecutionContext context, ConfigurationSelector configuration, SolutionRunConfiguration runConfiguration) in /Users/runner/work/1/s/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Solution.cs:line 1216
   at MonoDevelop.Ide.ProjectOperations.ExecuteSolutionItemAsync(ProgressMonitor monitor, IBuildTarget entry, ExecutionContext context, ConfigurationSelector configuration, RunConfiguration runConfiguration) in /Users/runner/work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs:line 1391
```

**Comment by rolfbjarne** [comment]
> Any suggestion or workaround?

Unfortunately no, the VS Mac team will have to investigate.
