### ISSUE TITLE
Archiving for iOS (through MAUI) fails when the path is too long

### ISSUE THREAD

**Issue by datvm** [xamarin/xamarin-macios#19445]
### Steps to Reproduce

1. Create a MAUI project
2. Use a library like `BlazorMaterialWeb.Bundled` that contains a file with a long name: `wwwroot\_content\BlazorMaterialWeb.Bundled\roboto\fonts\roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-100.woff2`
3. Build and archive it

### Expected Behavior

It should be archived successfully

### Actual Behavior

The UI does not respond, the log file in `AppData\Local\Xamarin\Logs\17.0` contains the following exception:

```
Xamarin.VisualStudio.Publishing.Presentation.ViewModels.ArchiveListViewModel Error: 0 : System.IO.FileNotFoundException: Could not find file 'C:\Users\lukev\AppData\Local\Xamarin\iOS\Archives\2023-11-13\MyAppName 11-13-23 2.54 PM.xcarchive\Products\Applications\MyAppName.app\wwwroot\_content\BlazorMaterialWeb.Bundled\roboto\fonts\roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-100.woff2'.
File name: 'C:\Users\lukev\AppData\Local\Xamarin\iOS\Archives\2023-11-13\MyAppName 11-13-23 2.54 PM.xcarchive\Products\Applications\MyAppName.app\wwwroot\_content\BlazorMaterialWeb.Bundled\roboto\fonts\roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-100.woff2'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at Xamarin.VisualStudio.IOS.Publishing.IOSProjectArchive.get_Size() in D:\a\_work\1\s\src\Core\VisualStudio.IOS\ProjectSystem\Publishing\IOSProjectArchive.cs:line 233
   at Xamarin.VisualStudio.Publishing.Presentation.ViewModels.BuildViewModel.SetModel(IProjectArchive model) in D:\a\_work\1\s\src\Core\VisualStudio.Publishing\Presentation\ViewModels\BuildViewModel.cs:line 298
   at Xamarin.VisualStudio.Publishing.Presentation.ViewModels.BuildViewModel..ctor(ArchiveViewModel archiveViewModel, IProjectArchive model, IArchiveManager archiveManager, JoinableTaskFactory asyncManager, IEventStream eventStream, IProgressReportService progressReportService) in D:\a\_work\1\s\src\Core\VisualStudio.Publishing\Presentation\ViewModels\BuildViewModel.cs:line 123
   at Xamarin.VisualStudio.Publishing.Presentation.ViewModels.ArchiveListViewModel.<OnNewBuildCompletedAsync>d__60.MoveNext() in D:\a\_work\1\s\src\Core\VisualStudio.Publishing\Presentation\ViewModels\ArchiveListViewModel.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.VisualStudio.Publishing.Presentation.ViewModels.ArchiveListViewModel.<>c__DisplayClass59_3.<<SubscribeToEvents>b__10>d.MoveNext() in D:\a\_work\1\s\src\Core\VisualStudio.Publishing\Presentation\ViewModels\ArchiveListViewModel.cs:line 315: 11/13/2023 20:54:40Z
    DateTime=2023-11-13T20:54:40.3083853Z: 11/13/2023 20:54:40Z
```

### Environment

<details>
<summary>Version information</summary>

```
Microsoft Visual Studio Community 2022
Version 17.7.5
VisualStudio.17.Release/17.7.5+34202.233
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA888
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.7.273.65229
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.7.273.65229
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.7.273.65229
Azure Functions and Web Jobs Tools

C# Tools   4.7.0-3.23469.2+a3b9f0c274649870015cfe508cacde8fdc15df55
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.4.34 (main@d5ab18b)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitHub Copilot   1.133.0.0 (v1.133.0.0@a12ebe1a4)
GitHub Copilot is an AI pair programmer that helps you write code faster and with less work.

GitHub Copilot Agent   1.133.0

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.7.27 (547ea6f)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.50628.1 Commit Hash:f9e713b25f69afd3ced63d934e0722003b73c121
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.7.3.2333001+0ab18affdf2a37647768d0e25f5f021bee6257a1
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.7.10.1
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

Tweaks 2022   1.1.143
A collection of minor fixes and tweaks for Visual Studio to reduce the paper cuts and make you a happier developer

TypeScript Tools   17.0.20829.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.7.0-3.23469.2+a3b9f0c274649870015cfe508cacde8fdc15df55
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.7.0-beta.23314.10+e612cf93b989503c89e3a5830090062b7ab5e143
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Web Compiler   1.14.11
Compiler for LESS, Sass and CoffeeScript files

Xamarin   17.7.0.223 (d17-7@c374b3e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.7.3.9 (remotes/origin/d17-7@796d191def)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.7.21 (150ec9f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.1.2 (d17-5/a8a26c7)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d


Xamarin.iOS and Xamarin.Mac SDK   16.4.0.18 (9d266025e)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Build Logs

Not relevant, see the log above. Build was successful and no problem with it.

**Comment by datvm** [comment]
This is similar to #14974 and https://developercommunity.visualstudio.com/t/XamarinFormsVisualMaterial-paths-too-/10025061 but unfortunately they are both closed. Apparently it happens to Android as well though thankfully I don't use Archive for Android.

**Comment by datvm** [comment]
For those with this issue, the archiving is actually still successful but you can no longer access it on your Windows' UI. You can access it on your Mac (XCode -> Window -> Organizer). You can distribute your app from there but it's very inconvenient.

**Comment by rolfbjarne** [comment]
I can reproduce this, but it's a problem in VS, and as such it'll have to be filed elsewhere unfortunately.

**Comment by datvm** [comment]
Thanks for checking and confirming, I've made a report [here](https://developercommunity.visualstudio.com/t/Archiving-for-iOS-through-MAUI-fails-w/10518154)
