### ISSUE TITLE
iOS App launch failing due to missing net.dot.mauitesting/Info.plist with default apps

### ISSUE THREAD

**Issue by LoopedBard3** [xamarin/xamarin-macios#19449]
This is failing in the dotnet-performance pipeline with the same error for both Maui and regular .NET apps. The instructions provided match the Maui app generation and testing flow. Includes build steps for at the low level and at the level for performance scenario automation: https://github.com/dotnet/performance. Pipeline run demonstrating the error: https://dev.azure.com/dnceng/internal/_build/results?buildId=2314628&view=logs&j=d8c84c9f-cdb2-5d72-a012-e2d37b93fcd3&t=2c2568b4-314a-5c0e-ad0f-cf0d98716086. 

#### Build performance repo
1. Clone dotnet/performance
2. cd into src/scenarios and run init.sh
3. cd into mauiios
4. Select XCode 15 `sudo xcode-select -s /Applications/Xcode_15.0.app` 
5. python pre.py publish -f net8.0-ios --self-contained --binlog ./mauiios.binlog -c Release -r ios-arm64

#### Build Inner-steps
1. Install Dotnet + Maui
6. Create a new default Maui app
7. Restore the app with `dotnet restore ./src/scenarios/mauiios/app/MauiiOSDefault.csproj --packages ./artifacts/packages /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 -bl:./mauiios.binlog-restore.binlog /p:EnableWindowsTargeting=true`
8. Publish the app with `dotnet publish ./src/scenarios/mauiios/app/MauiiOSDefault.csproj --configuration Release /p:NuGetPackageRoot=./artifacts/packages/ /p:RestorePackagesPath=./artifacts/packages/ /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 ./scenarios_out/mauiios --runtime ios-arm64 --framework net8.0-ios -bl:./mauiios.binlog /p:_RequireCodeSigning=false /p:ApplicationId=net.dot.mauitesting --self-contained /p:EnableWindowsTargeting=true`

#### Xharness/mlaunch steps
9. Use XHarness/mlaunch to install the app: `dotnet exec ./microsoft.dotnet.xharness.cli/9.0.0-prerelease.23556.1/tools/net7.0/any/Microsoft.DotNet.XHarness.CLI.dll apple install --app MauiiOSDefault.app --target ios-device -o traces -v`
10. Use XHarness/mlaunch to launch the app: `dotnet exec ./microsoft.dotnet.xharness.cli/9.0.0-prerelease.23556.1/tools/net7.0/any/Microsoft.DotNet.XHarness.CLI.dll apple mlaunch -- --launchdevbundleid=net.dot.mauitesting`

### Expected Behavior

App starts successfully.

### Actual Behavior
```
Completed install.
Waiting 10 secs to ensure we're not getting confused with previous app run.
Collect startup data for iteration 0.
$ dotnet exec /tmp/helix/working/A30F08E5/p/microsoft.dotnet.xharness.cli/9.0.0-prerelease.23556.1/tools/net7.0/any/Microsoft.DotNet.XHarness.CLI.dll apple mlaunch -- --launchdevbundleid=net.dot.mauitesting
2023-11-13 19:20:25.098 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.IDEDebugger.VariablesViewQuickLookProvider for extension Xcode.IDEDebugger.SpriteKitQuickLookProvider of plug-in com.apple.IDESpriteKitParticleEditor
2023-11-13 19:20:25.098 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.IDEDebugger.VariablesViewQuickLookProvider for extension Xcode.SpriteKit.GKStateMachineQuickLookProvider of plug-in com.apple.IDESpriteKitParticleEditor
2023-11-13 19:20:25.112 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.watchOSSimulator.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEWatchSupportUI
2023-11-13 19:20:25.112 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.ExtensionKitAppExtension of plug-in com.apple.dt.IDEWatchSupportUI
2023-11-13 19:20:25.112 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.AppExtension of plug-in com.apple.dt.IDEWatchSupportUI
2023-11-13 19:20:25.112 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.WatchApplication of plug-in com.apple.dt.IDEWatchSupportUI
2023-11-13 19:20:25.112 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.IntentsService-AppExtension of plug-in com.apple.dt.IDEWatchSupportUI
2023-11-13 19:20:25.112 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorSlice for extension Xcode.Xcode3ProjectSupport.InfoEditorSlice.WatchOS.BundleInfo of plug-in com.apple.dt.IDEWatchSupportUI
2023-11-13 19:20:25.112 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.watchOS.ViewDescriber of plug-in com.apple.dt.IDEWatchSupportUI
2023-11-13 19:20:25.112 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.WatchKit2-AppExtension of plug-in com.apple.dt.IDEWatchSupportUI
2023-11-13 19:20:25.112 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.IDEiPhoneSupport.TargetEditor for extension Xcode.IDEiPhoneSupport.TargetEditor.WatchOS.Application of plug-in com.apple.dt.IDEWatchSupportUI
2023-11-13 19:20:25.112 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.WatchOS.Bundle of plug-in com.apple.dt.IDEWatchSupportUI
2023-11-13 19:20:25.112 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.Tool of plug-in com.apple.dt.IDEWatchSupportUI
2023-11-13 19:20:25.112 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.Application of plug-in com.apple.dt.IDEWatchSupportUI
2023-11-13 19:20:25.112 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.watchOSSimulator.ViewDescriber of plug-in com.apple.dt.IDEWatchSupportUI
2023-11-13 19:20:25.112 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.Framework of plug-in com.apple.dt.IDEWatchSupportUI
2023-11-13 19:20:25.112 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEWatchSupportUI:IDEWatchSupportUI.plugindata/plug-in[1]/extension[20] of plug-in com.apple.dt.IDEWatchSupportUI
2023-11-13 19:20:25.112 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.watchOS.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEWatchSupportUI
2023-11-13 19:20:25.113 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEOSXSupportUI:IDEOSXSupportUI.plugindata/plug-in[1]/extension[5] of plug-in com.apple.dt.IDE.IDEOSXSupportUI
2023-11-13 19:20:25.114 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.IDEAppleTVSupportUI.AppExtension of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-11-13 19:20:25.114 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.IDEAppleTVSupportUIFramework of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-11-13 19:20:25.114 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorSlice for extension Xcode.Xcode3ProjectSupport.InfoEditorSlice.appletvos.BundleTargetInfo of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-11-13 19:20:25.114 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.tvOS.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-11-13 19:20:25.114 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.ATV.ViewDescriber of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-11-13 19:20:25.114 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.appletvos.Bundle of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-11-13 19:20:25.114 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.tvOSSimulator.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-11-13 19:20:25.114 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.IDEAppleTVSupportUI.Application of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-11-13 19:20:25.114 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEAppleTVSupportUI:IDEAppleTVSupportUI.plugindata/plug-in[1]/extension[16] of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-11-13 19:20:25.114 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.IDEAppleTVSupportUI.XPC of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-11-13 19:20:25.114 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DeviceIconProvider for extension Xcode.DebuggerFoundation.DeviceIconProvider.AppleTV of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-11-13 19:20:25.114 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.ATVSimulator.ViewDescriber of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-11-13 19:20:25.114 mlaunch[1288:13637] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.IDEAppleTVSupportUI.ExtensionKitAppExtension of plug-in com.apple.dt.IDEAppleTVSupportUI
error MT0000: Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
System.IO.FileNotFoundException: Could not find required file 'net.dot.mauitesting/Info.plist'.
   at Xamarin.Hosting.PList.FromFile(String) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/PList.cs:line 24
   at Xamarin.Hosting.PlistBasedAppBundle..ctor(String) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/PlistBasedAppBundle.cs:line 21
   at Xamarin.Launcher.Driver.LaunchOrDebugUsingDeviceCtl(Action, RealDevice) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 576
   at Xamarin.Launcher.Driver.LaunchOrDebugAsync(Action) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 547
   at Xamarin.Launcher.Driver.MainAsync() in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 491
   at Xamarin.Utils.NSRunLoopExtensions.RunUntilTaskCompletion[T](NSRunLoop, Task`1) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Utils/Extensions.cs:line 30
   at Xamarin.Launcher.Driver.Main2(String[]) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 436
   at Xamarin.Launcher.Driver.Main(String[]) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 123
Process exited with status 1
App launch failed, please rerun the script to start a new measurement.
```

### Environment
Running using the cli, listing versions manually.

<details>
<summary>Version information</summary>

```
Used rollback config from https://aka.ms/dotnet/maui/net8.0.json
Installing workload manifest microsoft.net.sdk.android version 34.0.47...
Installing workload manifest microsoft.net.sdk.ios version 17.0.8481...
Installing workload manifest microsoft.net.sdk.maccatalyst version 17.0.8481...
Installing workload manifest microsoft.net.sdk.macos version 14.0.8481...
Installing workload manifest microsoft.net.sdk.maui version 8.0.0-ci.net8.9610...
Installing workload manifest microsoft.net.sdk.tvos version 17.0.8481...
Installing workload manifest microsoft.net.workload.mono.toolchain.net7 version 8.0.0...
Installing workload manifest microsoft.net.workload.mono.toolchain.current version 8.0.0...
Installing workload manifest microsoft.net.workload.emscripten.net7 version 8.0.0...
Installing workload manifest microsoft.net.workload.emscripten.current version 8.0.0...
Installing pack Microsoft.AspNetCore.Components.WebView.Maui version 8.0.0-ci.net8.9610...

#dotnet --info from build machine (different from run machine)
.NET SDK:
 Version:           8.0.100
 Commit:            ae28d5bc06
 Workload version:  8.0.100-manifests.e7f351aa

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.6
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /Users/runner/work/1/s/CorrelationStaging/dotnet/sdk/8.0.100/

MauiVersion from Microsoft.Maui.dll: 8.0.0-ci.net8.9610+sha.a30c67d65f-azdo.8675422.a30c67d65faff1b517e1c73e93116313f183dd03

# Run Machine
[9.0.0-prerelease.23556.1+9fedae3f21825fb3d962ffb65d1a4b781a55116a] XHarness command issued: apple state
Runtime Enviroment:
  Machine name:	DNCENGMAC044
  OS Name:	Mac OS X
  OS Version:	10.18
  OS Platform:	Darwin

Developer Tools:
  Xcode:	15.0 - /Applications/Xcode_15.0.app
  Mlaunch:	Xamarin.Launcher 1.0.82 (refs/heads/main: 04b71d98c8) - ./microsoft.dotnet.xharness.cli/9.0.0-prerelease.23556.1/tools/net7.0/any/../../../runtimes/any/native/mlaunch/bin/mlaunch
```

</details>

### Build Logs

Available via Teams DM.

### Example Project (If Possible)

The main app is the default maui app, setup is done via automation in https://github.com/dotnet/performance.

**Comment by rolfbjarne** [comment]
I can reproduce this, and a fix is in progress.

As a workaround, you can pass the path to the app bundle instead of the bundleid:

> dotnet exec ./microsoft.dotnet.xharness.cli/9.0.0-prerelease.23556.1/tools/net7.0/any/Microsoft.DotNet.XHarness.CLI.dll apple mlaunch -- --launchdev MauiiOSDefault.app

and that should work fine.

**Comment by LoopedBard3** [comment]
Awesome! That seems to have helped the app launch get further, now I am hitting this error:
```
[2023/11/16 11:04:00][INFO] $ dotnet exec /tmp/helix/working/B1BD09D1/p/microsoft.dotnet.xharness.cli/9.0.0-prerelease.23556.1/tools/net7.0/any/Microsoft.DotNet.XHarness.CLI.dll apple mlaunch -- --launchdev MauiiOSDefault.app
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.749 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.IDEDebugger.VariablesViewQuickLookProvider for extension Xcode.SpriteKit.GKStateMachineQuickLookProvider of plug-in com.apple.IDESpriteKitParticleEditor
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.749 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.IDEDebugger.VariablesViewQuickLookProvider for extension Xcode.IDEDebugger.SpriteKitQuickLookProvider of plug-in com.apple.IDESpriteKitParticleEditor
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.762 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.IDEiPhoneSupport.TargetEditor for extension Xcode.IDEiPhoneSupport.TargetEditor.WatchOS.Application of plug-in com.apple.dt.IDEWatchSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.762 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.WatchOS.Bundle of plug-in com.apple.dt.IDEWatchSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.762 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.Tool of plug-in com.apple.dt.IDEWatchSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.762 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.Application of plug-in com.apple.dt.IDEWatchSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.762 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.watchOSSimulator.ViewDescriber of plug-in com.apple.dt.IDEWatchSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.762 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.Framework of plug-in com.apple.dt.IDEWatchSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.762 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEWatchSupportUI:IDEWatchSupportUI.plugindata/plug-in[1]/extension[20] of plug-in com.apple.dt.IDEWatchSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.762 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.watchOS.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEWatchSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.762 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.watchOSSimulator.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEWatchSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.762 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.ExtensionKitAppExtension of plug-in com.apple.dt.IDEWatchSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.762 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.AppExtension of plug-in com.apple.dt.IDEWatchSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.762 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.WatchApplication of plug-in com.apple.dt.IDEWatchSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.762 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.IntentsService-AppExtension of plug-in com.apple.dt.IDEWatchSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.762 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorSlice for extension Xcode.Xcode3ProjectSupport.InfoEditorSlice.WatchOS.BundleInfo of plug-in com.apple.dt.IDEWatchSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.762 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.watchOS.ViewDescriber of plug-in com.apple.dt.IDEWatchSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.762 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.WatchKit2-AppExtension of plug-in com.apple.dt.IDEWatchSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.763 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEOSXSupportUI:IDEOSXSupportUI.plugindata/plug-in[1]/extension[5] of plug-in com.apple.dt.IDE.IDEOSXSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.763 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEAppleTVSupportUI:IDEAppleTVSupportUI.plugindata/plug-in[1]/extension[16] of plug-in com.apple.dt.IDEAppleTVSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.763 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.IDEAppleTVSupportUI.XPC of plug-in com.apple.dt.IDEAppleTVSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.763 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DeviceIconProvider for extension Xcode.DebuggerFoundation.DeviceIconProvider.AppleTV of plug-in com.apple.dt.IDEAppleTVSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.764 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.ATVSimulator.ViewDescriber of plug-in com.apple.dt.IDEAppleTVSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.764 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.IDEAppleTVSupportUI.ExtensionKitAppExtension of plug-in com.apple.dt.IDEAppleTVSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.764 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.IDEAppleTVSupportUI.AppExtension of plug-in com.apple.dt.IDEAppleTVSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.764 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.IDEAppleTVSupportUIFramework of plug-in com.apple.dt.IDEAppleTVSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.764 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorSlice for extension Xcode.Xcode3ProjectSupport.InfoEditorSlice.appletvos.BundleTargetInfo of plug-in com.apple.dt.IDEAppleTVSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.764 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.tvOS.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEAppleTVSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.764 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.ATV.ViewDescriber of plug-in com.apple.dt.IDEAppleTVSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.764 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.appletvos.Bundle of plug-in com.apple.dt.IDEAppleTVSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.764 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.tvOSSimulator.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEAppleTVSupportUI
[2023/11/16 11:04:02][INFO] 2023-11-16 11:04:02.764 mlaunch[1658:23662] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.IDEAppleTVSupportUI.Application of plug-in com.apple.dt.IDEAppleTVSupportUI
[2023/11/16 11:04:02][INFO] error MT0000: Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
[2023/11/16 11:04:02][INFO] System.Resources.MissingManifestResourceException: Could not find the resource "Xamarin.Localization.Mlaunch.MLResources.resources" among the resources "Xamarin.Bundler.Errors.resources" embedded in the assembly "Xamarin.Localization.Mlaunch", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
[2023/11/16 11:04:02][INFO]    at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String)
[2023/11/16 11:04:02][INFO]    at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo, Dictionary`2, Boolean, Boolean)
[2023/11/16 11:04:02][INFO]    at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo, Boolean, Boolean)
[2023/11/16 11:04:02][INFO]    at System.Resources.ResourceManager.GetString(String, CultureInfo)
[2023/11/16 11:04:02][INFO]    at Xamarin.Localization.Mlaunch.MLResources.get_ML1044() in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Localization.Mlaunch/MLResources.Designer.cs:line 965
[2023/11/16 11:04:02][INFO]    at Xamarin.Launcher.DevController.LaunchDeviceUsingDeviceCtl(DeviceLaunchConfig, String) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/controller-device.cs:line 915
[2023/11/16 11:04:02][INFO]    at Xamarin.Launcher.Driver.LaunchOrDebugUsingDeviceCtl(Action, RealDevice) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 577
[2023/11/16 11:04:02][INFO]    at Xamarin.Launcher.Driver.LaunchOrDebugAsync(Action) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 547
[2023/11/16 11:04:02][INFO]    at Xamarin.Launcher.Driver.MainAsync() in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 491
[2023/11/16 11:04:02][INFO]    at Xamarin.Utils.NSRunLoopExtensions.RunUntilTaskCompletion[T](NSRunLoop, Task`1) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Utils/Extensions.cs:line 30
[2023/11/16 11:04:02][INFO]    at Xamarin.Launcher.Driver.Main2(String[]) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 436
[2023/11/16 11:04:02][INFO]    at Xamarin.Launcher.Driver.Main(String[]) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 123
[2023/11/16 11:04:02][ERROR] Process exited with status 1
[2023/11/16 11:04:02][ERROR] App launch failed, please rerun the script to start a new measurement.
```

Since this is a different issue do you want me to file a new issue?

**Comment by rolfbjarne** [comment]
That's supposed to give this error (we've already fixed the error reporting to do this, the release of this fix is in progress):

> A device must be specified using --devname.

Would you be able to do as the error message says?

**Comment by LoopedBard3** [comment]
I will give adding that a shot, I am assuming the value for devname is the name of the device rather than the long ID listed next to it in the apple state listing?
