### ISSUE TITLE
xharness apple mlaunch killdev failing due to 'Unexpected Error'

### ISSUE THREAD

**Issue by LoopedBard3** [xamarin/xamarin-macios#19577]
After getting our apps to launch with the workaround in #19449, killing the app is returning an exit code of 1. This is failing in the dotnet-performance pipeline. I have included build steps for at the low level and at the level for performance scenario automation: https://github.com/dotnet/performance. Pipeline run demonstrating the error: https://dev.azure.com/dnceng/internal/_build/results?buildId=2329078&view=results

#### Build performance repo
1. Clone dotnet/performance
2. cd into src/scenarios and run init.sh
3. cd into mauiios
4. Select XCode 15 `sudo xcode-select -s /Applications/Xcode_15.0.app` 
5. python pre.py publish -f net8.0-ios --self-contained --binlog ./mauiios.binlog -c Release -r ios-arm64

#### Build Inner-steps
1. Install Dotnet + Maui
6. Create a new default Maui app
7. Restore the app with `dotnet restore ./src/scenarios/mauiios/app/MauiiOSDefault.csproj --packages ./artifacts/packages /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 -bl:./mauiios.binlog-restore.binlog /p:EnableWindowsTargeting=true`
8. Publish the app with `dotnet publish ./src/scenarios/mauiios/app/MauiiOSDefault.csproj --configuration Release /p:NuGetPackageRoot=./artifacts/packages/ /p:RestorePackagesPath=./artifacts/packages/ /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 ./scenarios_out/mauiios --runtime ios-arm64 --framework net8.0-ios -bl:./mauiios.binlog /p:_RequireCodeSigning=false /p:ApplicationId=net.dot.mauitesting --self-contained /p:EnableWindowsTargeting=true`

#### Xharness/mlaunch steps
9. Use XHarness/mlaunch to install the app: `dotnet exec ./microsoft.dotnet.xharness.cli/9.0.0-prerelease.23604.1/tools/net7.0/any/Microsoft.DotNet.XHarness.CLI.dll apple install --app MauiiOSDefault.app --target ios-device -o traces -v`
10. Use XHarness/mlaunch to launch the app: `dotnet exec .microsoft.dotnet.xharness.cli/9.0.0-prerelease.23604.1/tools/net7.0/any/Microsoft.DotNet.XHarness.CLI.dll apple mlaunch -- --launchdev MauiiOSDefault.app --devname <device_name>`
11. Use XHarness/mlaunch to try and kill the app: `dotnet exec ./microsoft.dotnet.xharness.cli/9.0.0-prerelease.23604.1/tools/net7.0/any/Microsoft.DotNet.XHarness.CLI.dll apple mlaunch -- --killdev=11259`

### Expected Behavior

The app is killed and the command returns 0.

### Actual Behavior

The command returns exit code 1 with the following output:

```
$ dotnet exec ./microsoft.dotnet.xharness.cli/9.0.0-prerelease.23604.1/tools/net7.0/any/Microsoft.DotNet.XHarness.CLI.dll apple mlaunch -- --killdev=11259
2023-12-04 19:09:06.759 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.IDEDebugger.VariablesViewQuickLookProvider for extension Xcode.SpriteKit.GKStateMachineQuickLookProvider of plug-in com.apple.IDESpriteKitParticleEditor
2023-12-04 19:09:06.760 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.IDEDebugger.VariablesViewQuickLookProvider for extension Xcode.IDEDebugger.SpriteKitQuickLookProvider of plug-in com.apple.IDESpriteKitParticleEditor
2023-12-04 19:09:06.772 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.Framework of plug-in com.apple.dt.IDEWatchSupportUI
2023-12-04 19:09:06.772 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEWatchSupportUI:IDEWatchSupportUI.plugindata/plug-in[1]/extension[20] of plug-in com.apple.dt.IDEWatchSupportUI
2023-12-04 19:09:06.772 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.watchOS.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEWatchSupportUI
2023-12-04 19:09:06.772 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.watchOSSimulator.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEWatchSupportUI
2023-12-04 19:09:06.772 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.ExtensionKitAppExtension of plug-in com.apple.dt.IDEWatchSupportUI
2023-12-04 19:09:06.772 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.AppExtension of plug-in com.apple.dt.IDEWatchSupportUI
2023-12-04 19:09:06.772 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.WatchApplication of plug-in com.apple.dt.IDEWatchSupportUI
2023-12-04 19:09:06.772 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.IntentsService-AppExtension of plug-in com.apple.dt.IDEWatchSupportUI
2023-12-04 19:09:06.772 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorSlice for extension Xcode.Xcode3ProjectSupport.InfoEditorSlice.WatchOS.BundleInfo of plug-in com.apple.dt.IDEWatchSupportUI
2023-12-04 19:09:06.772 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.watchOS.ViewDescriber of plug-in com.apple.dt.IDEWatchSupportUI
2023-12-04 19:09:06.772 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.WatchKit2-AppExtension of plug-in com.apple.dt.IDEWatchSupportUI
2023-12-04 19:09:06.772 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.IDEiPhoneSupport.TargetEditor for extension Xcode.IDEiPhoneSupport.TargetEditor.WatchOS.Application of plug-in com.apple.dt.IDEWatchSupportUI
2023-12-04 19:09:06.772 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.WatchOS.Bundle of plug-in com.apple.dt.IDEWatchSupportUI
2023-12-04 19:09:06.772 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.Tool of plug-in com.apple.dt.IDEWatchSupportUI
2023-12-04 19:09:06.772 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.Application of plug-in com.apple.dt.IDEWatchSupportUI
2023-12-04 19:09:06.772 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.watchOSSimulator.ViewDescriber of plug-in com.apple.dt.IDEWatchSupportUI
2023-12-04 19:09:06.773 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEOSXSupportUI:IDEOSXSupportUI.plugindata/plug-in[1]/extension[5] of plug-in com.apple.dt.IDE.IDEOSXSupportUI
2023-12-04 19:09:06.774 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorSlice for extension Xcode.Xcode3ProjectSupport.InfoEditorSlice.appletvos.BundleTargetInfo of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-12-04 19:09:06.774 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.tvOS.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-12-04 19:09:06.774 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.ATV.ViewDescriber of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-12-04 19:09:06.774 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.appletvos.Bundle of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-12-04 19:09:06.774 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.tvOSSimulator.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-12-04 19:09:06.774 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.IDEAppleTVSupportUI.Application of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-12-04 19:09:06.774 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEAppleTVSupportUI:IDEAppleTVSupportUI.plugindata/plug-in[1]/extension[16] of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-12-04 19:09:06.774 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.IDEAppleTVSupportUI.XPC of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-12-04 19:09:06.774 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DeviceIconProvider for extension Xcode.DebuggerFoundation.DeviceIconProvider.AppleTV of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-12-04 19:09:06.774 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.ATVSimulator.ViewDescriber of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-12-04 19:09:06.774 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.IDEAppleTVSupportUI.ExtensionKitAppExtension of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-12-04 19:09:06.774 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.IDEAppleTVSupportUI.AppExtension of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-12-04 19:09:06.774 mlaunch[45009:3219237] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.IDEAppleTVSupportUIFramework of plug-in com.apple.dt.IDEAppleTVSupportUI
2023-12-04 19:09:07.108 mlaunch[45009:3219265] .NET ThreadPool Worker DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot11/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-22235/DVTFoundation/DeveloperStructure/DVTExtendedPlatformInfo.m:90
Details:  DVTExtendedPlatformInfo: Synthesized watchos Extended Platform Info because no plugin existed to provide it or that plugin was not loaded
Object:   <DVTExtendedPlatformInfo>
Method:   +extendedPlatformInfoForPlatformIdentifier:error:
Thread:   <NSThread: 0x600003852700>{number = 6, name = (null)}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
2023-12-04 19:09:07.108 mlaunch[45009:3219265] .NET ThreadPool Worker DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot11/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-22235/DVTFoundation/DeveloperStructure/DVTExtendedPlatformInfo.m:90
Details:  DVTExtendedPlatformInfo: Synthesized iphonesimulator Extended Platform Info because no plugin existed to provide it or that plugin was not loaded
Object:   <DVTExtendedPlatformInfo>
Method:   +extendedPlatformInfoForPlatformIdentifier:error:
Thread:   <NSThread: 0x600003852700>{number = 6, name = (null)}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
2023-12-04 19:09:07.108 mlaunch[45009:3219265] .NET ThreadPool Worker DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot11/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-22235/DVTFoundation/DeveloperStructure/DVTExtendedPlatformInfo.m:90
Details:  DVTExtendedPlatformInfo: Synthesized watchsimulator Extended Platform Info because no plugin existed to provide it or that plugin was not loaded
Object:   <DVTExtendedPlatformInfo>
Method:   +extendedPlatformInfoForPlatformIdentifier:error:
Thread:   <NSThread: 0x600003852700>{number = 6, name = (null)}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
2023-12-04 19:09:07.108 mlaunch[45009:3219265] .NET ThreadPool Worker DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot11/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-22235/DVTFoundation/DeveloperStructure/DVTExtendedPlatformInfo.m:90
Details:  DVTExtendedPlatformInfo: Synthesized iphoneos Extended Platform Info because no plugin existed to provide it or that plugin was not loaded
Object:   <DVTExtendedPlatformInfo>
Method:   +extendedPlatformInfoForPlatformIdentifier:error:
Thread:   <NSThread: 0x600003852700>{number = 6, name = (null)}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
error MT0000: Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
System.Resources.MissingManifestResourceException: Could not find the resource "Xamarin.Localization.Mlaunch.MLResources.resources" among the resources "Xamarin.Bundler.Errors.resources" embedded in the assembly "Xamarin.Localization.Mlaunch", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo, Dictionary`2, Boolean, Boolean)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo, Boolean, Boolean)
   at System.Resources.ResourceManager.GetString(String, CultureInfo)
   at Xamarin.Localization.Mlaunch.MLResources.get_ML1005() in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Localization.Mlaunch/MLResources.Designer.cs:line 706
   at Xamarin.Launcher.DevController.KillApplicationAsync(String, Int32) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/controller-device.cs:line 502
   at Xamarin.Launcher.Driver.MainAsync() in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 474
   at Xamarin.Utils.NSRunLoopExtensions.RunUntilTaskCompletion[T](NSRunLoop, Task`1) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Utils/Extensions.cs:line 30
   at Xamarin.Launcher.Driver.Main2(String[]) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 436
   at Xamarin.Launcher.Driver.Main(String[]) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 123
```

### Environment

Running using the cli, listing versions manually.

<details>
<summary>Version information</summary>

```
Used rollback config from https://aka.ms/dotnet/maui/net8.0.json
Installing workload manifest microsoft.net.sdk.android version 34.0.56...
Installing workload manifest microsoft.net.sdk.ios version 17.0.8493...
Installing workload manifest microsoft.net.sdk.maccatalyst version 17.0.8493...
Installing workload manifest microsoft.net.sdk.macos version 14.0.8493...
Installing workload manifest microsoft.net.sdk.maui version 8.0.0-ci.net8.9704...
Installing workload manifest microsoft.net.sdk.tvos version 17.0.8493...
Installing workload manifest microsoft.net.workload.mono.toolchain.net7 version 8.0.0...
Installing workload manifest microsoft.net.workload.mono.toolchain.current version 8.0.0...
Installing workload manifest microsoft.net.workload.emscripten.net7 version 8.0.0...
Installing workload manifest microsoft.net.workload.emscripten.current version 8.0.0...
Installing pack Microsoft.AspNetCore.Components.WebView.Maui version 8.0.0-ci.net8.9704...

#dotnet --info from build machine (different from run machine)
.NET SDK:
 Version:           8.0.100
 Commit:            ae28d5bc06
 Workload version:  8.0.100-manifests.e7f351aa

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.6
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /Users/runner/work/1/s/CorrelationStaging/dotnet/sdk/8.0.100/

MauiVersion from Microsoft.Maui.dll: 8.0.0-ci.net8.9704+sha.6c9a26c928-azdo.8761466.6c9a26c9282bb08f432c305e534d200a11f6db3c

# Run Machine
[9.0.0-prerelease.23604.1+21ba9996823e69be83c970b43796e05d9ca174cc] XHarness command issued: apple state
Runtime Enviroment:
  Machine name:	DNCENGMAC044
  OS Name:	Mac OS X
  OS Version:	10.18
  OS Platform:	Darwin

Developer Tools:
  Xcode:	15.0 - /Applications/Xcode_15.0.app
 Mlaunch:	Xamarin.Launcher 1.0.82 (refs/heads/main: 04b71d98c8) - /private/tmp/helix/working/B9100998/p/microsoft.dotnet.xharness.cli/9.0.0-prerelease.23604.1/tools/net7.0/any/../../../runtimes/any/native/mlaunch/bin/mlaunch
```

</details>

### Build Logs

Available via Teams DM.

### Example Project (If Possible)

The main app is the default maui app, setup is done via automation in https://github.com/dotnet/performance.

**Comment by rolfbjarne** [comment]
I can reproduce; fix is in progress.
