### ISSUE TITLE
mlaunch NRE. getting real devices

### ISSUE THREAD

**Issue by rmarinho** [xamarin/xamarin-macios#19598]
### Steps to Reproduce

1. Try to run the controls device tests on real devices with the maui cake script 
2. 
3. 

### Environment

```
Apple State:       [18:57:03.9857070] error MT0000: Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
Apple State:       [18:57:04.1303550] System.NullReferenceException: Object reference not set to an instance of an object.
Apple State:       [18:57:04.1303780]    at Xamarin.Hosting.RealDevice.Connect***() in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/RealDevice.cs:line 121
Apple State:       [18:57:04.1303790]    at System.Threading.Tasks.Task.InnerInvoke()
Apple State:       [18:57:04.1303800]    at System.Threading.Tasks.Task.<>c.<.cctor>b__273_0(Object)
Apple State:       [18:57:04.1303800]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
Apple State:       [18:57:04.1303810] --- End of stack trace from previous location ---
Apple State:       [18:57:04.1303810]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
Apple State:       [18:57:04.1303820]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
Apple State:       [18:57:04.1303820] --- End of stack trace from previous location ---
Apple State:       [18:57:04.1303830]    at Xamarin.Hosting.RealDevice.IsUnlockedAsync() in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/RealDevice.cs:line 192
Apple State:       [18:57:04.1303900]    at Xamarin.Launcher.DevController.GetDeviceInfoAsync(RealDevice, Boolean) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/controller-device.cs:line 678
Apple State:       [18:57:04.1303900]    at Xamarin.Launcher.DevController.<>c__DisplayClass22_1.<<GetDevicesAsyncUsingAMDevice>b__2>d.MoveNext() in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/controller-device.cs:line 552
Apple State:       [18:57:04.1430710] Process mlaunch exited with 1
Apple State:       [18:57:04.1639860] Failed to parse device list: System.Exception: Failed to list devices.
Apple State:          at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.HardwareDeviceLoader.LoadDevices(ILog log, Boolean includeLocked, Boolean forceRefresh, Boolean listExtraData, Boolean includeWirelessDevices, Cancellation*** cancellation***) in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/HardwareDeviceLoader.cs:line 104
Apple State:       

```

**Comment by rolfbjarne** [comment]
Which version of xharness/mlaunch are you using?
