### ISSUE TITLE
Testflight build crashes on startup

### ISSUE THREAD

**Issue by MitchellFreeman** [xamarin/xamarin-macios#19860]
### Steps to Reproduce

1. Publish a build to testflight
2. Install on device
3. Open app

### Expected Behavior
The app opens.
### Actual Behavior
The app crashes immediately.

This only happens with the testflight build. A debug build runs fine, an adhoc build runs fine. We've tried fixes suggested in [this issue](https://github.com/dotnet/maui/issues/11276) but none of them work.

Without the fixes from that issue the error is:
```
Unhandled managed exception: __Internal (System.DllNotFoundException)
   at UIKit.UIApplication.UIApplicationMain(Int32 , String[] , IntPtr , IntPtr )
   at UIKit.UIApplication.Main(String[] , Type , Type )
   at Pttox.Forms.Program.Main(String[] args)
```

With the fixes (UseInterpreter true) the error becomes:
```
Unhandled Exception:
System.TypeInitializationException: TypeInitialization_Type, System.Threading.Thread
 ---> System.TypeInitializationException: TypeInitialization_Type, Sys
 ---> System.DllNotFoundException: libSystem.Native
   at Interop.Sys..cctor()
   Exception_EndOfInnerExceptionStack
   at System.Threading.Thread.GetCurrentProcessorNumber()
   at System.Threading.ProcessorIdCache.ProcessorNumberSpeedCheck()
   at System.Threading.Thread..cctor()
   Exception_EndOfInnerExceptionStack
   at System.Threading.Thread.get_CurrentThread()
   at System.Threading.Monitor.Enter(Object obj, Boolean& lockTaken)
   at System.AppContext.GetData(String name)
   at System.AppContext.TryGetSwitch(String switchName, Boolean& isEnabled)
   at System.StartupHookProvider.get_IsSupported()
   at System.StartupHookProvider.ProcessStartupHooks(String diagnosticStartupHooks)

```

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac
Version 17.6.7 (build 417)
Installation UUID: 089df5ab-181f-42c4-a22a-d9be2dbf15a2

Runtime
.NET 7.0.3 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2

Roslyn (Language Service)
4.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.311/Sdks
SDK Versions:
	8.0.100
	7.0.311
	7.0.202
	6.0.417
	6.0.407
	6.0.402
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	6.0.417
	6.0.106
	5.0.408
	3.1.426
	3.1.424
	3.1.420

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	8.0.0
	7.0.14
	7.0.4
	6.0.25
	6.0.15
	6.0.10

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	6.0.25
	6.0.6
	5.0.17
	3.1.32
	3.1.30
	3.1.26

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 13.2.2.0 (Visual Studio Community)
Commit: xamarin-android/d17-5/45b0e14
Android SDK: /Users/gitlabrunner/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.3
SDK Build Tools Version: 32.0.0

Build Information: 
Mono: d9a6e87
Java.Interop: xamarin/java.interop/d17-5@149d70fe
SQLite: xamarin/sqlite/3.40.1@68c69d8
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.6.0.50
Hash: a715dca
Branch: HEAD
Build date: 2023-11-10 12:19:52 UTC

Android Device Manager
Version: 0.0.0.1309
Hash: 06e3e77
Branch: HEAD
Build date: 2023-11-10 12:19:52 UTC

Apple Developer Tools
Xcode: 15.0.1 22266
Build: 15A507

Xamarin.Mac
Not Installed

Xamarin.iOS
Version: 16.4.0.23 Visual Studio Community
Hash: 9defd91b3
Branch: xcode14.3
Build date: 2023-10-23 16:15:00-0400

Xamarin Designer
Version: 17.6.3.9
Hash: 2648399ae8
Branch: remotes/origin/d17-6
Build date: 2023-11-10 12:19:46 UTC

Build Information
Release ID: 1706070417
Git revision: 179aa48a5702754e41a8218d0403ddc3be46706f
Build date: 2023-11-10 12:18:09+00
Build branch: release-17.6
Build lane: release-17.6

Operating System
Mac OS X 14.1.2
Darwin 23.1.0 Darwin Kernel Version 23.1.0
    Mon Oct  9 21:28:12 PDT 2023
    root:xnu-10002.41.9~6/RELEASE_ARM64_T8103 arm64


```

</details>
Note that we no longer use VS for mac and instead use VSCode.

### Build Logs

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/13983377/msbuild.binlog.zip)

**Comment by rolfbjarne** [comment]
Can you provide the .ipa you uploaded to TestFlight?

**Comment by MitchellFreeman** [comment]
> Can you provide the .ipa you uploaded to TestFlight?

Here is the ipa we uploaded:
https://drive.google.com/file/d/1Bgtvv2qPtvn0RZZiy2w3v0rUPeOkF7uy/view?usp=sharing

Additionally here is the csproj file we use:
```
<PropertyGroup>
      <nullable>enable</nullable>
      <WarningsAsErrors>nullable</WarningsAsErrors>
      <NoWarn>NU1605,CA1416</NoWarn>
      <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) or $([MSBuild]::IsOSPlatform('macOS'))">net8.0;net8.0-android;net8.0-ios;</TargetFrameworks>
      <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('linux'))">net8.0;net8.0-android;</TargetFrameworks>
      <OutputType>Exe</OutputType>
      <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">16.1</SupportedOSPlatformVersion>
      <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">28.0</SupportedOSPlatformVersion>
      <SingleProject>true</SingleProject>
      <ImplicitUsings>enable</ImplicitUsings>
      <UseMaui>true</UseMaui>
      <UseMauiEssentials>true</UseMauiEssentials>
      <ApplicationTitle>Tait PTToX</ApplicationTitle>
      <RootNamespace>Pttox.Forms</RootNamespace>
      <ApplicationId>com.taitradio.unified.pttox</ApplicationId>
      <UseNativeHttpHandler>false</UseNativeHttpHandler>
      <MauiUseDefaultAotProfile>false</MauiUseDefaultAotProfile>
   </PropertyGroup>
   <PropertyGroup Condition="$(TargetFramework) == 'net8.0'">
      <DefineConstants>$(DefineConstants);NET8_TARGET</DefineConstants>
   </PropertyGroup>
   <PropertyGroup Condition="$(TargetFramework) == 'net8.0-android'">
      <RuntimeIdentifiers>android-arm;android-arm64</RuntimeIdentifiers>
   </PropertyGroup>
   <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
      <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
      <LangVersion>11.0</LangVersion>
   </PropertyGroup>
   <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
      <LangVersion>11.0</LangVersion>
   </PropertyGroup>
   <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-ios|AnyCPU'">
     <CreatePackage>false</CreatePackage>
     <MtouchLink>None</MtouchLink>
     <MtouchExtraArgs>-v -v -v -v</MtouchExtraArgs>
     <MtouchNoSymbolStrip>true</MtouchNoSymbolStrip>
     <CodesignProvision>Automatic</CodesignProvision>
     <CodesignKey>iPhone Developer</CodesignKey>
     <CodesignEntitlements>Platforms\iOS\EntitlementsDebug.plist</CodesignEntitlements>
   </PropertyGroup>
   <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-ios|AnyCPU'">
     <CodesignKey>Apple Distribution: Tait Limited (BKZKC4ZKKF)</CodesignKey>
     <CodesignProvision>PTToX Dist</CodesignProvision>
     <CodesignEntitlements>Platforms\iOS\EntitlementsRelease.plist</CodesignEntitlements>
   </PropertyGroup>
   <PropertyGroup Condition="$(TargetFramework.Contains('-ios'))">
      <RuntimeIdentifiers>ios-arm64</RuntimeIdentifiers>
   </PropertyGroup>
   <ItemGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-ios|AnyCPU'">
      <NativeReference Include="..\..\..\iOS-PTToX\main\build\OS64\Release\libpttox-client.a" Kind="Static">
         <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </NativeReference>
   </ItemGroup>
   <ItemGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-ios|AnyCPU'">
      <NativeReference Include="..\..\..\iOS-PTToX\main\build\OS64\Debug\libpttox-client.a" Kind="Static">
         <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </NativeReference>
   </ItemGroup>
```

**Comment by rolfbjarne** [comment]
Can you try using `RuntimeIdentifier` (singular) instead of `RuntimeIdentifiers` (plural) and see if that works?

```xml
<PropertyGroup Condition="$(TargetFramework.Contains('-ios'))">
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
</PropertyGroup>
```

**Comment by MitchellFreeman** [comment]
Yes that has fixed it.

**Comment by rolfbjarne** [comment]
Great! A fix is in progress, and hopefully we'll be able to release it in an upcoming service release.
