### ISSUE TITLE
Task assemblies can mismatch between .NET versions

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#20062]
Ref: https://discord.com/channels/732297728826277939/732297808148824115/1205082594757054494

```

Filip Navara — Today at 10:27 AM

    88>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\tools\msbuild\iOS\Xamarin.Shared.targets(546,3): error MSB4018: The "CompileAppManifest" task failed unexpectedly.
    88>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\tools\msbuild\iOS\Xamarin.Shared.targets(546,3): error MSB4018: System.MissingMethodException: Method not found: 'System.String Xamarin.Localization.MSBuild.MSBStrings.get_W7108()'.
    88>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\tools\msbuild\iOS\Xamarin.Shared.targets(546,3): error MSB4018:    at Xamarin.MacDev.Tasks.CompileAppManifestTaskBase.Execute()
    88>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\tools\msbuild\iOS\Xamarin.Shared.targets(546,3): error MSB4018:    at Xamarin.MacDev.Tasks.CompileAppManifest.Execute() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/CompileAppManifest.cs:line 16
    88>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\tools\msbuild\iOS\Xamarin.Shared.targets(546,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
    88>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\tools\msbuild\iOS\Xamarin.Shared.targets(546,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
    
    does this ring any bells? .NET 8.0.200-preview.23624.5 SDK, VS 17.9.0 Preview 4.0
    (I know it's a "missing file" error, not really asking about the underlying cause, just the localization bundling issue)

Rolf — Today at 10:31 AM

    that's weird, W7108 is in the initial .NET 8 release
    is this a .NET 7 project?
    or are there .NET 7 projects in the solution?

Filip Navara — Today at 10:32 AM

    It was .NET 7 project and I bumped it to .NET 8.
    There are other .NET 7 projects in the solution, possibly even some iOS library projects
    so yeah, it would make sense that it can collide within the same VS instance

Filip Navara — Today at 10:40 AM

    yep, goes away if I retarget everything and restart VS
    (in fact, even the build error goes away)
```

See also https://github.com/xamarin/xamarin-macios/issues/9835, where a fix was attempted (but apparently not enough).

**Comment by rolfbjarne** [comment]
Also internally: https://teams.microsoft.com/l/message/19:53507cb282f14829aff9c6bd9ef183ad@thread.v2/1716290507008?context=%7B%22contextType%22%3A%22chat%22%7D

> The "FindItemWithLogicalName" task failed unexpectedly.System.MissingMethodException: Method not found: 'System.String Xamarin.Localization.MSBuild.MSBStrings.get_M0149b()'.   at Xamarin.MacDev.Tasks.FindItemWithLogicalName.Execute()   at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
