### ISSUE TITLE
`MessagingException` while trying to build for Simulator

### ISSUE THREAD

**Issue by MartinZikmund** [xamarin/xamarin-macios#21092]
### Apple platform

iOS

### Framework version

net8.0-*

### Affected platform version

Visual Studio 17.11.1

### Description

Seems quite similar to https://github.com/xamarin/xamarin-macios/issues/21005, but the `ArgumentNullException` happens with ILLink instead.

When trying to build and run a simple iOS app (Blank app based on Uno Platform) on Remote Mac Simulator connected to VS, the build fails with:

```
MessagingException: An error occurred on client build7468871940Marti while executing a post for topic xvs/build/17.11.0.94/execute-task/UnoApp35/6ceb41e002fILLink
ArgumentNullException: Object cannot be null.
Parameter name: source
```

```
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning : [xma][err]: An exception occurred in the task 'ILLink'
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning : An error occurred on client build7468871940Marti while executing a post for topic xvs/build/17.11.0.94/execute-task/UnoApp35/6ceb41e002fILLink
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at Xamarin.Messaging.Client.MessagingClient.<PostAsync>d__21`2.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Client\MessagingClient.cs:line 247
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning : --- End of stack trace from previous location where exception was thrown ---
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at Xamarin.Messaging.Ssh.MessagingRunnerPro.<ExecuteWithRetryAsync>d__13`1.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Ssh\MessagingRunnerPro.cs:line 57
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning : --- End of stack trace from previous location where exception was thrown ---
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at Xamarin.Messaging.Ssh.MessagingRunnerPro.ThrowIfConnected(ExceptionDispatchInfo exceptionInfo, IMessagingAnalyticsAction analytics) in D:\a\_work\1\s\src\Xamarin.Messaging.Ssh\MessagingRunnerPro.cs:line 151
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at Xamarin.Messaging.Ssh.MessagingRunnerPro.<HandleExceptionAsync>d__15`1.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Ssh\MessagingRunnerPro.cs:line 99
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning : --- End of stack trace from previous location where exception was thrown ---
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at Xamarin.Messaging.Ssh.MessagingRunnerPro.<ExecuteWithRetryAsync>d__13`1.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Ssh\MessagingRunnerPro.cs:line 64
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning : --- End of stack trace from previous location where exception was thrown ---
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at Xamarin.Messaging.Ssh.MessagingRunnerPro.<ExecuteWithRetryAsync>d__11`1.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Ssh\MessagingRunnerPro.cs:line 39
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning : --- End of stack trace from previous location where exception was thrown ---
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at Xamarin.Messaging.Ssh.MessagingClientPro.<PostAsync>d__26`2.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Ssh\MessagingClientPro.cs:line 144
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning : --- End of stack trace from previous location where exception was thrown ---
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at Xamarin.Messaging.Build.Client.BuildClient.<RunMessagingAsync>d__34`2.MoveNext() in D:\a\_work\1\s\src\MSBuild\Xamarin.Messaging.Build.Client\BuildClient.cs:line 302
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning : --- End of stack trace from previous location where exception was thrown ---
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at Xamarin.Messaging.Build.Client.BuildClient.<ExecuteTaskAsync>d__20.MoveNext() in D:\a\_work\1\s\src\MSBuild\Xamarin.Messaging.Build.Client\BuildClient.cs:line 65
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning : --- End of stack trace from previous location where exception was thrown ---
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning :    at Xamarin.Messaging.Build.Client.TaskRunner.<RunAsync>d__6.MoveNext() in D:\a\_work\1\s\src\MSBuild\Xamarin.Messaging.Build.Client\TaskRunner.cs:line 56
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): error : MessagingException: An error occurred on client build7468871940Marti while executing a post for topic xvs/build/17.11.0.94/execute-task/UnoApp35/6ceb41e002fILLink
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): error : ArgumentNullException: Object cannot be null.
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): error : Parameter name: source
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): error : 
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(406,3): error MSB3371: The file "obj\Debug\net8.0-ios\iossimulator-x64\linked\Link.semaphore" cannot be created. Could not find a part of the path 'D:\Throwaway\UnoApp35\UnoApp35\obj\Debug\net8.0-ios\iossimulator-x64\linked\Link.semaphore'.
```

### Steps to Reproduce

1. Clone https://github.com/MartinZikmund/repro-xamarin-macios-21092
2. Open the .sln and select `net8.0-ios` target
3. Connect to a remote Mac
4. Select a iOS Simulator
5. Try to build and run the app

I was building against .NET 8.0.400, iPhone 15 Plus iOS 17.5 as Simulator target. I have hit this issue with both a Apple M2 Mac Studio and Intel-based MacBook.

### Did you find any workaround?

- Seems the build works with Visual Studio 2022 17.12.0 Preview 1.0 - both against .NET 8 stable and .NET 9 Preview

### Build logs

[binlog.zip](https://github.com/user-attachments/files/16706636/binlog.zip)

**Comment by MartinZikmund** [comment]
I was now able to get Visual Studio 2022 17.12.0 Preview 1.0 to break as well when building against M2 Mac with the following:

```
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning : [xma][err]: An exception occurred in the task 'GetDirectories'
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning : The post for client build4543688320Marti on topic xvs/build/17.12.0.40/execute-task/UnoApp35/2d43edf002fGetDirectories has been cancelled
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at Xamarin.Messaging.Client.MessagingClient.<PostAsync>d__21`2.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Client\MessagingClient.cs:line 231
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning : --- End of stack trace from previous location where exception was thrown ---
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at Xamarin.Messaging.Ssh.MessagingRunnerPro.<ExecuteWithRetryAsync>d__13`1.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Ssh\MessagingRunnerPro.cs:line 57
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning : --- End of stack trace from previous location where exception was thrown ---
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at Xamarin.Messaging.Ssh.MessagingRunnerPro.ThrowIfConnected(ExceptionDispatchInfo exceptionInfo, IMessagingAnalyticsAction analytics) in D:\a\_work\1\s\src\Xamarin.Messaging.Ssh\MessagingRunnerPro.cs:line 151
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at Xamarin.Messaging.Ssh.MessagingRunnerPro.<HandleExceptionAsync>d__15`1.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Ssh\MessagingRunnerPro.cs:line 99
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning : --- End of stack trace from previous location where exception was thrown ---
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at Xamarin.Messaging.Ssh.MessagingRunnerPro.<ExecuteWithRetryAsync>d__13`1.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Ssh\MessagingRunnerPro.cs:line 64
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning : --- End of stack trace from previous location where exception was thrown ---
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at Xamarin.Messaging.Ssh.MessagingRunnerPro.<ExecuteWithRetryAsync>d__11`1.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Ssh\MessagingRunnerPro.cs:line 39
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning : --- End of stack trace from previous location where exception was thrown ---
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at Xamarin.Messaging.Ssh.MessagingClientPro.<PostAsync>d__26`2.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Ssh\MessagingClientPro.cs:line 144
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning : --- End of stack trace from previous location where exception was thrown ---
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at Xamarin.Messaging.Build.Client.BuildClient.<RunMessagingAsync>d__34`2.MoveNext() in D:\a\_work\1\s\src\MSBuild\Xamarin.Messaging.Build.Client\BuildClient.cs:line 302
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning : --- End of stack trace from previous location where exception was thrown ---
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at Xamarin.Messaging.Build.Client.BuildClient.<ExecuteTaskAsync>d__20.MoveNext() in D:\a\_work\1\s\src\MSBuild\Xamarin.Messaging.Build.Client\BuildClient.cs:line 65
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning : --- End of stack trace from previous location where exception was thrown ---
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): warning :    at Xamarin.Messaging.Build.Client.TaskRunner.<RunAsync>d__6.MoveNext() in D:\a\_work\1\s\src\MSBuild\Xamarin.Messaging.Build.Client\TaskRunner.cs:line 56
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): error : MessagingException: The post for client build4543688320Marti on topic xvs/build/17.12.0.40/execute-task/UnoApp35/2d43edf002fGetDirectories has been cancelled
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): error : OperationCanceledException: The operation was canceled.
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\tools\msbuild\iOS\Xamarin.Shared.targets(377,3): error :
```

**Comment by MartinZikmund** [comment]
I have created https://developercommunity.visualstudio.com/t/ArgumentNullException-while-executing-a/10723723 with the issue details
