### ISSUE TITLE
[iOS 17.0.8523 - VS 17.11] Remote builds fail with null ref exception

### ISSUE THREAD

**Issue by emaf** [xamarin/xamarin-macios#21199]
### Apple platform

iOS

### Framework version

net8.0-*

### Affected platform version

VS 17.11- net8.0-ios17.0 - iOS 17.0.8523

### Description

Building remotely a new MAUI app targeting net8.0-ios17.0 fails with the following error:

```
The "Copy" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xamarin.Messaging.Build.Client.TaskRunner.FixReferencedItems(ITaskItem[] items) in D:\a\_work\1\s\src\MSBuild\Xamarin.Messaging.Build.Client\TaskRunner.cs:line 237
   at Microsoft.Build.Tasks.Copy.Execute() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/Copy.cs:line 12
   at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

### Steps to Reproduce

1. Create a new MAUI app using VS 17.11 and target net8.0
2. Change the project to target `net8.0-ios17.0`
3. Connect to a Mac
4. Select a simulator
5. Try to run for debugging

### Build logs

[binlog.zip](https://github.com/user-attachments/files/16913868/binlog.zip)

**Comment by emaf** [comment]
@rolfbjarne it seems the 17.0 version we are shipping in VS 17.11 (stable) is missing at least https://github.com/xamarin/xamarin-macios/commit/a4ec504211b43f170ed1b41e106a5af9a0adf0da, but there could be some other important fixes missing there?

**Comment by emaf** [comment]
This comes from https://developercommunity.visualstudio.com/t/ArgumentNullException-while-executing-a-/10723723, so customers are trying to use 17.0.

What if the library is built remotely?
