### ISSUE TITLE
iOS MAUI app unable to debug in VS code for MAC on a physical device

### ISSUE THREAD

**Issue by vaibhav-sukhdeve** [xamarin/xamarin-macios#21672]
While deploying the MAUI application on a physical device it is getting deployed successfully.
But I am unable to debug the application or I can say that the breakpoints are not hitting. 
And no logs are visible in the debug console. 
Please check the following log:

`/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net9.0_18.0/18.0.9617/tools/bin/mlaunch
error MT0000: Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
error MT0000: Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
System.NotSupportedException: Specified method is not supported.
System.NotSupportedException: Specified method is not supported.
at Xamarin.Hosting.DeviceCtlDevice.CreateTcpTunnel(LaunchConfig) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/DeviceCtlDevice.cs:line 79
at Xamarin.Hosting.DeviceCtlDevice.CreateTcpTunnel(LaunchConfig) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/DeviceCtlDevice.cs:line 79
at Xamarin.Launcher.DevController.CreateTcpTunnel(String, LaunchConfig) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/controller-device.cs:line 844
at Xamarin.Launcher.DevController.CreateTcpTunnel(String, LaunchConfig) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/controller-device.cs:line 844
at Xamarin.Launcher.Driver.MainAsync() in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 536
at Xamarin.Launcher.Driver.MainAsync() in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 536
at Xamarin.Utils.NSRunLoopExtensions.RunUntilTaskCompletion[T](NSRunLoop, Task`1) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Utils/Extensions.cs:line 30
at Xamarin.Utils.NSRunLoopExtensions.RunUntilTaskCompletion[T](NSRunLoop, Task`1) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Utils/Extensions.cs:line 30
at Xamarin.Launcher.Driver.Main2(String[]) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 443
at Xamarin.Launcher.Driver.Main2(String[]) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 443
at Xamarin.Launcher.Driver.Main(String[]) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 130
at Xamarin.Launcher.Driver.Main(String[]) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 130
`

**Comment by rolfbjarne** [comment]
This is a duplicate of #21664.
