### ISSUE TITLE
Exception deploying app on device

### ISSUE THREAD

**Issue by softlion** [xamarin/xamarin-macios#4930]
### Steps to Reproduce

1.  Create xamarin forms app from VS windows (stable)
2.  debug F5 on device

### Expected Behavior
Deploys fine

### Actual Behavior

Crashes (at least on first deployment)

Message in debug window: "the app has been terminated.The app has been terminated."

```Xamarin.VisualStudio.IOS.MonoTouchFlavoredProject|Error|0|An error occurred while lauching Application for debugging
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xamarin.VisualStudio.IOS.MonoTouchFlavoredProject.ProjectContainsOnDemandResources() in E:\A\_work\157\s\src\Core\VisualStudio.IOS\ProjectSystem\MonoTouchFlavoredProject.cs:line 1465
   at Xamarin.VisualStudio.IOS.MonoTouchFlavoredProject.GetRunSessionInfo(MonoTouchDevice device) in E:\A\_work\157\s\src\Core\VisualStudio.IOS\ProjectSystem\MonoTouchFlavoredProject.cs:line 1287
   at Xamarin.VisualStudio.IOS.MonoTouchFlavoredProject.CreateDebuggerStartInfo(MonoTouchDevice device, Int32 debugPort) in E:\A\_work\157\s\src\Core\VisualStudio.IOS\ProjectSystem\MonoTouchFlavoredProject.cs:line 1107
   at Xamarin.VisualStudio.IOS.MonoTouchFlavoredProject.StartDebugging(MonoTouchDevice device, IProgressReport progress, MonoDebuggerLauncher debug_session) in E:\A\_work\157\s\src\Core\VisualStudio.IOS\ProjectSystem\MonoTouchFlavoredProject.cs:line 1182
   at Xamarin.VisualStudio.IOS.MonoTouchFlavoredProject.<>c__DisplayClass94_0.<DebugApplication>b__0() in E:\A\_work\157\s\src\Core\VisualStudio.IOS\ProjectSystem\MonoTouchFlavoredProject.cs:line 1157
```

### Environment

Xcode 10 / VS2017

```
Microsoft Visual Studio Enterprise 2017 
Version 15.8.6
VisualStudio.15.Release/15.8.6+28010.2041
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise

Architecture Diagrams and Analysis Tools   00369-90000-00000-AA445
Microsoft Architecture Diagrams and Analysis Tools

Visual C++ 2017   00369-90000-00000-AA445
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.8.05085.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60618.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.8.05023.0
Azure App Service Tools v3.0.0

C# Tools   2.9.0-beta8-63208-01
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 2018.2.3   Build 182.0.20180912.70621
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2018 JetBrains, Inc.

JustDecompilePackage2017 Extension   1.0
JustDecompilePackage2017 Visual Studio Extension Detailed Info

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

Mono Debugging for Visual Studio   4.11.11-pre (8fb558f)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

NuGet PackageReference Upgrader   1.0
A VS2017 Extension that helps legacy apps migrate off of packages.config. 

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   15.8.18241.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - IronPython support   15.8.18241.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   15.8.18241.1
Profiling support for Python projects.

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResXManager   1.24.1179.0
Manage localization of all ResX-Based resources in one place. Shows all resources of a solution and let's you edit the strings and their localizations in a well-arranged data grid.

SQL Server Data Tools   15.1.61808.07020
Microsoft SQL Server Data Tools

TypeScript Tools   15.8.20822.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.9.0-beta8-63208-01
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 55a3dc3231c95c77f81ee53f7d29152029da7408.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Universal Windows Apps   15.0.28010.2041
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

WiX Toolset Visual Studio Extension   0.9.21.62588
WiX Toolset Visual Studio Extension version 0.9.21.62588
Copyright (c) .NET Foundation and contributors. All rights reserved.

Xamaridea.VisualStudioPlugin   1.0
VS + Xamarin + IDEA = Love

Xamarin   4.11.0.776 (d15-8@1ae9b59d7)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.15.9 (d000f568b)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.116 (9619170)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.0.0.19 (HEAD/a8a3b0ec7)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.0.0.15 (84552a4)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

> VS bug [#697751](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/697751)

**Comment by dfoulk** [comment]
@softlion were you able to run this app in Debug mode after receiving this error? I am getting this error and cannot seem to get it to run at all. Any insight would be greatly appreciated.

**Comment by softlion** [comment]
I switched on vs mac

**Comment by emaf** [comment]
This problem is already fixed in the latest stable version of Visual Studio. You can download it from https://visualstudio.microsoft.com/downloads.

Thanks!

**Comment by softlion** [comment]
2018 lol
