### ISSUE TITLE
Start Debugging sometimes only builds and does not start

### ISSUE THREAD

**Issue by rihadavid** [xamarin/xamarin-macios#5098]
### Steps to Reproduce

1. I just click Start Debugging
2. Sometimes it only builds but fails to start

### Environment

I am using Xcode 10.1 on macOS 10.13.6 inside VMware Workstation 14.1.2, testing on iPhone 5S iOS 12.1 simulator.

Note that I also have many other issues with Mac Agent stability and maybe some of them might be related, I will try to report them all individually.

```
Microsoft Visual Studio Community 2017 
Version 15.8.9
VisualStudio.15.Release/15.8.9+28010.2050
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

ASP.NET and Web Tools 2017   15.8.05085.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

AWS Toolkit for Visual Studio 2017   1.14.4.1
AWS Toolkit for Visual Studio 2017.
Copyright 2011-2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Release notes: https://aws-vs-toolkit.s3.amazonaws.com/versioninfo.html

This software includes third party software subject to the following copyrights:
- Logging from log4net, Apache License 
  [http://logging.apache.org/log4net/license.html]
- Putty for PPK to PEM conversion, MIT license 
  [http://www.chiark.greenend.org.uk/~sgtatham/putty/licence.html]
- NGit for AWS Elastic Beanstalk incremental push
  [https://github.com/mono/ngit/blob/master/NGit.license.txt]
- NSch dependency for NGit
  [https://github.com/mono/ngit/blob/master/NSch.license.txt]
- Sharpen dependency for NGit
  [https://github.com/mono/ngit/blob/master/Sharpen/AssemblyInfo.cs]
- ICSharpCode.SharpZipLib dependency for NGit
  [http://www.icsharpcode.net/opensource/sharpziplib/]
- Mono.Posix.dll and Mono.Security.dll dependencies for NGit
  [http://mono-project.com/FAQ:_Licensing#Licensing]
- MPFProj for Visual Studio Project Framework
  [http://mpfproj10.codeplex.com/license]
- JSON Checker for JSON validation
  [http://www.raboof.com/projects/jsonchecker/]
- Newtonsoft Json.NET
  [http://www.newtonsoft.com/json] 
- YamlDotNet
  [http://aaubry.net/pages/yamldotnet.html] 
    

C# Tools   2.9.0-beta8-63208-01
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   4.11.11-pre (8fb558f)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Visual Basic Tools   2.9.0-beta8-63208-01
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 55a3dc3231c95c77f81ee53f7d29152029da7408.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.11.0.779 (d15-8@ff915e800)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.15.12 (d7ff6f39c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.118 (4217ee9)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.0.0.19 (HEAD/a8a3b0ec7)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.1.0.15 (cbfb047)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Build Logs

build output:
```
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
Build started.
Project "MyApp.iOS.csproj" (GetAppBundleDir target(s)):
Done building project "MyApp.iOS.csproj".
Build succeeded.
```

xamarin log:
```
System.Net.Mqtt.Sdk.MqttClientImpl|Information|0|Client vs18536David - An application message for topic xvs/idb/4.11.0.779/simulators-changed was received
Xamarin.VisualStudio.IOS.MonoTouchFlavoredProject|Information|0|Beginning build for D:\Dokumenty-D\aplikace\MyApp\MyApp.iOS\MyApp.iOS.csproj. Properties: DeviceSpecificBuild: false, TargetiOSDevice: , ServerPort: 50196, ServerUser: User, ContinueOnDisconnected: False, ServerAddress: 192.168.189.128
System.Net.Mqtt.Sdk.ClientPacketListener|Information|0|Client vs18536David - Dispatching Publish message to flow PublishReceiverFlow and topic xma/client-status
System.Net.Mqtt.Sdk.MqttClientImpl|Information|0|Client vs18536David - An application message for topic xma/client-status was received
System.Net.Mqtt.Sdk.ClientPacketListener|Warning|0|Client vs18536David - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener|Information|0|Client vs18536David - Dispatching PingResponse message to flow PingFlow
System.Net.Mqtt.Sdk.ClientPacketListener|Warning|0|Client vs18536David - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener|Information|0|Client vs18536David - Dispatching PingResponse message to flow PingFlow
Mono.Debugging.VisualStudio.DebugLauncher|Error|0|Controller.Launch ()
Xamarin.VisualStudio.IOS.MonoTouchFlavoredProject|Error|0|An error occurred while lauching Application for debugging
System.Runtime.InteropServices.COMException (0x89710016): Unable to start program 'Mono'.

General Exception
   at Microsoft.VisualStudio.Shell.Interop.IVsDebugger4.LaunchDebugTargets4(UInt32 DebugTargetCount, VsDebugTargetInfo4[] pDebugTargets, VsDebugTargetProcessInfo[] pLaunchResults)
   at Mono.Debugging.VisualStudio.DebugLauncher.StartDebugger(SoftDebuggerSession session, StartInfo startInfo) in E:\A\_work\445\s\src\Debugging.VisualStudio\DebugLauncher.cs:line 49
   at Mono.Debugging.VisualStudio.MonoDebuggerLauncher.StartSession(StartInfo startInfo, SoftDebuggerSession session) in E:\A\_work\445\s\src\Debugging.VisualStudio\MonoDebuggerLauncher.cs:line 29
   at Xamarin.VisualStudio.IOS.MonoTouchFlavoredProject.StartDebugging(MonoTouchDevice device, IProgressReport progress, MonoDebuggerLauncher debug_session) in E:\A\_work\675\s\src\Core\VisualStudio.IOS\ProjectSystem\MonoTouchFlavoredProject.cs:line 1189
   at Xamarin.VisualStudio.IOS.MonoTouchFlavoredProject.<>c__DisplayClass94_0.<DebugApplication>b__0() in E:\A\_work\675\s\src\Core\VisualStudio.IOS\ProjectSystem\MonoTouchFlavoredProject.cs:line 1157
System.Net.Mqtt.Sdk.ClientPacketListener|Warning|0|Client vs18536David - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener|Information|0|Client vs18536David - Dispatching PingResponse message to flow PingFlow
```

trying again:

build output
```
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
Project "MyApp.iOS.csproj" (GetAppBundleDir target(s)):
Done building project "MyApp.iOS.csproj".
Launching...
etc.
```

and it works, starts debugging

> VS bug [#725500](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/725500)

**Comment by rihadavid** [comment]
Another situation (that I think does not deserve a new issue) is sometimes happening when deploying to iPhone 5S device.

I just Start Debugging, the app builds and deploys to device, but the debugger stops before the app launches and on the iPhone, I only have the launch screen, the app never starts.
I only have a single sencente in Debug output: `The app has been terminated.`

In Xamarin log file, I have this:
(notice the `xvs/idb/4.11.0.779/app-terminated`)
```
...
System.Net.Mqtt.Sdk.ClientPacketListener|Information|0|Client vs25364David - Dispatching Publish message to flow PublishReceiverFlow and topic xvs/idb/4.11.0.779/output
System.Net.Mqtt.Sdk.MqttClientImpl|Information|0|Client vs25364David - An application message for topic xvs/idb/4.11.0.779/output was received
System.Net.Mqtt.Sdk.ClientPacketListener|Information|0|Client vs25364David - Dispatching Publish message to flow PublishReceiverFlow and topic vs25364David/response/xvs/idb/4.11.0.779/launch-app
System.Net.Mqtt.Sdk.MqttClientImpl|Information|0|Client vs25364David - An application message for topic vs25364David/response/xvs/idb/4.11.0.779/launch-app was received
System.Net.Mqtt.Sdk.ClientPacketListener|Information|0|Client vs25364David - Dispatching Publish message to flow PublishReceiverFlow and topic xvs/idb/4.11.0.779/app-terminated
System.Net.Mqtt.Sdk.MqttClientImpl|Information|0|Client vs25364David - An application message for topic xvs/idb/4.11.0.779/app-terminated was received
System.Net.Mqtt.Sdk.ClientPacketListener|Warning|0|Client vs25364David - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener|Information|0|Client vs25364David - Dispatching PingResponse message to flow PingFlow
```

**Comment by rihadavid** [comment]
Unfortunately, those bugs seem very random and I can't find specific conditions to reproduce it.

Today I have another similar bug, I built the project and deploying failed again, but this time it is failing constantly, clicking on 'Start Debugging' is just doing nothing. The error I see in the log file this time is this:
```
Xamarin.VisualStudio.IOS.MonoTouchFlavoredProject|Error|0|An error occurred while lauching Application for debugging
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xamarin.VisualStudio.IOS.MonoTouchFlavoredProject.ProjectContainsOnDemandResources() in E:\A\_work\675\s\src\Core\VisualStudio.IOS\ProjectSystem\MonoTouchFlavoredProject.cs:line 1465
   at Xamarin.VisualStudio.IOS.MonoTouchFlavoredProject.GetRunSessionInfo(MonoTouchDevice device) in E:\A\_work\675\s\src\Core\VisualStudio.IOS\ProjectSystem\MonoTouchFlavoredProject.cs:line 1287
   at Xamarin.VisualStudio.IOS.MonoTouchFlavoredProject.CreateDebuggerStartInfo(MonoTouchDevice device, Int32 debugPort) in E:\A\_work\675\s\src\Core\VisualStudio.IOS\ProjectSystem\MonoTouchFlavoredProject.cs:line 1107
   at Xamarin.VisualStudio.IOS.MonoTouchFlavoredProject.StartDebugging(MonoTouchDevice device, IProgressReport progress, MonoDebuggerLauncher debug_session) in E:\A\_work\675\s\src\Core\VisualStudio.IOS\ProjectSystem\MonoTouchFlavoredProject.cs:line 1182
   at Xamarin.VisualStudio.IOS.MonoTouchFlavoredProject.<>c__DisplayClass94_0.<DebugApplication>b__0() in E:\A\_work\675\s\src\Core\VisualStudio.IOS\ProjectSystem\MonoTouchFlavoredProject.cs:line 1157
```
Before I tried to deploy to the simulator, I tried to start debugging in "Any CPU" configuration by mistake, if that's relevant.
This seems to be an even worse bug because reconnecting the mac agent or cleaning the project and rebuilding is not helping, I will need to figure out how to fix this (maybe restarting VS or cleaning Xamarin cache files will help) or I am stuck..
Full log here: 
[2018-11-10_08-54-06.10308.Ide.log](https://github.com/xamarin/xamarin-macios/files/2568747/2018-11-10_08-54-06.10308.Ide.log)

As I said, I get many bugs with the mac agent and they seem to be quite random. I hope you can find some ways to fix it..

VS on Mac:
```
Visual Studio Community 2017 for Mac
Version 7.6.11 (build 9)
Installation UUID: 9ca1abe7-219c-4c1f-a6c1-6945692a176c
Runtime:
	Mono 5.12.0.309 (2018-02/39d89a335c8) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000309

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 10.1 (14460.46)
Build 10B61

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 12.1.0.15 (Visual Studio Community)
Hash: cbfb047a
Branch: xcode10.1
Build date: 2018-10-30 22:57:23-0400

Xamarin.Android
Not Installed

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 706110009
Git revision: d7cd66f5e3acd3d46ba0b94a0c935378f828bde0
Build date: 2018-10-31 17:17:12+00
Build branch: release-7.6
Xamarin extensions: bc9b985bfcb480b04a208a6d4045adc443a07857

Operating System
Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

Enabled user installed extensions
Internet of Things (IoT) development (Preview) 7.1
```

**Comment by dalexsoto** [comment]
Thank you for your information, I will let the Visual Studio team take over.

**Comment by dfoulk** [comment]
I am seeing the same error as @rihadavid (and experiencing the same symptoms). We are completely unable to debug our Xamarin.iOS project in Visual Studio 2017.

## Exception (*.Ide.log)

```
Xamarin.VisualStudio.IOS.MonoTouchFlavoredProject|Error|0|An error occurred while lauching Application for debugging
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xamarin.VisualStudio.IOS.MonoTouchFlavoredProject.ProjectContainsOnDemandResources() in E:\A\_work\39\s\src\Core\VisualStudio.IOS\ProjectSystem\MonoTouchFlavoredProject.cs:line 1468
   at Xamarin.VisualStudio.IOS.MonoTouchFlavoredProject.GetRunSessionInfo(MonoTouchDevice device) in E:\A\_work\39\s\src\Core\VisualStudio.IOS\ProjectSystem\MonoTouchFlavoredProject.cs:line 1290
   at Xamarin.VisualStudio.IOS.MonoTouchFlavoredProject.CreateDebuggerStartInfo(MonoTouchDevice device, Int32 debugPort) in E:\A\_work\39\s\src\Core\VisualStudio.IOS\ProjectSystem\MonoTouchFlavoredProject.cs:line 1110
   at Xamarin.VisualStudio.IOS.MonoTouchFlavoredProject.StartDebugging(MonoTouchDevice device, IProgressReport progress, MonoDebuggerLauncher debug_session) in E:\A\_work\39\s\src\Core\VisualStudio.IOS\ProjectSystem\MonoTouchFlavoredProject.cs:line 1185
   at Xamarin.VisualStudio.IOS.MonoTouchFlavoredProject.<>c__DisplayClass94_0.<DebugApplication>b__0() in E:\A\_work\39\s\src\Core\VisualStudio.IOS\ProjectSystem\MonoTouchFlavoredProject.cs:line 1160
```

This is really bad. We are completely unable to debug our Xamarin.iOS app. Does anyone from Microsoft have a workaround for us? Anything would help!

## Environment

```
Microsoft Visual Studio Professional 2017 
Version 15.9.3
VisualStudio.15.Release/15.9.3+28307.145
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Professional

Visual C++ 2017   00370-20004-74785-AA071
Microsoft Visual C++ 2017

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60913.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.9.03024.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.5001.7
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   15.9.02046.0
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.3.5001.7
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Extensibility Tools   1.10.211
Contains numerous tools and helpers that makes it easier than ever to build Visual Studio extensions.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitFlow.VS.Extension   1.0
Visual Studio extension that integrates GitFlow

GitHub.VisualStudio   2.6.1.6227
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Infragistics.VSExtension   1.0
Infragistics Visual Studio Extension (AddIn) adds scheduled check for update functionality to your Visual Studio IDE. It also provides some fast shortcuts to infragistics products and online resources.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

IntelliCode Extension   1.0
IntelliCode Extension

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

JetBrains ReSharper Ultimate 2018.2.3   Build 182.0.20180912.70621
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2019 JetBrains, Inc.

Microsoft Azure HDInsight Azure Node   2.3.5001.7
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.5001.7
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.4
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.5001.7
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10730.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

Mono Debugging for Visual Studio   4.13.11-pre (400cfb1)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.4.21001.1 Commit Hash:8dd15923800d931b153ab9e4de74e42a74eba5e6
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Open in Sublime Text   1.1.30
Adds a menu command that lets you open any solution, project, folder and file in Sublime Text.

PowerShell Pro Tools for Visual Studio   1.0
A set of tools for developing and debugging PowerShell scripts and modules in Visual Studio.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Sandcastle Help File Builder   SHFB
Visual Studio integration for the Sandcastle Help File Builder.
https://GitHub.com/EWSoftware/SHFB

SQL Server Data Tools   15.1.61810.11040
Microsoft SQL Server Data Tools

SQL Server Reporting Services   15.0.900.163
Microsoft SQL Server Reporting Services Designers 
Version 15.0.900.163

SQLite & SQL Server Compact Toolbox   4.7
SQLite & SQL Server Compact Toolbox adds scripting, import, export, rename, query execution and much more to SQL Server Compact & SQLite Data Connections.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   15.9.20918.2001
TypeScript Tools for Microsoft Visual Studio

VersionManagerToolWindow Extension   1.0
VersionManagerToolWindow Visual Studio Extension Detailed Info

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Universal Windows Apps   15.0.28301.59
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.12.3.73 (d15-9@20b35b881)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.5 (6b9f32067)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.127 (e975299)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.0.38 (HEAD/61d16aa23)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.2.1.11 (5ef73d3)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

**Comment by dfoulk** [comment]
@rihadavid Thank you for the reply! I'll try that. Much appreciated!
