### ISSUE TITLE
iOS designer in visual studio 15.9.0

### ISSUE THREAD

**Issue by jorisvergeer** [xamarin/xamarin-macios#5127]
### Steps to Reproduce

1. Install Xamarin + Visual studion 15.9 (verry fresh version)
2. Connect to an mac
2. Try to open iOS designer (I used a storyboard file)

### Expected Behavior
The designer opens and I an edit

### Actual Behavior
![image](https://user-images.githubusercontent.com/1906639/48479707-6532a380-e808-11e8-9da4-77faa2d06edf.png)

### Environment
Microsoft Visual Studio Professional 2017 
Version 15.9.0
VisualStudio.15.Release/15.9.0+28307.53
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Professional

Visual C++ 2017   00369-60000-00001-AA405
Microsoft Visual C++ 2017

.NET Portability Analyzer   1.1.10808.0
Evaluates portability of assemblies across .NET platforms.

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

AnkhSVN - Subversion Support for Visual Studio   2.7.12815.35086
AnkhSVN - Subversion Support for Visual Studio 2.7.12815.35086 
 * Ankh.Package 2.7.12815.35086
 * Subversion 1.9.5 via SharpSvn 1.9005.3940.224
 * Git/LibGit2 0.24.0 via SharpGit 0.2401.1116.230

SharpSvn is linked to: Apr 1.5.2, Apr-util 1.5.4, Cyrus Sasl 2.1.26, eXpat 2.2.0, LibSSH2 1.8.0, OpenSSL 1.0.2k  26 Jan 2017, Serf 1.3.9, SQLite 3.17.0, Subversion 1.9.5-SharpSvn, Utf8proc 1.1.5, ZLib 1.2.8
SharpSvn is optionally linked to: Berkeley DB 4.4.20, SharpPlink 0.67.0(SharpSvn)

SharpGit is linked to: Apr 1.5.1, Apr-Util 1.5.4, eXpat 2.1.0, Libgit2 0.24.0, LibSSH2 1.7.0, OpenSSL 1.0.2h  3 May 2016, Subversion 1.9.3, Utf8proc 1.1.5, ZLib 1.2.8

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

ASP.NET Core Blazor Language Services   0.5.1-rtm-10384

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60913.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.9.03024.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.5001.4
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   15.9.02046.0
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.3.5001.4
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   15.9.18254.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Microsoft Azure HDInsight Azure Node   2.3.5001.4
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.5001.4
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.4
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.5001.4
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10730.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

Mono Debugging for Visual Studio   4.13.11-pre (400cfb1)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   15.9.18254.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   15.9.18254.1
Provides templates and integration for the Django web framework.

Python - IronPython support   15.9.18254.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   15.9.18254.1
Profiling support for Python projects.

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResXManager   1.28.1304.0
Manage localization of all ResX-Based resources in one place. Shows all resources of a solution and let's you edit the strings and their localizations in a well-arranged data grid.

SlowCheetah - XML config transforms   1.0
This package enables you to transform your app.config or any other XML file based on the build configuration. It also adds additional tooling to help you create XML transforms.

SQL Server Data Tools   15.1.61810.11040
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   15.9.20918.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Universal Windows Apps   15.0.28301.59
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

WiX Toolset Visual Studio Extension   0.9.21.62588
WiX Toolset Visual Studio Extension version 0.9.21.62588
Copyright (c) .NET Foundation and contributors. All rights reserved.

Xamarin   4.12.3.69 (d15-9@15fcf6b03)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.4 (128ba449c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Live Reload   0.3.27 (remotes/origin/dev@207abf7)
Provides live reload capabilities for Xamarin XAML.

Xamarin Templates   1.1.127 (e975299)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.0.38 (HEAD/61d16aa23)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.2.1.10 (f2a05ed)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### iOS Designer Logs
[2018-11-14 12:17:19.6] INFO: IDE notified that the list of assemblies referenced has changed
[2018-11-14 12:17:19.6] INFO: Not uploading assemblies because there is no remote session
[2018-11-14 12:18:37.6] PERF: Deployment time: 11789ms
[2018-11-14 12:18:38.4] INFO: Last login: Wed Nov 14 12:10:57 2018

[2018-11-14 12:18:38.4] INFO:  /Library/Frameworks/Mono.framework/Commands/mono64 /Users/jvergeer/Library/Caches/Xamarin/XMA/Agents/Designer/agent-128ba449cfdfbb78efcd87c831a9fd807dae2e5d/CSProxyHost.exe; echo "<<<<< Designer Remote Agent EOS >>>>>";
[2018-11-14 12:18:38.8] INFO: Joriss-Mac-mini:~ jvergeer$  /Library/Frameworks/Mono.framework/Commands/mono64 /Users/jvergeer/Library/Caches/Xamarin/XMA/Agents/Designer/agent-128ba449cfdfbb78efcd87c831a9fd807dae2e5d/CSProxyHost.exe; echo "<<<<< Designer Remote Agent EOS >>>>>";
[2018-11-14 12:18:38.8] INFO: Initializing CSProxyHost StdOut
[2018-11-14 12:18:38.8] INFO: Initializing CSProxyHost StdErr
[2018-11-14 12:18:39.0] INFO: 2018-11-14 12:18:39.096 mono64[9413:55226] 
[2018-11-14 12:18:39.0] INFO: Unhandled Exception:
[2018-11-14 12:18:39.0] INFO: System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions)
[2018-11-14 12:18:39.0] INFO:   at Registrar.Registrar+ObjCType.Add (Registrar.Registrar+ObjCMethod method, System.Collections.Generic.List`1[System.Exception]& exceptions) [0x00019] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-14 12:18:39.0] INFO:   at Registrar.Registrar.RegisterTypeUnsafe (System.Type type, System.Collections.Generic.List`1[System.Exception]& exceptions) [0x01181] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-14 12:18:39.0] INFO:   at Registrar.Registrar.RegisterType (System.Type type, System.Collections.Generic.List`1[System.Exception]& exceptions) [0x00013] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-14 12:18:39.0] INFO:   at Registrar.DynamicRegistrar.Register (System.Type type) [0x00003] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-14 12:18:39.0] INFO:   at ObjCRuntime.Class.Register (System.Type type) [0x00001] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-14 12:18:39.0] INFO:   at ObjCRuntime.Runtime.RegisterAssembly (System.Reflection.Assembly a) [0x0016a] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-14 12:18:39.0] INFO:   at ObjCRuntime.Runtime.RegisterAssembly (System.IntPtr a) [0x00007] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-14 12:18:39.0] INFO:   at ObjCRuntime.Runtime.register_assembly (System.IntPtr assembly, System.Int32& exception_gchandle) [0x00005] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-14 12:18:39.0] INFO: --- End of stack trace from previous location where exception was thrown ---
[2018-11-14 12:18:39.0] INFO:   at (wrapper managed-to-native) System.Object.wrapper_native_0x10dbd9c40()
[2018-11-14 12:18:39.0] INFO:   at ObjCRuntime.Runtime.EnsureInitialized () [0x0004b] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-14 12:18:39.0] INFO:   at AppKit.NSApplication.Init () [0x00016] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-14 12:18:39.0] INFO:   at CSProxyHost.MainClass.Main (System.String[] args) [0x000b0] in <859b10803c674bad953a45c2be47ba13>:0 
[2018-11-14 12:18:39.0] INFO: [ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions)
[2018-11-14 12:18:39.0] INFO:   at Registrar.Registrar+ObjCType.Add (Registrar.Registrar+ObjCMethod method, System.Collections.Generic.List`1[System.Exception]& exceptions) [0x00019] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-14 12:18:39.0] INFO:   at Registrar.Registrar.RegisterTypeUnsafe (System.Type type, System.Collections.Generic.List`1[System.Exception]& exceptions) [0x01181] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-14 12:18:39.0] INFO:   at Registrar.Registrar.RegisterType (System.Type type, System.Collections.Generic.List`1[System.Exception]& exceptions) [0x00013] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-14 12:18:39.0] INFO:   at Registrar.DynamicRegistegister (System.Type type) [0x00001] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-14 12:18:39.0] INFO:   at ObjCRuntime.Runtimrar.Register (System.Type type) [0x00003] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-14 12:18:39.0] INFO:   at ObjCRuntime.Class.Re.RegisterAssembly (System.Reflection.Assembly a) [0x0016a] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-14 12:18:39.0] INFO:   at ObjCRuntime.Runtime.RegisterAssembly (System.IntPtr a) [0x00007] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-14 12:18:39.0] INFO:   at ObjCRuntime.Runtime.register_assembly (System.IntPtr assembly, System.Int32& exception_gchandle) [0x00005] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-14 12:18:39.0] INFO: --- End of stack trace from previous location where exception was thrown ---
[2018-11-14 12:18:39.0] INFO:   at (wrapper managed-to-native) System.Object.wrapper_native_0x10dbd9c40()
[2018-11-14 12:18:39.0] INFO:   at ObjCRuntime.Runtime.EnsureInitialized () [0x0004b] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-14 12:18:39.0] INFO:   at AppKit.NSApplication.Init () [0x00016] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-14 12:18:39.0] INFO:   at CSProxyHost.MainClass.Main (System.String[] args) [0x000b0] in <859b10803c674bad953a45c2be47ba13>:0 
[2018-11-14 12:18:39.0] INFO: <<<<< Designer Remote Agent EOS >>>>>
[2018-11-14 12:18:39.6] ERROR: Could not connect to the remote mac:
System.IO.EndOfStreamException: The DesignerAgent crashed before it initialized
   at MonoTouch.Design.Client.SshAgentLauncher.StartCSProxyHost(SshClient client, String csproxyHostPath) in E:\A\_work\28\s\Xamarin.Designer.iOS\MonoTouch.Design.Client\Connection\SshAgentLauncher.cs:line 116
   at MonoTouch.Design.Client.SshAgentLauncher.LaunchAsync(ConnectionInfo info, String csproxyHostDirectory, CancellationToken token) in E:\A\_work\28\s\Xamarin.Designer.iOS\MonoTouch.Design.Client\Connection\SshAgentLauncher.cs:line 78
   at MonoTouch.Design.Client.SshAgentLauncher.<>c__DisplayClass6_0.<LaunchAsync>b__0() in E:\A\_work\28\s\Xamarin.Designer.iOS\MonoTouch.Design.Client\Connection\SshAgentLauncher.cs:line 42
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MonoTouch.Design.Client.SshAgentLauncher.<LaunchAsync>d__6.MoveNext() in E:\A\_work\28\s\Xamarin.Designer.iOS\MonoTouch.Design.Client\Connection\SshAgentLauncher.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MonoTouch.Design.Client.RemoteDesignerAgent.<CreateConnectionAsync>d__16.MoveNext() in E:\A\_work\28\s\Xamarin.Designer.iOS\MonoTouch.Design.Client\Connection\RemoteDesignerAgent.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.VisualStudio.IOS.Designer.MonoTouchDesignerPane.<InitializeAsync>d__70.MoveNext() in E:\A\_work\28\s\Xamarin.Designer.VisualStudio\src\VisualStudio.IOS.Designer\Editor\MonoTouchDesignerPane.cs:line 771

From the looks of it, it looks like that there is an mono version mismatch as `System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions)` required mono 5.14 (from other issues). But Visual Studio forces an installation of mono 5.12l.

Could it be related to an issue with a similar exception: #4384

> VS bug [#729609](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/729609)

**Comment by TheWass** [comment]
Same issue occurs with opening a xaml file in design view.  Same log, same circumstances, slightly different UI.
![XamlDesign](https://user-images.githubusercontent.com/3410388/48565615-f5cfb900-e8c6-11e8-8336-f0155f677b2c.png)

**Comment by keithjm** [comment]
I have the same issue when opening the storyboard and xib files, but the emulator still seems to work. It started when I upgraded to VS 15.9.  I filed a ticket with Microsoft and expect to hear back in the next few days. I will keep you posted.

**Comment by TheWass** [comment]
Here's a related ticket on the Visual Studio Developer Community site:
https://developercommunity.visualstudio.com/content/problem/383487/xamarin-ios-designer-not-working-with-159-and-xama.html

**Comment by tipa** [comment]
Oh jeez, so glad I am not alone with this. Even completely set up my MacOS system from scratch after I couldn't find anything about the issue in the web. Hope this gets resolved timely, developing on the Mac directly is a pain.

**Comment by Aguilex** [comment]
I'm sorry for this problem! It has now been fixed and will ship in an upcoming VS 15.9 service release.

**Comment by icanread** [comment]
I have confirmed that it's been fixed in Visual Studios 15.9.2 release.

**Comment by EphramDoyle** [comment]
i have the same and i have 15.9.4

**Comment by achrafj** [comment]
i have the same error and i have 15.9.6
