### ISSUE TITLE
Unable to pair VS 2019 (16.5.5) with macOS (Automatic Mac provisioning)

### ISSUE THREAD

**Issue by dops-at** [xamarin/xamarin-macios#8608]
### Steps to Reproduce

1. Open Visual Studio 2019 (16.5.5)
2. Pair to Mac (insert ssh credentials)
3. Mono, Xamarin.iOS get's installed
4. Error
`Couldn't connect to mac-01. Please try again.
There was an error while trying to connect the client vs4900myu to the Server.`

### Expected Behavior
Pairing successful
### Actual Behavior
Pairing doesn't work
### Environment

1. Visual Studio (Windows)
```
Microsoft Visual Studio Professional 2019
Version 16.5.5
VisualStudio.16.Release/16.5.5+30104.148
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Professional

Visual C++ 2019   00435-20310-92745-AA526
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.5.236.49856
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.5.236.49856
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.5.236.49856
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.4.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.5.236.49856
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.4.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Dotfuscator Community Edition   5.42.0.9514-e0e25f754
PreEmptive Protection - Dotfuscator CE

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IncrediBuild Build Acceleration   1.5.0.13
IncrediBuild effectively reduces compilation and development times by up to 90%.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.4.5000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.4.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.4.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30207.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.25+gdacdb9b7a1
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.5.514 (c4f36a9)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62003.05170
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.20225.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.8.0.0 for F# 4.7   16.5.0-beta.20181.6+85af456066acd4e76d2bc7821b44a325e46f2fca
Microsoft Visual F# Tools 10.8.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.5.000.533 (d16-5@9152e1b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.5.0.470 (remotes/origin/d16-5@681de3fd6)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.5.49 (0904f41)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.2.0.100 (d16-5/988c811)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c0c5c78
    Java.Interop: xamarin/java.interop/d16-5@fc18c54
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-5@9f4ed4b


Xamarin.iOS and Xamarin.Mac SDK   13.16.0.13 (b75deaf)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```
2. macOS
```
macOS 10.14.5 (18F132)
XCode 11.2.1 (11B500)
```

### Build Logs
1. Windows (2020-05-19_07-57-45.4900.Ide.log)
```
Xamarin.VisualStudio.TastyPackage|Information|0|Hooked up SDB tracing adapter
Xamarin.VisualStudio.TastyPackage|Information|0|Initialization finished
Xamarin|Information|0|Xamarin - 16.5.000.533-d16-5+9152e1b
Xamarin.VisualStudio.TastyPackage|Information|0|Hooked up SDB tracing adapter
Xamarin.VisualStudio.TastyPackage|Information|0|Initialization finished
Xamarin.VisualStudio.IOS.Messaging.LocalMessagingInitializer|Information|0|Connecting to Local Broker...
System.Net.Mqtt.Sdk.Bindings.TcpChannelFactory|Error|0|An error occurred while connecting via TCP to the endpoint address 127.0.0.1 and port 53951, to establish an MQTT connection
System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it 127.0.0.1:53951
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Mqtt.Sdk.Bindings.TcpChannelFactory.<CreateAsync>d__4.MoveNext()
System.Net.Mqtt.Sdk.MqttClientImpl|Error|0|System.Net.Mqtt.MqttException: An error occurred while connecting via TCP to the endpoint address 127.0.0.1 and port 53951, to establish an MQTT connection ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:53951
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Mqtt.Sdk.Bindings.TcpChannelFactory.<CreateAsync>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Net.Mqtt.Sdk.Bindings.TcpChannelFactory.<CreateAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Mqtt.Sdk.PacketChannelFactory.<CreateAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Mqtt.Sdk.MqttClientImpl.<InitializeChannelAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Mqtt.Sdk.MqttClientImpl.<ConnectAsync>d__29.MoveNext()
Xamarin.Messaging.Ssh.BrokerCommands|Information|0|Checking Broker 16.5.000.533 installation...
Xamarin.Messaging.Ssh.BrokerCommands|Information|0|Installing Broker 16.5.000.533...
Xamarin.Messaging.Ssh.BrokerCommands|Information|0|Starting Broker 16.5.000.533 in port 53951...
Xamarin.VisualStudio.IOS.XamarinIOSPackage|Warning|0|Initializing Xamarin.VisualStudio.IOS.XamarinIOSPackage.
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: processing ActiveProjectConfigurationChanged event
Xamarin.Messaging.Ssh.BrokerCommands|Information|0|Broker 16.5.000.533 started successfully
Xamarin.VisualStudio.IOS.Messaging.LocalMessagingInitializer|Information|0|Starting IDB Local Agent...
Xamarin.Messaging.Ssh.AgentCommands|Information|0|Checking Agent IDB.Local 16.5.000.533 installation...
Xamarin.Messaging.Ssh.MessagingService|Information|0|Installing Agent IDB.Local 16.5.000.533...
Xamarin.Messaging.Ssh.AgentCommands|Information|0|Installing Agent IDB.Local 16.5.000.533...
Xamarin.Messaging.Ssh.MessagingService|Information|0|Starting Agent IDB.Local 16.5.000.533...
Xamarin.Messaging.Ssh.AgentCommands|Information|0|Starting Agent IDB.Local 16.5.000.533 in port 53951...
Xamarin.Messaging.Ssh.AgentCommands|Information|0|Agent IDB.Local 16.5.000.533 started successfully
Xamarin.Messaging.Ssh.MessagingService|Information|0|Agent IDB.Local 16.5.000.533 is running
Xamarin.Messaging.Ssh.MessagingService|Information|0|Agent IDBLocal 16.5.000.533 is running
Xamarin.VisualStudio.IOS.Messaging.LocalMessagingInitializer|Warning|0|The required Apple Support libraries have not been found. Please ensure to have a valid iTunes installation in order to communicate with Apple devices in Windows. Windows Store iTunes installations are not supported right now.
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Server State transition from DisconnectedState to ConfiguringState on mac-01 (11.11.11.11)
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Checking host configuration for connecting to 'mac-01'...
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Checking SSH configuration...
System.Net.Mqtt.Sdk.ClientPacketListener|Warning|0|Client vs4900myu - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Initializing environment...
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Checking available disk space...
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Checking Mono installation...
Xamarin.Messaging.Ssh.SshCommands|Information|0|A valid Mono installation has been found at '/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono64'
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Checking Xamarin iOS installation...
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Checking host configuration for connecting to 'mac-01'...
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Server State transition from ConfiguringState to ConfiguredState on mac-01 (11.11.11.11)
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Host 'mac-01' is configured correctly
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Server State transition from ConfiguredState to ConnectingState on mac-01 (11.11.11.11)
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Starting connection to 'mac-01'...
System.Net.Mqtt.Sdk.Bindings.TcpChannelFactory|Error|0|An error occurred while connecting via TCP to the endpoint address 11.11.11.11 and port 57006, to establish an MQTT connection
System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it 11.11.11.11:57006
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Mqtt.Sdk.Bindings.TcpChannelFactory.<CreateAsync>d__4.MoveNext()
System.Net.Mqtt.Sdk.MqttClientImpl|Error|0|System.Net.Mqtt.MqttException: An error occurred while connecting via TCP to the endpoint address 11.11.11.11 and port 57006, to establish an MQTT connection ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 11.11.11.11:57006
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Mqtt.Sdk.Bindings.TcpChannelFactory.<CreateAsync>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Net.Mqtt.Sdk.Bindings.TcpChannelFactory.<CreateAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Mqtt.Sdk.PacketChannelFactory.<CreateAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Mqtt.Sdk.MqttClientImpl.<InitializeChannelAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Mqtt.Sdk.MqttClientImpl.<ConnectAsync>d__29.MoveNext()
Xamarin.Messaging.Ssh.BrokerCommands|Information|0|Checking Broker 16.5.000.533 installation...
Xamarin.Messaging.Ssh.MessagingCommands{System.String}|Information|0|Server directory /Users/myuser/Library/Caches/Xamarin/XMA/Broker/16.5.000.533 doesn't exist, hence the checksum can't be verified
Xamarin.Messaging.Ssh.BrokerCommands|Information|0|Installing Broker 16.5.000.533...
Xamarin.Messaging.Ssh.MessagingCommands{System.String}|Information|0|Server directory /Users/myuser/Library/Caches/Xamarin/XMA/Broker/16.5.000.533 doesn't exist, hence the checksum can't be verified
Xamarin.Messaging.Ssh.MessagingFileManager|Information|0|Uploading Broker.zip (192/1823 KB) 10%...
Xamarin.Messaging.Ssh.MessagingFileManager|Information|0|Uploading Broker.zip (368/1823 KB) 20%...
Xamarin.Messaging.Ssh.MessagingFileManager|Information|0|Uploading Broker.zip (560/1823 KB) 30%...
Xamarin.Messaging.Ssh.MessagingFileManager|Information|0|Uploading Broker.zip (736/1823 KB) 40%...
Xamarin.Messaging.Ssh.MessagingFileManager|Information|0|Uploading Broker.zip (912/1823 KB) 50%...
Xamarin.Messaging.Ssh.MessagingFileManager|Information|0|Uploading Broker.zip (1104/1823 KB) 60%...
Xamarin.Messaging.Ssh.MessagingFileManager|Information|0|Uploading Broker.zip (1280/1823 KB) 70%...
Xamarin.Messaging.Ssh.MessagingFileManager|Information|0|Uploading Broker.zip (1472/1823 KB) 80%...
Xamarin.Messaging.Ssh.MessagingFileManager|Information|0|Uploading Broker.zip (1648/1823 KB) 90%...
Xamarin.Messaging.Ssh.MessagingFileManager|Information|0|Uploaded Broker.zip 100%
Xamarin.Messaging.Ssh.BrokerCommands|Information|0|Starting Broker 16.5.000.533 in port 57006...
Xamarin.Messaging.Ssh.SshCommands|Information|0|A valid Mono installation has been found at '/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono64'
Xamarin.Messaging.Ssh.BrokerCommands|Information|0|Broker 16.5.000.533 started successfully
System.Net.Mqtt.Sdk.Bindings.TcpChannel|Warning|0|The underlying communication stream has completed sending bytes. The observable sequence will be completed and the channel will be disposed
System.Net.Mqtt.Sdk.ClientPacketListener|Warning|0|Client vs4900myu - Packet Channel observable sequence has been completed
System.Net.Mqtt.Sdk.MqttClientImpl|Warning|0|Client - Packet observable sequence has been completed, hence closing the channel
System.Net.Mqtt.Sdk.MqttClientImpl|Error|0|System.Net.Mqtt.MqttClientException: The client vs4900myu has been disconnected while trying to perform the connection
   at System.Net.Mqtt.Sdk.MqttClientImpl.<ConnectAsync>d__29.MoveNext()
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Server State transition from ConnectingState to DisconnectedState on mac-01 (11.11.11.11)
Xamarin.Messaging.Ssh.MessagingService|Warning|0|The underlying client has been disconnected by the remote host
Xamarin.Messaging.Ssh.MessagingService|Error|0|An error occurred on the underlying client while executing an operation. Details: The client vs4900myu has been disconnected while trying to perform the connection
Xamarin.Messaging.Client.MessagingConnection|Error|0|There was an error while trying to connect the client vs4900myu to the Server.
System.Net.Mqtt.MqttClientException: The client vs4900myu has been disconnected while trying to perform the connection
   at System.Net.Mqtt.Sdk.MqttClientImpl.<ConnectAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.Client.MessagingConnection.<ConnectAsync>d__21.MoveNext() in E:\A\_work\548\s\External\messaging\src\Xamarin.Messaging.Client\MessagingConnection.cs:line 64
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Starting connection to 'mac-01'...
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Server State transition from DisconnectedState to DisconnectingState on mac-01 (11.11.11.11)
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Starting disconnection from mac-01...
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Starting disconnection from mac-01...
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Server State transition from DisconnectingState to DisconnectedState on mac-01 (11.11.11.11)
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|The connection to 'mac-01' has been finished
Xamarin.Messaging.Integration.State.ServerStateContext|Error|0|Couldn't connect to mac-01. Please try again.
Xamarin.Messaging.Exceptions.MessagingException: There was an error while trying to connect the client vs4900myu to the Server. ---> System.Net.Mqtt.MqttClientException: The client vs4900myu has been disconnected while trying to perform the connection
   at System.Net.Mqtt.Sdk.MqttClientImpl.<ConnectAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.Client.MessagingConnection.<ConnectAsync>d__21.MoveNext() in E:\A\_work\548\s\External\messaging\src\Xamarin.Messaging.Client\MessagingConnection.cs:line 64
   --- End of inner exception stack trace ---
   at Xamarin.Messaging.Client.MessagingConnection.<ConnectAsync>d__21.MoveNext() in E:\A\_work\548\s\External\messaging\src\Xamarin.Messaging.Client\MessagingConnection.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.Ssh.SshMessagingConnection.<ConnectAsync>d__41.MoveNext() in E:\A\_work\548\s\External\messaging\src\Xamarin.Messaging.Ssh\SshMessagingConnection.cs:line 185
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.Ssh.MessagingService.<ConnectMqttAsync>d__91.MoveNext() in E:\A\_work\548\s\External\messaging\src\Xamarin.Messaging.Ssh\MessagingService.cs:line 658
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Xamarin.Messaging.Ssh.MessagingService.<ConnectAsync>d__75.MoveNext() in E:\A\_work\548\s\External\messaging\src\Xamarin.Messaging.Ssh\MessagingService.cs:line 352
System.Net.Mqtt.Sdk.ClientPacketListener|Warning|0|Client vs4900myu - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener|Warning|0|Client vs4900myu - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener|Warning|0|Client vs4900myu - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener|Warning|0|Client vs4900myu - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener|Warning|0|Client vs4900myu - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener|Warning|0|Client vs4900myu - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener|Warning|0|Client vs4900myu - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener|Warning|0|Client vs4900myu - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive

```

2. macOS (2020-05-19__07-57-46.4900.Broker.log)
```
Xamarin.Messaging.Broker.BrokerServer: Information: 0: Starting broker...: 2020-05-19 05:58:30Z
Xamarin.Messaging.Broker.BrokerAgent: Information: 0: Starting: Broker 16.5.000.533 ( PID = 74358 ): 2020-05-19 05:58:30Z
Xamarin.Messaging.Broker.BrokerAgent: Information: 0: Connecting Agent to the Broker...: 2020-05-19 05:58:30Z
Xamarin.Messaging.Broker.BrokerAgent: Information: 0: Initializing Agent context...: 2020-05-19 05:58:30Z
Xamarin.Messaging.Broker.BrokerAgent: Information: 0: Registering Agent message handlers...: 2020-05-19 05:58:30Z
```

> VS bug [#1131893](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1131893)

**Comment by whitneyschmidt** [comment]
@dops-at This looks more like an IDE issue than a problem with the Mac/iOS SDK. I've reassigned this bug to the VS team, updates will be posted here.
