### ISSUE TITLE
Xamarin Profiler fails when attempting to profile iOS application on Mac remote host

### ISSUE THREAD

**Issue by rc65** [xamarin/xamarin-macios#9487]
### Steps to Reproduce

1. Pair to mac with iOS device connected from Visual Studio on a windows machine.
1. Build Xamarin iOS project.
1. Set build target as the iOS device you want to deploy on.
1. Run Xamarin Profiler from Visual Studio or as standalone application.
1. Start profiling.

### Expected Behavior

The profiler should connect to the device and begin to profile the built application.

### Actual Behavior

Profiler fails to start profiling.

### Environment

![Xamarin Profiler Version](https://user-images.githubusercontent.com/9903380/91171908-3f237e00-e6d3-11ea-9d05-892ce407b469.png)

![OS X Version](https://user-images.githubusercontent.com/9903380/91172487-2c5d7900-e6d4-11ea-989b-537466a507ca.png)

```
Microsoft Visual Studio Enterprise 2019 (2)
Version 16.7.2
VisualStudio.16.Release/16.7.2+30413.136
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA894
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.7.532.28833
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2035807+72d099b977d3a85e65fa3b0614ca8cfc803fef02
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.7.532.28833
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.7.532.28833
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.7.532.28833
Azure Functions and Web Jobs Tools

C# Tools   3.7.0-6.20412.3+d3c3a44a4e7ad31cc75c59be0d3df4a19ff33878
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30701.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.79+ge3567815aa.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.7.5 (112c7bc)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62008.03130
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.20702.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.7.0-6.20412.3+d3c3a44a4e7ad31cc75c59be0d3df4a19ff33878
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.10.0.0 for F# 4.7   16.7.0-beta.20361.3+3ef6f0b514198c0bfa6c2c09fefe41a740b024d5
Microsoft Visual F# Tools 10.10.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.7.000.440 (d16-7@358f3c6)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.7.0.495 (remotes/origin/d16-7@79c0c522c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.7.85 (1bcbbdf)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.0.2.0 (d16-7/025fde9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 83105ba
    Java.Interop: xamarin/java.interop/d16-7@1f3388a
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f


Xamarin.iOS and Xamarin.Mac SDK   13.20.2.2 (817b6f72a)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Build Logs

```
XamarinProfiler.Core.ProfilerService Information: 0 : [2020-08-25 12:25:04.8943] ##########################################
XamarinProfiler.Core.ProfilerService Information: 0 : [2020-08-25 12:25:04.8958] # Xamarin Profiler version -  1.6.10.15
XamarinProfiler.Core.ProfilerService Information: 0 : [2020-08-25 12:25:04.8958] #  * Arch x86_64
XamarinProfiler.Core.ProfilerService Information: 0 : [2020-08-25 12:25:04.8958] ##########################################
XamarinProfiler.Core.ProfilerService Information: 0 : [2020-08-25 12:25:05.0019] initializing android platform
XamarinProfiler.Core.ProfilerService Information: 0 : [2020-08-25 12:25:05.0034] initializing ios platform
XamarinProfiler.Core.ProfilerService Information: 0 : [2020-08-25 12:25:05.0034] initializing mlpd platform
XamarinProfiler.Core.ProfilerService Information: 0 : [2020-08-25 12:25:05.1264] processing command line = --options=mode:usb,host:192.168.22.160,user:username,port:50105,name:Company iPad mini HR,family:ios,gc:sgen,maxframes:16 --type=ios --device=Company iPad mini HR --target=net.company.projectName --heapshot-mode=ondemand --heapshot-frequency=1000 --sampling-mode=cpu --sample-cycle-freq=100
XamarinProfiler.Core.ProfilerService Information: 0 : [2020-08-25 12:25:05.1483] processing command line = C:\Program Files (x86)\Xamarin\Profiler\XamarinProfiler.exe --type=ios --target=net.company.projectName --device=Company iPad mini HR --options=host:192.168.22.160,port:58549,user:username,family:ios,name:Company iPad mini HR,mode:usb
XamarinProfiler.Core.ProfilerService Information: 0 : [2020-08-25 12:25:07.9110] processing command line = --options=mode:usb,host:192.168.22.160,user:username,port:50105,name:Company iPad mini HR,family:ios,gc:sgen,maxframes:16 --type=ios --device=Company iPad mini HR --target=net.company.projectName --heapshot-mode=ondemand --heapshot-frequency=1000 --sampling-mode=cpu --sample-cycle-freq=100
XamarinProfiler.Windows.ViewModels.ProgressReport.ReportViewModel Information: 0 : [2020-08-25 12:25:07.9536] Initializing profiling...
XamarinProfiler.Windows.ViewModels.ProgressReport.ReportViewModel Information: 0 : [2020-08-25 12:25:07.9968] Connecting to 192.168.22.160 as username
XamarinProfiler.Windows.MainWindow Information: 0 : [2020-08-25 12:25:08.3985] StartRecording for net.company.projectName
System.Net.Mqtt.Sdk.MqttClientImpl Information: 0 : Client profiler7924rossc - Created new client session
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - First packet from Server has been received. Type: ConnectAck
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching ConnectAck message to flow ClientConnectFlow
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching SubscribeAck message to flow ClientSubscribeFlow
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching SubscribeAck message to flow ClientSubscribeFlow
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching SubscribeAck message to flow ClientSubscribeFlow
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching SubscribeAck message to flow ClientSubscribeFlow
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching Publish message to flow PublishReceiverFlow and topic profiler7924rossc/response/xma/clients
System.Net.Mqtt.Sdk.MqttClientImpl Information: 0 : Client profiler7924rossc - An application message for topic profiler7924rossc/response/xma/clients was received
XamarinProfiler.Windows.ViewModels.ProgressReport.ReportViewModel Information: 0 : [2020-08-25 12:25:08.7636] Deploying profiler agent to 192.168.22.160
Xamarin.Messaging.Ssh.MessagingCommands{Xamarin.Messaging.AgentInfo} Warning: 0 : Server checksum couldn't be verified because there were problems analyzing the content of: /Users/username/Library/Caches/Xamarin/XMA/Agents/ProfilerAgent/1.6.10.15
Xamarin.Messaging.Ssh.MessagingCommands{Xamarin.Messaging.AgentInfo} Warning: 0 : Server checksum couldn't be verified because there were problems analyzing the content of: /Users/username/Library/Caches/Xamarin/XMA/Agents/ProfilerAgent/1.6.10.15
Xamarin.Messaging.Ssh.MessagingService Information: 0 : Installing Agent ProfilerAgent 1.6.10.15...
Xamarin.Messaging.Ssh.MessagingCommands{Xamarin.Messaging.AgentInfo} Warning: 0 : Server checksum couldn't be verified because there were problems analyzing the content of: /Users/username/Library/Caches/Xamarin/XMA/Agents/ProfilerAgent/1.6.10.15
Xamarin.Messaging.Ssh.MessagingCommands{Xamarin.Messaging.AgentInfo} Warning: 0 : Server checksum couldn't be verified because there were problems analyzing the content of: /Users/username/Library/Caches/Xamarin/XMA/Agents/ProfilerAgent/1.6.10.15
Xamarin.Messaging.Ssh.MessagingScpClient Warning: 0 : An error occurred while using SCP Client. Trying again with a new SCP connection...
Renci.SshNet.Common.ScpException: scp: error: unexpected filename: 
   at Renci.SshNet.ScpClient.CheckReturnCode(Stream input)
   at Renci.SshNet.ScpClient.UploadFileModeAndName(IChannelSession channel, Stream input, Int64 fileSize, String serverFileName)
   at Renci.SshNet.ScpClient.Upload(Stream source, String path)
   at Xamarin.Messaging.Ssh.MessagingScpClient.<>c__DisplayClass16_0.<Upload>b__0()
   at Xamarin.Messaging.Ssh.MessagingScpClient.Execute(Action action, Boolean retry)
Xamarin.Messaging.Ssh.MessagingScpClient Warning: 0 : An error occurred while using SCP Client. Trying again with a new SCP connection...
Renci.SshNet.Common.ScpException: scp: error: unexpected filename: 
   at Renci.SshNet.ScpClient.CheckReturnCode(Stream input)
   at Renci.SshNet.ScpClient.UploadFileModeAndName(IChannelSession channel, Stream input, Int64 fileSize, String serverFileName)
   at Renci.SshNet.ScpClient.Upload(Stream source, String path)
   at Xamarin.Messaging.Ssh.MessagingScpClient.<>c__DisplayClass16_0.<Upload>b__0()
   at Xamarin.Messaging.Ssh.MessagingScpClient.Execute(Action action, Boolean retry)
Xamarin.Messaging.Ssh.SshCommandRunner Warning: 0 : Failed to execute '/bin/bash -c 'md5 -q "/tmp/ProfilerAgent-1.6.10.15-cf99f13d-a2bd-4ded-a7fa-34c936c16b85/ProfilerAgent.zip"'': ExitStatus = 1
Xamarin.Messaging.Ssh.SshCommandRunner Warning: 0 : Failed to execute '/bin/bash -c 'md5 -q "/tmp/ProfilerAgent-1.6.10.15-cf99f13d-a2bd-4ded-a7fa-34c936c16b85/ProfilerAgent.zip"'': ExitStatus = 1
Xamarin.Messaging.Ssh.SshCommandRunner Warning: 0 : md5: /tmp/ProfilerAgent-1.6.10.15-cf99f13d-a2bd-4ded-a7fa-34c936c16b85/ProfilerAgent.zip: No such file or directory

Xamarin.Messaging.Ssh.SshCommandRunner Warning: 0 : md5: /tmp/ProfilerAgent-1.6.10.15-cf99f13d-a2bd-4ded-a7fa-34c936c16b85/ProfilerAgent.zip: No such file or directory

Xamarin.Messaging.Ssh.MessagingFileManager Error: 0 : An error occurred while uploading files
Xamarin.Messaging.Ssh.Exceptions.SshCommandException: md5: /tmp/ProfilerAgent-1.6.10.15-cf99f13d-a2bd-4ded-a7fa-34c936c16b85/ProfilerAgent.zip: No such file or directory

   at Renci.SshNet.SshCommandExtensions.ThrowIfError(SshCommand command)
   at Xamarin.Messaging.Ssh.SshCommands.<RunBashCommandAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Xamarin.Messaging.Ssh.SshCommands.<GetFileChecksumAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Xamarin.Messaging.Ssh.MessagingFileManager.<UploadFileAsync>d__10.MoveNext()
Xamarin.Messaging.Ssh.MessagingFileManager Error: 0 : An error occurred while uploading files
Xamarin.Messaging.Ssh.Exceptions.SshCommandException: md5: /tmp/ProfilerAgent-1.6.10.15-cf99f13d-a2bd-4ded-a7fa-34c936c16b85/ProfilerAgent.zip: No such file or directory

   at Renci.SshNet.SshCommandExtensions.ThrowIfError(SshCommand command)
   at Xamarin.Messaging.Ssh.SshCommands.<RunBashCommandAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Xamarin.Messaging.Ssh.SshCommands.<GetFileChecksumAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Xamarin.Messaging.Ssh.MessagingFileManager.<UploadFileAsync>d__10.MoveNext()
Xamarin.Messaging.Ssh.MessagingService Error: 0 : Unable to install the Agent 'ProfilerAgent 1.6.10.15'
Xamarin.Messaging.Ssh.MessagingService Error: 0 : Unable to install the Agent 'ProfilerAgent 1.6.10.15'
Xamarin.Messaging.Ssh.MessagingService Error: 0 : !Unable to install the Agent 'ProfilerAgent 1.6.10.15'
Xamarin.Messaging.Ssh.MessagingService Error: 0 : !Unable to install the Agent 'ProfilerAgent 1.6.10.15'
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching SubscribeAck message to flow ClientSubscribeFlow
XamarinProfiler.Windows.ViewModels.ProgressReport.ReportViewModel Information: 0 : [2020-08-25 12:25:09.4337] Starting listener on port 51729
XamarinProfiler.Windows.ViewModels.ProgressReport.ReportViewModel Information: 0 : [2020-08-25 12:25:09.4481] Starting application net.company.projectName
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching SubscribeAck message to flow ClientSubscribeFlow
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching Publish message to flow PublishReceiverFlow and topic profiler7924rossc/error/xp/1.6.10.15/start-profiling
System.Net.Mqtt.Sdk.MqttClientImpl Information: 0 : Client profiler7924rossc - An application message for topic profiler7924rossc/error/xp/1.6.10.15/start-profiling was received
Xamarin.Messaging.Client.MessagingClient Error: 0 : An error occurred on client profiler7924rossc while executing a post for topic xp/1.6.10.15/start-profiling
Xamarin.Messaging.Exceptions.ReceiverNotFoundException: No receiver was found for topic xp/1.6.10.15/start-profiling
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Xamarin.Messaging.Client.MessagingClient.<PostAsync>d__23`2.MoveNext()
Xamarin.Messaging.Client.MessagingClient Error: 0 : An error occurred on client profiler7924rossc while executing a post for topic xp/1.6.10.15/start-profiling
Xamarin.Messaging.Exceptions.ReceiverNotFoundException: No receiver was found for topic xp/1.6.10.15/start-profiling
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Xamarin.Messaging.Client.MessagingClient.<PostAsync>d__23`2.MoveNext()
XamarinProfiler.Windows.MainWindow Error: 0 : [2020-08-25 12:25:09.4962] Error occured on run net.company.projectName: An error occurred on client profiler7924rossc while executing a post for topic xp/1.6.10.15/start-profiling
XamarinProfiler.Windows.MainWindow Error: 0 : [2020-08-25 12:25:09.4962] Error occured on run net.company.projectName: An error occurred on client profiler7924rossc while executing a post for topic xp/1.6.10.15/start-profiling
XamarinProfiler.Windows.ViewModels.ProgressReport.ReportViewModel Error: 0 : [2020-08-25 12:25:09.5155] Sorry, something went wrong trying to run net.company.projectName: An error occurred on client profiler7924rossc while executing a post for topic xp/1.6.10.15/start-profiling
XamarinProfiler.Windows.ViewModels.ProgressReport.ReportViewModel Error: 0 : [2020-08-25 12:25:09.5155] Sorry, something went wrong trying to run net.company.projectName: An error occurred on client profiler7924rossc while executing a post for topic xp/1.6.10.15/start-profiling
XamarinProfiler.Windows.ViewModels.ProgressReport.ReportViewModel Information: 0 : [2020-08-25 12:25:09.5160] Sorry, something went wrong trying to run net.company.projectName: An error occurred on client profiler7924rossc while executing a post for topic xp/1.6.10.15/start-profiling
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching PingResponse message to flow PingFlow
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching PingResponse message to flow PingFlow
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching PingResponse message to flow PingFlow
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching PingResponse message to flow PingFlow
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching PingResponse message to flow PingFlow
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching PingResponse message to flow PingFlow
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching PingResponse message to flow PingFlow
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching PingResponse message to flow PingFlow
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching PingResponse message to flow PingFlow
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching PingResponse message to flow PingFlow
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching PingResponse message to flow PingFlow
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching PingResponse message to flow PingFlow
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching PingResponse message to flow PingFlow
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching PingResponse message to flow PingFlow
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching PingResponse message to flow PingFlow
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching PingResponse message to flow PingFlow
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching PingResponse message to flow PingFlow
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching PingResponse message to flow PingFlow
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - No packet has been sent in 30 seconds. Sending Ping to Server to maintain Keep Alive
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching PingResponse message to flow PingFlow
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching UnsubscribeAck message to flow ClientUnsubscribeFlow
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Client profiler7924rossc - Dispatching UnsubscribeAck message to flow ClientUnsubscribeFlow
System.Net.Mqtt.Sdk.Bindings.TcpChannel Warning: 0 : The underlying communication stream has completed sending bytes. The observable sequence will be completed and the channel will be disposed
System.Net.Mqtt.Sdk.Bindings.TcpChannel Warning: 0 : The underlying communication stream has completed sending bytes. The observable sequence will be completed and the channel will be disposed
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - Packet Channel observable sequence has been completed
System.Net.Mqtt.Sdk.ClientPacketListener Warning: 0 : Client profiler7924rossc - Packet Channel observable sequence has been completed
System.Net.Mqtt.Sdk.MqttClientImpl Information: 0 : Client profiler7924rossc - Closing. Reason: SelfDisconnected
System.Net.Mqtt.Sdk.ClientPacketListener Information: 0 : Disposing System.Net.Mqtt.Sdk.ClientPacketListener...
System.Net.Mqtt.Sdk.PacketChannel Information: 0 : Disposing System.Net.Mqtt.Sdk.PacketChannel...
System.Net.Mqtt.Sdk.Bindings.TcpChannel Information: 0 : Disposing System.Net.Mqtt.Sdk.Bindings.TcpChannel...
Xamarin.Messaging.Ssh.MessagingService Information: 0 : The underlying client has been closed
```
### Example Project (If Possible)
Not possible.

> VS bug [#1179901](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1179901)

**Comment by nick5454** [comment]
Yep does not work from Visual Studio

**Comment by nick5454** [comment]
Scp fails, do we need to deploy something on mac first

**Comment by t-johnson** [comment]
Getting the same errors in the log. :(

**Comment by Knots23** [comment]
Same for me. I'm running the latest (stable) VS 2019 Enterprise on a Windows machine and the Mac is running 10.15.7. 
Building / Running our iOS app works normally.

**Comment by steffos** [comment]
Same here. VS 2019 Enterprise 16.8.6 and mac 10.15.7 and getting the following error message: 
"An error occurred on client profiler4892stefa while executing a post for topic xp/1.6.10.15/start-profiling
Xamarin.Messaging.Exceptions.ReceiverNotFoundException: No receiver was found for topic xp/1.6.10.15/start-profiling"

Building/running apps works fine.

I see this issue is labeled 'external-xamarin-vs' som I take it this is not the right place for this issue? If so, can someone tell me where it should be posted to get some attention?

**Comment by decriptor** [comment]
@steffos The ideal place would be the "Report a Problem...", however, I'm aware of this issue and am hoping to have it resolved soon. I can't promise anything just yet, but I will be updating this issue as soon as it is fixed.

**Comment by EnglishDave** [comment]
This still hasn't been fixed. What's the point of paying for an enterprise VS subscription if we can't use the enterprise features

**Comment by decriptor** [comment]
@EnglishDave Sorry about the long time this is taking. I'm actively work on a variety of things around the profiler. I'm hoping to have something out in the near future pending any unforeseen issues. If you'd like to email me my address is stepsha @ microsoft . com

**Comment by MatteoColombo** [comment]
Hello, is there any update about this? I'm having the same issue

**Comment by decriptor** [comment]
My apologies. I recently had to take off a fair bit of time, but I'm finally back this week. I don't have an update today, but hopefully soon.

**Comment by Fenki404** [comment]
Pleas talk to your team leader for some more resources on this software. This is just too expensive to wait that long for a Bug fix!

**Comment by decriptor** [comment]
I'm hoping to have some news and an update next week.

**Comment by decriptor** [comment]
I believe I might have a fix for this. I'm working on getting some testing on the latest build. If all goes well my next step will be to put together a release.

**Comment by BillFulton** [comment]
Super duper, Stephen!

**Comment by JimPickettSE** [comment]
When do you expect to release this fix?
